fix: grid item skelton cards size issue
kodadot/nft-gallery pull request #10040
Opened 2024-04-10 07:06 UTC by floyd-li

**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #9377
- [ ] Requires deployment <snek/rubick/worker>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality

#### Optional

- [ ] I've tested it at </ksm/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=13rv1SWoLg9Gb3tmvHPZxb7JbVy51BtMziX7k9WQGSJ7Kp3A)

#### Community participation

- [x] [Are you at KodaDot Ecosystem Telegram?](https://t.me/koda_eco)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

https://github.com/kodadot/nft-gallery/assets/16473062/40fc9e4b-e645-4f64-b6d9-a886fc9fa13d

2024-04-10 07:39 UTC, hassnian requested changes

2024-04-10 07:39 UTC, hassnian commented on components/shared/nftCard/NftCardSkeleton.vue
> +    minimal?: boolean
combine into one , `variant` prop

2024-04-10 07:39 UTC, hassnian commented on components/shared/nftCard/NftCardSkeleton.vue
> +      }">
do like this 

NftCard.vue

![CleanShot 2024-04-10 at 12 36 14@2x](https://github.com/kodadot/nft-gallery/assets/44554284/f4abdf8d-a20f-4fa6-b7fe-3939317d40af)

2024-04-10 08:19 UTC, daiagi commented on components/items/ItemsGrid/ItemsGrid.vue
> +}
missing a default return value

2024-04-10 14:42 UTC, prury commented
@floyd-li please resolve conversations

2024-04-10 14:44 UTC, prury commented
there is a super small skeleton shifting when you browse profile, no need to fix if its too complicated

2024-04-10 17:29 UTC, daiagi approved these changes

2024-04-11 04:01 UTC, hassnian approved these changes

2024-04-11 11:45 UTC, prury commented
@daiagi please check if conversations are good to go

2024-04-11 11:46 UTC, daiagi commented
@prury 

all good. may continue

2024-04-11 11:55 UTC, merged

2024-04-11 14:49 UTC, prury commented
pay 30 usd

2024-04-11 14:50 UTC, yangwao commented
😍 Perfect, I’ve sent the payout 
💵 $30 @ 8.26 USD/DOT ~ 3.632 $DOT
🧗 [13rv1SWoLg9Gb3tmvHPZxb7JbVy51BtMziX7k9WQGSJ7Kp3A](https://polkadot.subscan.io/account/13rv1SWoLg9Gb3tmvHPZxb7JbVy51BtMziX7k9WQGSJ7Kp3A)
🔗 [0xd2e1da10fec9d57ba3e7b382bd2e8d294e0a3d0abb08412bef188ea1707dd51b](https://polkadot.subscan.io/extrinsic/0xd2e1da10fec9d57ba3e7b382bd2e8d294e0a3d0abb08412bef188ea1707dd51b)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)