[POC] - graphql using gql-tada
kodadot/nft-gallery pull request #10197
Opened 2024-05-03 08:06 UTC by daiagi

## Context

- [x] Ref #185
- [ ] Requires deployment <worker/stick/speck>

## Screenshot 📸

2024-05-06 12:44 UTC, daiagi commented
this has grown larger then i intended


1. I have deleted all unused graphql queries
2. i have deleted some dead pages and their associated components => delete more dead queries
3. I have converted some queries to types ones, but it's a large job, so let's continue in a follow up


@Jarsen136 @preschian

2024-05-06 13:21 UTC, prury commented
Playwright detection: Collection banner/names are not loading

![image](https://github.com/kodadot/nft-gallery/assets/36627808/2fef74ad-0929-49b9-b1ea-9cb2d77895e6)

2024-05-06 13:34 UTC, daiagi commented
@prury 


yes i have noticed

fixed

2024-05-07 07:22 UTC, preschian commented
> 3\. but it's a large job, so let's continue in a follow up

Nice 👍🏻
Yes, there is no need to migrate it to one PR

Can you summarise a little bit of how to use it and the tradeoff? And mention internal dev

2024-05-07 08:34 UTC, daiagi commented
sure

first let's break this PR apart so it doesn't look so scary and big

1. 56 deleted graphql files (old and unused queries, spring cleanup)
2. 16 deleted `.vue` and `.ts` files. these are dead pages and their associated sub components (hot, sales, spotlight pages)
3. 1 deleted unused composable ([composables/drop/useCheckReferenDumVote.ts](https://github.com/kodadot/nft-gallery/pull/10197/files?file-filters%5B%5D=.ts&show-deleted-files=true&show-viewed-files=true#diff-7de5983aaef3a5f15810c23e65db6e80f7c716d7c3db891930854e92f7b571d4))
4.  3 deleted types i've created in #10176 

so far 76 deleted files

5. 8 new `.ts` files  typed fragments
6. 4 new `d.ts` files that contain the typings of the graphql clients, 1 file for the functions that take in a query text and return typed `DocumentNode`
7. 6 new typed queried

19 new files

so far 95 files

8. 6 edited componenets
9. 4 misclenious (package.json, tsconfig and such)

105 files

2024-05-08 16:18 UTC, vikiival commented
If it is suitable -
Aka for queries that already use subsquid/general it is ok to use typed queries

However for specific chains I would resolve Query path - or better checl when and why it was added back then

2024-05-12 07:27 UTC, daiagi commented
>if it is suitable -
Aka for queries that already use subsquid/general it is ok to use typed queries

However for specific chains I would resolve Query path - or better checl when and why it was added back then


i agree, this is a good tradeoff between both approaches


therefore, i will delete the typed clients that are chain specific, and will call `https://ahp.gql.api.kodadot.xyz/` GENERAL

2024-05-12 07:36 UTC, daiagi commented
cc @preschian @Jarsen136

2024-05-12 09:12 UTC, Jarsen136 approved these changes

2024-05-12 09:12 UTC, Jarsen136 commented on components/collection/CollectionHeader/CollectionBanner.vue
> +  console.log('debug collection.name', name)
Could you remove these `console.log` ?

2024-05-12 09:12 UTC, Jarsen136 commented on .gitignore
> +queries/clients/types
It does not work. I still see the types file on the commits.

![image](https://github.com/kodadot/nft-gallery/assets/31397967/94935ea7-cb48-442d-9e4b-f96b048c119a)

2024-05-12 09:13 UTC, Jarsen136 reviewed
.

2024-05-12 09:14 UTC, Jarsen136 requested changes
as comment above

2024-05-12 10:09 UTC, daiagi commented
thx @Jarsen136 

fixed

2024-05-12 10:16 UTC, Jarsen136 approved these changes

2024-05-13 04:44 UTC, preschian approved these changes
sorry for the delay, otherwise lgtm

Additionals:
- remove `~/components/spotlight` on `nuxt.config.ts`
- nitpick: separate `gql.tada` queries from raw graphql queries

<img width="276" alt="Screenshot 2024-05-13 at 11 33 26" src="https://github.com/kodadot/nft-gallery/assets/734428/8d1c0c48-07b3-488c-812d-527d4600b56e">

2024-05-13 04:44 UTC, preschian commented on tsconfig.json
> +            "tadaOutputLocation": "./queries/clients/types/ahp.d.ts"
The folder doesn't exist; it won't create the types on launch. Adjust it and ignore `*.d.ts` files

```suggestion
            "tadaOutputLocation": "./queries/clients/ahp.d.ts"
```

2024-05-13 04:44 UTC, preschian commented on components/collection/CollectionHeader/CollectionBanner.vue
> +    convertMarkdownToText(data.value?.collectionEntity?.meta?.description),
I'm getting this on `convertMarkdownToText()`

```
Argument of type 'string | null | undefined' is not assignable to parameter of type 'string | undefined'.
```

2024-05-13 07:42 UTC, daiagi commented
@preschian  Thank you

All done

2024-05-13 09:45 UTC, vikiival reviewed
~

2024-05-13 09:45 UTC, vikiival commented on queries/fragments/typed/nftSubsquid.ts
Prob delete as it is same as `nft.ts`

2024-05-13 09:45 UTC, vikiival commented on queries/fragments/typed/nft.ts
add `updatedAt` to be able to remove [nftSubsquid.ts](https://github.com/kodadot/nft-gallery/pull/10197/files#diff-c6737b7326d724e5a4bd9d632c5cacc43cbc57e29660d83854ef84475f83de5e)

2024-05-13 09:46 UTC, vikiival commented
Please @daiagi, @Jarsen136 and @prury go through app and make sure that every page and chain work as intended :)

2024-05-13 10:02 UTC, daiagi commented
@vikiival 



>Prob delete as it is same as nft.ts
>add updatedAt to be able to remove


done

2024-05-13 10:34 UTC, daiagi commented
i have scanned throuh

- home page (all chains)
- explore collections and items (all chains)
- my profile page
- drops home page
- single ahk drop page
- create pages
- single nfty page (all chains)
- single collection page (all chains)



**so far 0 graphql detected**

2024-05-13 12:06 UTC, daiagi commented
>How about trasactions like create collection,
list/buy NFT ?

i did buy and list 1 ahp nft

2024-05-13 12:08 UTC, Jarsen136 commented
I went through the website and did not find anything abnormal.

2024-05-13 12:08 UTC, prury commented
> > How about trasactions like create collection,
> > list/buy NFT ?
> 
> i did buy and list 1 ahp nft

i will perform transaction tests as well trough the day

2024-05-13 14:33 UTC, prury commented
NFT Transfer :white_check_mark: 
Change Price :white_check_mark: 
Collection Creation :white_check_mark: 
NFT Creation(List, copies) :white_check_mark: 
Mass buy :white_check_mark: 
Mass list :white_check_mark: 
Drop Mint :white_check_mark:

2024-05-13 14:41 UTC, prury commented
failing test can be ignored

2024-05-16 13:06 UTC, prury commented
i've resolved conversations, merging now

2024-05-16 13:06 UTC, merged