fix: Wrong share text on farcaster
kodadot/nft-gallery pull request #10201
Opened 2024-05-03 09:36 UTC by hassnian

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- fixed sn numbers
- added collection frame url
- [x] Closes #9982

## Needs QA check

- @kodadot/qa-guild please review

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD)

## Screenshot 📸

- [x] My fix has changed **something** on UI; 

<img src="https://github.com/kodadot/nft-gallery/assets/44554284/d1505943-ad30-4fba-b179-287b0ee7885b" width="600" />

2024-05-03 13:03 UTC, prury commented
can we ditch the total number of pieces on the share text? at least for me its a bit confusing wdyt

2024-05-04 06:27 UTC, hassnian commented
> can we ditch the total number of pieces on the share text? at least for me its a bit confusing wdyt

updated 

![CleanShot 2024-05-04 at 11 23 50@2x](https://github.com/kodadot/nft-gallery/assets/44554284/5a782dc3-f704-4eff-b1ec-7fe5eb69dc5b)

2024-05-04 10:40 UTC, exezbcz requested changes

2024-05-04 10:40 UTC, exezbcz commented on locales/en.json
> +    "dropNfts": "I've minted {0} generative art pieces on Koda",
Koda! 


will make it more exciting

2024-05-04 11:29 UTC, Jarsen136 approved these changes

2024-05-06 12:07 UTC, hassnian commented on locales/en.json
> +    "dropNfts": "I've minted {0} generative art pieces on Koda",
updated 🫡

2024-05-06 12:41 UTC, prury commented
@hassnian i can still see the total collection amount here when minting one:

![image](https://github.com/kodadot/nft-gallery/assets/36627808/cdde3f4a-fc7e-4063-9352-d3f7a256c54a)

2024-05-06 13:44 UTC, hassnian commented
> @hassnian i can still see the total collection amount here when minting one:
> 
> ![image](https://private-user-images.githubusercontent.com/36627808/328181722-cdde3f4a-fc7e-4063-9352-d3f7a256c54a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwMDMzMTMsIm5iZiI6MTcxNTAwMzAxMywicGF0aCI6Ii8zNjYyNzgwOC8zMjgxODE3MjItY2RkZTNmNGEtZmM3ZS00MDYzLTkzNTItZDNmN2EyNTZjNTRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA2VDEzNDMzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxYzM4MjM4MjljYWZiNDIyZDlhMDYyNjhlZTI1MjM2OGVjNTEwNWE5ZWVmMmJiZDA1MTBmZjc4NGNhZjQ0ZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.996GQjuFXPKuOW6917f0orcnRhDzKuSmVkVbRWJblHk)

fixed

![CleanShot 2024-05-06 at 18 42 21@2x](https://github.com/kodadot/nft-gallery/assets/44554284/07478451-93be-412b-bacc-f4e725cac5a3)

2024-05-06 16:09 UTC, exezbcz approved these changes

2024-05-07 07:29 UTC, preschian approved these changes

2024-05-07 07:29 UTC, preschian commented on components/common/successfulModal/ShareSocialsSection.vue
> +    social?: SocialMediaProps
eslint, default value

2024-05-07 12:50 UTC, hassnian commented on components/common/successfulModal/ShareSocialsSection.vue
> +    social?: SocialMediaProps
updated

2024-05-07 12:53 UTC, merged