fix Top Collection buttons
kodadot/nft-gallery pull request #10286
Opened 2024-05-13 13:44 UTC by FG-HJ

**Thank you for your contribution** to the [Koda - Generative Art Marketplace](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

(please remove design and QA checks below if not needed)

## Needs Design check

- @exezbcz please review

## Needs QA check

- @kodadot/qa-guild please review

## Context

- [x] Closes #<10267 >
- [ ] Requires deployment <worker/stick/speck>

#### Before submitting pull request, please make sure:

- [ ] My contribution builds **clean without any errors or warnings**
- [ ] I've merged recent default branch -- **main** and I've no conflicts
- [ ] I've tried to respect high code quality standards
- [ ] I've didn't break any original functionality

#### Optional

- [ ] I've tested it at </ahp/collection> 
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Did your issue had any of the "$" label on it?

- [ ] Fill up your DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=<My_Polkadot_Address_check_https://github.com/kodadot/nft-gallery/blob/main/REWARDS.md#creating-your-dot-address>)

#### Community participation

- [ ] [Are you at Koda Ecosystem Telegram?](https://t.me/koda_eco)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
![Uploading Screenshot_7.png…]()
![Uploading Screenshot_8.png…]()

2024-05-13 19:42 UTC, prury commented
i think changing the neobutton css directly affected too many items across app, can you come up with a different solution?

2024-05-14 03:54 UTC, hassnian requested changes
this change affects the entire app

as said here  https://github.com/kodadot/nft-gallery/issues/10267#issuecomment-2105606883

you need to override NeoButton's styles where that component is used, in this case TopCollections.vue

2024-05-14 04:25 UTC, hassnian commented
@FG-HJ you requested a new review but I don't see any new changes , forgot to push ?

2024-05-15 04:18 UTC, hassnian requested changes
`NeoButton.scss` shouldn't be changed at all 

just override the min-w  of`NeoButton.scss` inside `TopCollections.vue`

2024-05-16 12:09 UTC, hassnian commented on components/landing/topCollections/TopCollections.vue
> +          class="!min-w-[70px] md:!min-w-[110px] control flex-1 p-0 max-md:w-full px-4 mobile-padding"
```suggestion
          class="control flex-1 p-0 !min-w-[70px] max-md:w-full md:!min-w-[98px] px-4 mobile-padding"
```

why did you change `md:!min-w-[110px]` width amount ?

2024-05-16 14:28 UTC, prury commented
@FG-HJ there should not be changes in the pnpm-lock.yaml file in your PR

2024-05-16 17:07 UTC, closed without merging