feat: Add new check to code-checker
kodadot/nft-gallery pull request #10484
Opened 2024-06-18 09:48 UTC by hassnian

## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

- [x] Closes #10454

## Needs QA check

- @kodadot/qa-guild please review

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD)

## Screenshot 📸

- [x] My fix has changed **something** on UI; 

![CleanShot 2024-06-18 at 14 43 28@2x](https://github.com/kodadot/nft-gallery/assets/44554284/4d3219d9-3393-464b-908c-844375ec01a0)

![image](https://github.com/kodadot/nft-gallery/assets/44554284/288ada56-f84c-4b6c-980c-aa997baf0e86)

2024-06-18 11:06 UTC, vikiival reviewed
please consult kodahash :)

2024-06-18 11:06 UTC, vikiival requested changes

2024-06-18 11:06 UTC, vikiival commented on components/codeChecker/issueHint/NotUsingExternalResources.vue
> +  <script src="p5.js" />
[incorrect](https://github.com/vikiival/kodahash/blob/main/public/index.html)

```suggestion
  <script src="./p5.min.js">
```

2024-06-19 04:06 UTC, hassnian commented on components/codeChecker/issueHint/NotUsingExternalResources.vue
> +  <script src="p5.js" />
fixed

2024-06-19 08:48 UTC, vikiival commented on components/codeChecker/issueHint/NotUsingExternalResources.vue
>    <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.9.2/p5.js" />
```suggestion
  <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.9.2/p5.min.js" />
```

2024-06-19 08:49 UTC, vikiival commented
cc @Jarsen136

2024-06-19 08:49 UTC, vikiival approved these changes

2024-06-19 22:41 UTC, Jarsen136 approved these changes

2024-06-19 22:41 UTC, merged