Added stalebot
kodadot/nft-gallery pull request #10507
Opened 2024-06-19 23:05 UTC by TouchstoneTheDev

**Thank you for your contribution** to the [Koda - Generative Art Marketplace](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

(please remove design and QA checks below if not needed)

## Needs QA check

- @kodadot/qa-guild please review

## Context

- [x] Closes #9393
- [ ] Requires deployment <worker/stick/speck>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality

#### Optional

- [ ] I've tested it at </ahp/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Did your issue had any of the "$" label on it?

- [ ] Fill up your DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=<My_Polkadot_Address_check_https://github.com/kodadot/nft-gallery/blob/main/REWARDS.md#creating-your-dot-address>)

#### Community participation

- [x] [Are you at Koda Ecosystem Telegram?](https://t.me/koda_eco)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

2024-06-26 02:04 UTC, hassnian commented
this is going to close most of our issues (won't be keeping issues older than 180 days), some of them are still valid and shouldn't be closed

stale: 90 days 
closed: 90 days

should we change the amount of days? thoughts? @exezbcz @prury @kodadot/internal-dev

2024-06-26 08:15 UTC, vikiival commented on .github/workflows/stale.yml
> +    - cron: '00 12 * * *'
Once per week would be enough

```suggestion
    - cron: '0 0 * * SAT'

```

2024-06-26 08:15 UTC, vikiival commented on .github/workflows/stale.yml
> +          days-before-issue-close: 90
```suggestion
          days-before-issue-stale: 720
          days-before-issue-close: 720

```

2024-06-26 08:15 UTC, vikiival commented on .github/workflows/stale.yml
> +            activity in last 90 days. It will be closed in 90 days if no further activity occurs. Please
```suggestion
            activity in last 720 days. It will be closed in 90 days if no further activity occurs. Please

```

2024-06-26 08:16 UTC, vikiival commented on .github/workflows/stale.yml
> +            activity in the last 90 days. Thank you for your contributions!
```suggestion
            activity in the last 720 days. Thank you for your contributions!

```

2024-06-26 08:21 UTC, vikiival requested changes
I am happy to merge this as it would be amazing addition to this repository. 

However I am out of the capacity to sort closed by the bot.
There is a lot of briliant ideas by @yangwao and I would be sad to lost them.

Therefore I am proposing 720 days and we will be slowly decreasing. This number to the ideal 120-150 days

2024-06-26 09:06 UTC, exezbcz commented
> However I am out of the capacity to sort closed by the bot.

the bot will ping the issue that he will close right?

2024-06-26 09:12 UTC, vikiival commented on .github/workflows/stale.yml
> +          exempt-issue-labels: no stalebot,type/epic
```suggestion
          exempt-issue-labels: chief
```

2024-06-28 04:18 UTC, hassnian approved these changes

2024-07-01 07:44 UTC, vikiival approved these changes

2024-07-01 07:45 UTC, merged