🔧 collection mobile
kodadot/nft-gallery pull request #10573
Opened 2024-07-03 10:54 UTC by roiLeo

## PR Type

- [x] Refactoring
- [x] css to tailwind

## Needs Design check

- @exezbcz please review

## Needs QA check

- @kodadot/qa-guild please review

## Context

- [x] Same as #10564 
- [x] Closes #10572 

## Screenshot 📸

<img width="544" alt="Capture d’écran 2024-07-03 à 12 52 17 PM" src="https://github.com/kodadot/nft-gallery/assets/9987732/f3e5818d-98d6-4183-b6f8-4cc864b4d3c7">

2024-07-03 12:19 UTC, Jarsen136 approved these changes

2024-07-04 10:05 UTC, hassnian reviewed
follow up of #10564 , profile banner skeleton needs to be updated   

can you also fix this here?. 

thanks

![CleanShot 2024-07-04 at 14 58 19](https://github.com/kodadot/nft-gallery/assets/44554284/0a929404-c1e2-46d8-abe4-a10cff6112c8)

2024-07-04 12:03 UTC, roiLeo commented
<img width="544" alt="Capture d’écran 2024-07-04 à 2 00 06 PM" src="https://github.com/kodadot/nft-gallery/assets/9987732/d1ff6603-9a84-43f3-bedb-d80580d05223">

2024-07-05 10:13 UTC, hassnian requested changes
something broke 

<img src="https://github.com/kodadot/nft-gallery/assets/44554284/e3611176-ea01-4457-812c-8f270f5a72f1" width="300" />

2024-07-05 10:13 UTC, hassnian commented on components/collection/CollectionHeader/CollectionBanner.vue
> +              class="collection-banner-name font-bold title is-4 md:is-3"
no bulma classes, can you use tailwind instate

2024-07-05 10:13 UTC, hassnian requested changes
something broke 

<img src="https://github.com/kodadot/nft-gallery/assets/44554284/e3611176-ea01-4457-812c-8f270f5a72f1" width="300" />

2024-07-06 04:39 UTC, hassnian commented
![CleanShot 2024-07-06 at 09 35 09@2x](https://github.com/kodadot/nft-gallery/assets/44554284/bb00cf01-d947-4f97-ba48-395393b22d36)

2024-07-08 07:04 UTC, roiLeo commented
> profile picture scale down, from 144px to 100px, centered vertically in the banner

where the 40px padding comes from?

2024-07-10 05:15 UTC, hassnian commented
checked canary and it has the same issues, would appreciate if you could fix them , thanks

## profile

### desktop 

1. image banner padding should be (40px)
2. profile title should be 31px

https://github.com/kodadot/nft-gallery/assets/44554284/126dd4f6-f806-4686-aa9b-24d8e1a05fd3

### mobile

looks good

2024-07-10 06:39 UTC, roiLeo commented
> ## profile
> ### desktop
> 
>     1. image banner padding should be (40px)
>     2. profile title should be 31px

thank you for these clarifications, should be good now.
IMO it would be better to customize tailwind fontSize class than have specific size.

2024-07-10 10:03 UTC, hassnian commented
> thank you for these clarifications, should be good now. 

looking good, thanks! 

> IMO it would be better to customize tailwind fontSize class than have specific size.

if you want #10611  :)

2024-07-10 10:05 UTC, hassnian approved these changes

2024-07-13 06:13 UTC, merged