fix: Profile: If follower doesnot have profile picture leave that Polkadot wallet picture
kodadot/nft-gallery pull request #10583
Opened 2024-07-04 16:37 UTC by Jarsen136

**Thank you for your contribution** to the [Koda - Generative Art Marketplace](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix

## Needs QA check

- @kodadot/qa-guild please review

## Context

- [x] Closes #10580

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

![image](https://github.com/kodadot/nft-gallery/assets/31397967/8f767f6c-2cc7-4235-b97b-b67469ef4705)

2024-07-06 07:18 UTC, preschian approved these changes

2024-07-08 08:00 UTC, vikiival approved these changes

2024-07-08 08:00 UTC, vikiival commented
@Jarsen136 everything is failling

![Screenshot 2024-07-08 at 10 00 24](https://github.com/kodadot/nft-gallery/assets/22471030/e32b21f9-6256-42dc-a82f-cce25357cd9c)

2024-07-08 08:00 UTC, vikiival requested changes
Until failing CI resolved

2024-07-08 08:14 UTC, merged