Fix/click see all search
kodadot/nft-gallery pull request #10704
Opened 2024-07-29 13:16 UTC by codomposer

**Thank you for your contribution** to the [Koda - Generative Art Marketplace](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #<10650>
https://github.com/kodadot/nft-gallery/issues/10650

## Screenshot 📸
![image](https://github.com/user-attachments/assets/e8e0e8bf-8a0e-4ff1-9cb7-fc860adbc88d)
![image](https://github.com/user-attachments/assets/d9a7e35b-f015-4713-b8b1-072124513b07)
![image](https://github.com/user-attachments/assets/89989540-b400-452b-a023-ab7c87e69608)

2024-07-29 13:33 UTC, Jarsen136 requested changes

2024-07-31 03:59 UTC, hassnian commented on components/search/SearchSuggestion.vue
> +        path: `${path}`,
```suggestion
        path,
```

2024-07-31 03:59 UTC, hassnian commented on components/search/SearchSuggestion.vue
> +      ? ' selected-item'
```suggestion
      ? 'selected-item'
```

2024-07-31 08:35 UTC, exezbcz commented
it does not redirect to the explorer when first hitting the enter - its the first search i made on the page 
<img width="990" alt="image" src="https://github.com/user-attachments/assets/ef91bb6f-aa3d-4be6-acf7-d0cb0b1768bb">



looks like edge case, could you please investigate?

2024-07-31 09:26 UTC, codomposer commented
The functionality is working correctly. However, before getting all JavaScript and asset files, it does not function as expected. Unfortunately, there is no workaround for this issue.

2024-08-07 12:37 UTC, exezbcz commented
second review? @kodadot/internal-dev

2024-08-07 12:37 UTC, codomposer commented
https://github.com/kodadot/nft-gallery/issues/10650

2024-09-06 09:58 UTC, vikiival commented
Thank you for your contribution!
Seems that issue was not merged for one month, therefore I am closing that as stale.
Please pickup other p1/p2 issue ^-^.

2024-09-06 09:58 UTC, closed without merging