Developers sub page
kodadot/nft-gallery pull request #1075
Opened 2021-11-09 19:53 UTC by hisergiorojas

**Thank you for your contribution** to the KodaDot NFT gallery.

👇 Let's do a quick check before the merge. 

### PR type
- [ ] Bugfix 
- [x] Feature 
- [ ] Refactoring 

### Before submitting Pull Request, please make sure:
- [x] My contribution builds **clean without any errors or warnings**
- [] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted screenshot of demonstrated change in this PR

### Optional
- [ ] I've tested PR on mobile and everything works
- [ ] I found edge cases

### What's new? 
- [x] PR closes #361 
- [ ] <brief_description_of_what_I've_added>

### Had issue bounty label ?
- [ ] Fill up your KSM address: [Payout](https://kodadot.xyz/transfer/?target=<My_Kusama_Address>)

### Community participation
- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot
- [ ] My fix has changed **something** on UI, a screenshot for others, is best to understand changes.

2021-11-09 19:55 UTC, hisergiorojas commented
![Screenshot from 2021-11-09 11-51-58](https://user-images.githubusercontent.com/48057303/140995365-48651543-8418-424a-ae2c-81d07577c37e.png)

2021-11-10 08:43 UTC, yangwao commented
Before merging this we will merge `main` into `main-nuxt` to sync the stuff as to be sure everything is all right https://github.com/kodadot/nft-gallery/issues/1077

2021-11-10 08:51 UTC, roiLeo requested changes
branch outdated?
- You need to change other `<h1>` tag to something else
- change container size to match other pages
- not a big fan of `<br>`

2021-11-10 08:51 UTC, roiLeo commented on src/components/landing/Developers.vue
> +            <div class="column is-6 is-offset-3">
I would have remove these ```<div>``` to match container size (as seen in other pages)

2021-11-10 08:51 UTC, roiLeo commented on src/components/landing/Developers.vue
> +              <h1 class="subtitle">
Bad pratice (SEO) to use multiple h1, use h2 for subtitle

2021-11-10 16:54 UTC, yangwao commented
> branch outdated?
> 
> * You need to change other `<h1>` tag to something else
> * change container size to match other pages
> * not a big fan of `<br>`

Hey @hisergiorojas  Let's fix conflicts, avoid br and use h1,h2, accordingly to SEO practices

2021-11-11 20:52 UTC, hisergiorojas commented
Okay, I will fix the issue.

2021-11-12 11:20 UTC, yangwao commented
How users will find about this? Probably put link on the landing page. 

This should be emoji 'sparkles' ✨
![image](https://user-images.githubusercontent.com/5887929/141458221-ba7d4ec3-98da-4a5b-ac60-701f0d9f95ba.png)

> The good first issue **label isfor problems** or updates we think are ideal for beginners. 

Probably space is missing
![image](https://user-images.githubusercontent.com/5887929/141458458-9d9531f9-65cc-4570-aa14-1571607cf532.png)

Checking against recent [contributing.md](https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md)

Seems you are missing whole [section about Rewards](https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#rewards)

Let's add it please. 
![image](https://user-images.githubusercontent.com/5887929/141459058-4d5e1a9e-e3ab-462b-b3d9-0d664ef28627.png)

2021-11-12 11:43 UTC, yangwao commented
Added [Dynamics of PRs and avoiding stalled PRs section](https://github.com/kodadot/nft-gallery/blob/main-nuxt/CONTRIBUTING.md#dynamics-of-pull-requests)

2021-11-13 09:49 UTC, yangwao commented
Converted to draft as it's not ready for merge.
Lmk when you reflect new changes @hisergiorojas

2021-11-15 10:03 UTC, yangwao commented
Hey, I'm closing this as seems to lack progress and attention from PR author.

2021-11-15 10:03 UTC, closed without merging