🔧 columns & column bulma to tailwind
kodadot/nft-gallery pull request #11279
Opened 2024-12-20 13:52 UTC by roiLeo

part of #9013

2024-12-20 22:17 UTC, Jarsen136 requested changes
There is something style broken. Could you please test more cases?
<img width="1033" alt="image" src="https://github.com/user-attachments/assets/05239e4d-79d8-4a21-9db6-41483af5bce7" />

2024-12-23 10:47 UTC, preschian approved these changes

2024-12-23 19:07 UTC, Jarsen136 approved these changes

2024-12-26 11:27 UTC, vikiival commented
@roiLeo / @kodadot/internal-dev can someone pls resolve conflicts?

2025-01-03 11:14 UTC, merged