Feat hide tabs
kodadot/nft-gallery pull request #1133
Opened 2021-11-13 11:19 UTC by prachi00

**Thank you for your contribution** to the KodaDot NFT gallery.

👇 Do a quick check before the merge. 

### PR type
- [ ] Bugfix
- [ ] Feature
- [ ] Refactoring

### Before submitting Pull Request, please make sure:
- [ ] My contribution builds **clean without any errors or warnings**
- [ ] I've merged recent default branch -- **main** and I've no conflicts
- [ ] I've tried respect high code quality standards
- [ ] I've didn't break any original functionality
- [ ] I've posted screenshot of demonstrated change in this PR

### Optional
- [ ] I've tested PR on mobile and everything works
- [ ] I found edge cases

### What's new?
- [ ] PR closes #1120
- [ ] <brief_description_of_what_I've_added>

### Had issue bounty label ?
- [ ] Fill up your KSM address: 
[Payout](https://kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)

### Community participation
- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot
- [ ] My fix has changed **something** on UI, a screenshot for others, is best to understand changes.

2021-11-13 11:50 UTC, roiLeo requested changes

2021-11-13 11:50 UTC, roiLeo commented on src/views/Profile.vue
> +        <b-tab-item value="nft" :headerClass="!totalCreated ? 'is-hidden' : '' ">
```suggestion
        <b-tab-item value="nft" :headerClass="{'is-hidden': !totalCreated}" >
```
small refacto

2021-11-13 11:50 UTC, roiLeo commented on src/views/Profile.vue
> +        <b-tab-item value="sold" :headerClass="!totalSold ? 'is-hidden' : '' ">
same here

2021-11-15 09:14 UTC, roiLeo requested changes
Tested on /rmrk/u/F5DaGLPBkroG9tYGZPaaAaQWqzkNgJgjrz17FAmk1EVNKn9
It's not displaying "Sold" tab while this user has already sold nfts

2021-11-15 10:06 UTC, yangwao commented
Yeah, it's good to show up test suite where you testing it, probably you can add it to `TESTSUITE.md` file for case why

2021-11-15 14:54 UTC, prachi00 commented
> Tested on /rmrk/u/F5DaGLPBkroG9tYGZPaaAaQWqzkNgJgjrz17FAmk1EVNKn9 It's not displaying "Sold" tab while this user has already sold nfts

@roiLeo so the issue now is that how do we know the number of sold items? the graphql query only hits once the tab is actually clicked. 
Possible solution:
hit the graphql query for **nftListSold**  once the page loads to get the number of sold items

2021-11-15 15:07 UTC, roiLeo commented
> > Tested on /rmrk/u/F5DaGLPBkroG9tYGZPaaAaQWqzkNgJgjrz17FAmk1EVNKn9 It's not displaying "Sold" tab while this user has already sold nfts
> 
> @roiLeo so the issue now is that how do we know the number of sold items? the graphql query only hits once the tab is actually clicked. Possible solution: hit the graphql query for **nftListSold** once the page loads to get the number of sold items

It will be the same for Collected & Created.
Possible solution could be to create a new query only for the stats (Created/Collected/Collection/Sold)

2021-11-15 15:13 UTC, prachi00 commented
> > > Tested on /rmrk/u/F5DaGLPBkroG9tYGZPaaAaQWqzkNgJgjrz17FAmk1EVNKn9 It's not displaying "Sold" tab while this user has already sold nfts
> > 
> > 
> > @roiLeo so the issue now is that how do we know the number of sold items? the graphql query only hits once the tab is actually clicked. Possible solution: hit the graphql query for **nftListSold** once the page loads to get the number of sold items
> 
> It will be the same for Collected & Created. Possible solution could be to create a new query only for the stats (Created/Collected/Collection/Sold)

@roiLeo okay, can you tell me more about how to do this? like is there already an api that is giving out these details?

2021-11-17 10:25 UTC, prachi00 commented
> > @roiLeo okay, can you tell me more about how to do this? like is there already an api that is giving out these details?
> 
> Well, I'm not an expert on this field but you could try something with graphql to get multiple totalCount. I would do my tests on [graphqlbin](https://www.graphqlbin.com/v2/new) with magic SUBQUERY_URL

@roiLeo so I tried doing it using the spotlight api, I still couldn't find two issues tho:
1. Finding the count of **collected**
2. Using IDB, since I couldn't find any data for spotlight already there

2021-11-17 14:34 UTC, roiLeo approved these changes
Tested on: 
- /rmrk/u/CwXa36Dddsm4h7T1LDnXvtdTFmSfUg7ZVygZ7mv8m6DE19s
- /rmrk/u/FUEGFWoPPtX4XkRzEnZnMgwGKENscHXAiEZy6kcgaDz1BY6
- /rmrk/u/EfzipPaWQRa8p7RtfKqw2QUFrZDSbHcXVjuD9XEDJKaBw9a

We might need to check if there is a significant increase in loading time by adding this query

2021-11-17 14:34 UTC, roiLeo commented on src/views/Profile.vue
> +      const [data] :any = spotlightAggQuery(
```suggestion
      const [data]: any = spotlightAggQuery(
```

2021-11-17 14:34 UTC, roiLeo commented on src/views/Profile.vue
> +
this could be removed as it's not used anymore

2021-11-17 19:51 UTC, vikiival commented
To be honest I do no like the fix

1. It's a super big query
2. sold => currentOwner != issuer (yeah not great)

2021-11-17 19:56 UTC, vikiival requested changes
Super big query

2021-11-18 09:21 UTC, prachi00 commented
> To be honest I do no like the fix
> 
> 1. It's a super big query
> 2. sold => currentOwner != issuer (yeah not great)
> 
> My approach to this: just check if the first query (created) returns empty array and emit the change to the parent component :)
> 
> cc @roiLeo @prachi00

@vikiival you mean the query for sold items?

2021-11-18 12:50 UTC, yangwao commented
> just check if the first query (created) returns empty array and emit the change to the parent component :)

yes, i've proposed this as well :)

2021-11-18 13:03 UTC, vikiival commented
https://github.com/kodadot/nft-gallery/compare/main...1120-hide-created-when-empty

2021-11-18 13:06 UTC, yangwao commented
> cc @roiLeo @prachi00
> 
> [main...1120-hide-created-when-empty](https://github.com/kodadot/nft-gallery/compare/main...1120-hide-created-when-empty)

@prachi00 let's pick up this, it easiest way to resolve it and does the job, happy to proceed with payout :)

2021-11-18 13:27 UTC, prachi00 commented
> > cc @roiLeo @prachi00
> > [main...1120-hide-created-when-empty](https://github.com/kodadot/nft-gallery/compare/main...1120-hide-created-when-empty)
> 
> @prachi00 let's pick up this @vikiival solution, it easiest way to resolve it and does the job, happy to proceed with payout :)

Did the changes, not sure if its right or not tho. Also PS had to force push (with lease) since I had to delete my previous commit

2021-11-18 13:51 UTC, roiLeo approved these changes

2021-11-18 14:26 UTC, yangwao commented
Looks good BUT when I open https://deploy-preview-1133--nftkodadot.netlify.app/rmrk/u/DgCNKpvqeg29wsMsUDLcYP7Kqcc4pW963F7mj2uRe8Kk6Jm

It just keeps hanging on collected. 
![image](https://user-images.githubusercontent.com/5887929/142433747-4c947772-dea7-4724-84d4-fbea86b0f26d.png)


I suggest you should watch totalcollections and if zero then set active tab to collected

2021-11-18 14:50 UTC, prachi00 commented
> Looks good BUT when I open https://deploy-preview-1133--nftkodadot.netlify.app/rmrk/u/DgCNKpvqeg29wsMsUDLcYP7Kqcc4pW963F7mj2uRe8Kk6Jm
> 
> It just keeps hanging on collected. ![image](https://user-images.githubusercontent.com/5887929/142433747-4c947772-dea7-4724-84d4-fbea86b0f26d.png)
> 
> I suggest you should watch totalcollections and if zero then set active tab to collected

@yangwao done

2021-11-18 16:06 UTC, vikiival approved these changes

2021-11-20 13:59 UTC, yangwao commented
nice works for me now!
sent payout https://kusama.subscan.io/extrinsic/10177383-7

2021-11-20 13:59 UTC, merged