Fixing styles on gallery item page
kodadot/nft-gallery pull request #1134
Opened 2021-11-13 13:42 UTC by MiracleCorunus

**Thank you for your contribution** to the KodaDot NFT gallery.

👇 Do a quick check before the merge. 

### PR type
- [x ] Bugfix
- [ ] Feature
- [x ] Refactoring

### What's new?
- [x ] #958 related

### Before submitting Pull Request, please make sure:
- [ x] My contribution builds **clean without any errors or warnings**
- [ x] I've merged recent default branch -- **main** and I've no conflicts
- [ x] I've tried respect high code quality standards
- [ x] I've didn't break any original functionality
- [ x] I've posted screenshot of demonstrated change in this PR

### What I've done
- Restyling the structure of page.
- Make price chart and history chart as foldable.
- Merge Price box with Actions if it's for Collecting and not the owner of NFT
- When creator, showing rest buttons would be shown.

### Screenshot
- [x ] My fix has changed **something** on UI, a screenshot for others, is best to understand changes.
![image](https://user-images.githubusercontent.com/83771788/141645920-d0f1438f-76e4-4862-a45f-fdc1112074d6.png)
![image](https://user-images.githubusercontent.com/83771788/141645935-02fc0637-f7fa-4e66-8014-027d70bf7487.png)
![image](https://user-images.githubusercontent.com/83771788/141645951-08c6a69d-57b9-47ba-904c-87bd440f445e.png)

2021-11-13 18:16 UTC, yangwao commented
Added test case https://deploy-preview-1134--nftkodadot.netlify.app/rmrk/detail/7479313-7a147cba01afccbf17-GA-GENERATIVE_ASTERISM_23-0000000000000023

2021-11-13 18:21 UTC, yangwao commented
Hey price chart doesn't work for me 
![image](https://user-images.githubusercontent.com/5887929/141654855-cd8cf3e6-70d1-40e0-8c6f-a25e4aada580.png)

2021-11-15 10:02 UTC, yangwao commented
Hello @MiracleCorunus have you made any progress? 
Till it's not fixed I'll put this PR as a draft.

2021-11-15 12:48 UTC, yangwao commented
Hey, @roiLeo @vikiival let's do a quick review, seems most of the code looks working to me!

Price chart works, seems that's why added timeout there?
 
![image](https://user-images.githubusercontent.com/5887929/141784695-2e3add3a-26f7-4bce-b64f-d9a4b9ca3682.png)

2021-11-15 13:32 UTC, yangwao commented
Added test case https://deploy-preview-1134--nftkodadot.netlify.app/rmrk/detail/7479313-7a147cba01afccbf17-GA-GENERATIVE_ASTERISM_23-0000000000000023

2021-11-15 14:00 UTC, roiLeo requested changes
- Could you please lint your code before pushing with `yarn lint --fix`
- We will need to refactor the function that map "event" to "interaction" into something reusable
- There is a whitespace between nft card & nft name while logged off
pic:
![Screenshot 2021-11-15 at 15-00-22 GenerativeAsterism #23](https://user-images.githubusercontent.com/9987732/141794623-1d696879-62dd-435d-a1af-63caa0af1ccd.png)

2021-11-15 15:26 UTC, MiracleCorunus commented on src/components/rmrk/Gallery/HistoryPriceChart.vue
> +  }
I think there was delay for loading the pricechart so it can't load exactly,
So I made some delay for loading the price chart

2021-11-15 15:26 UTC, MiracleCorunus commented on src/components/rmrk/Gallery/HistoryPriceChart.vue
> +        event['To'] = newEvent['meta']
Okay, sure

2021-11-15 15:28 UTC, MiracleCorunus commented on src/components/rmrk/Gallery/GalleryItem.vue
> +        <div class="column is-12">
got it

2021-11-16 10:29 UTC, yangwao commented
hey, @MiracleCorunus how did you resolve RoiLeo's suggestions? Because I see resolved but not new commit 👀

2021-11-17 12:48 UTC, yangwao commented
We should test this one before merging 👀 
As lot of things might changed

2021-11-18 12:55 UTC, yangwao commented
@MiracleCorunus can you check why charts not working in your PR? 

This is test case https://deploy-preview-1134--nftkodadot.netlify.app/rmrk/detail/9624153-7c95ac83655cdc8b26-ACV04-DINOS_PLANET_57-0000000000000057 

![image](https://user-images.githubusercontent.com/5887929/142418980-479055fa-54ab-4721-b930-ef4392eab365.png)

Please remove double texts, like price chart when unfolded 
![image](https://user-images.githubusercontent.com/5887929/142419142-17cdab9f-0b7f-4287-bffb-ea1c97fc91b1.png)

Remove second "history" when unfolded

![image](https://user-images.githubusercontent.com/5887929/142419173-d3cad40c-9047-42a1-8f93-a848ca82591c.png)

2021-11-18 13:03 UTC, yangwao commented
Hey @MiracleCorunus we want to close on this. 
I'll send you a lower bounty as you lack responsive be around and quality code. 
Please update your KSM address in PR template in this issue and I can process payout.

Let's pick probably easier issue next time, seems this one was quite complex and hard for you.

2021-11-18 13:04 UTC, merged

2021-11-20 00:57 UTC, MiracleCorunus commented
This is my Kusama Wallet Address

HcEvTkvAPYEEGEndFV9sMmS3P83jdtwhwZq37GfdzA3mLrL

2021-11-20 00:57 UTC, MiracleCorunus commented
This is my Kusama Wallet Address

HcEvTkvAPYEEGEndFV9sMmS3P83jdtwhwZq37GfdzA3mLrL

2021-11-20 13:07 UTC, yangwao commented
> This is my Kusama Wallet Address
> 
> HcEvTkvAPYEEGEndFV9sMmS3P83jdtwhwZq37GfdzA3mLrL

Payment sent https://kusama.subscan.io/extrinsic/10176854-4
Thank you