Generate payment link for transfer
kodadot/nft-gallery pull request #1329
Opened 2021-11-27 16:44 UTC by prachi00

**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇  _ Do a quick check before the merge. 

### PR type
- [ ] Bugfix
- [ ] Feature
- [ ] Refactoring

### Before submitting Pull Request, please make sure:
- [ ] My contribution builds **clean without any errors or warnings**
- [ ] I've merged recent default branch -- **main** and I've no conflicts
- [ ] I've tried respect high code quality standards
- [ ] I've didn't break any original functionality
- [ ] I've posted screenshot of demonstrated change in this PR

### Optional
- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything works
- [ ] I found edge cases

### What's new?
- [ ] PR closes #1316
- [ ] Changed the location, wasn't fitting well right next to the usd

### Had issue bounty label ?
- [ ] Fill up your KSM address: 
[Payout](https://kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)

### Community participation
- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot
- [ ] My fix has changed **something** on UI, a screenshot for others, is best to understand changes.
<img width="818" alt="Screenshot 2021-11-27 at 10 10 28 PM" src="https://user-images.githubusercontent.com/39299315/143689687-e5877d8f-c9dd-4b23-b00b-7cdc13299366.png">

2021-11-29 11:11 UTC, vikiival requested changes
I would personally put the button down (next to submit?)

2021-11-29 11:11 UTC, vikiival commented on src/components/transfer/Transfer.vue
> +    return `https://nft.kodadot.xyz/transfer?target=${this.destinationAddress}&usdamount=${this.usdValue}&donation=true`;
instead of `https://nft.kodadot.xyz/` use `${window.location.origin}`

2021-11-29 14:43 UTC, prachi00 commented
> I would personally put the button down (next to submit?)

@vikiival done, changed position

2021-11-29 17:30 UTC, roiLeo requested changes
checked buttons on mobile view and it looks like it's missing some space.
![Screenshot 2021-11-29 at 18-22-39 KodaDot - Kusama NFT Market Explorer Low Carbon NFTs](https://user-images.githubusercontent.com/9987732/143914593-8db4ebbc-5c93-4a15-a020-548dc525e086.png)

You should check [Buefy buttons ](https://buefy.org/documentation/button/) doc to replace `<b-field>`

2021-11-29 17:30 UTC, roiLeo commented on src/components/transfer/Transfer.vue
> +            <b-field class="mb-3 ml-3" v-show="destinationAddress">
you don't need `mb-3 ml-3`class here

2021-11-30 08:15 UTC, roiLeo requested changes
![Screenshot 2021-11-30 at 09-07-09 KodaDot - Kusama NFT Market Explorer Low Carbon NFTs](https://user-images.githubusercontent.com/9987732/144010096-bf3ef368-14d2-41e7-a136-1298879c30b2.png)

You don't need magic css to fix this.

use `<div class="buttons">` as a wrapper

// TODO:
- remove line 81
- remove class paymentLink
- replace button wrapper `<b-field>` by `<div class="buttons">`

2021-11-30 08:15 UTC, roiLeo commented on src/components/transfer/Transfer.vue
> +
```suggestion

```

2021-11-30 13:03 UTC, yangwao commented on src/components/transfer/Transfer.vue
> +
![image](https://user-images.githubusercontent.com/5887929/144052378-4d6ac5b1-7eb8-46fc-8a3d-4da24d0af848.png)

2021-11-30 13:04 UTC, yangwao commented
Let me know whenever I can test through

2021-11-30 14:15 UTC, yangwao commented
@prachi00 let's update the URL live in the address bar once I'll put the address and USD amount there :)

2021-12-01 07:23 UTC, prachi00 commented
> @prachi00 let's update the URL live in the address bar once I'll put the address and USD amount there :)

@yangwao @roiLeo have done the changes mentioned, you can test now, let me know if there are still any issues you see, thanks

2021-12-01 07:31 UTC, roiLeo approved these changes
lgtm, what will happen when adding new currency #939?

2021-12-01 10:56 UTC, yangwao commented
> > @prachi00 let's update the URL live in the address bar once I'll put the address and USD amount there :)
> 
> @yangwao @roiLeo have done the changes mentioned, you can test now, let me know if there are still any issues you see, thanks

Seems when I open https://deploy-preview-1329--nftkodadot.netlify.app/transfer?usdamount=100&target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU it won't make me able to submit the transaction

2021-12-01 11:01 UTC, yangwao commented
Payout sent https://kusama.subscan.io/extrinsic/10331792-15
@prachi00 let's pick #1361 to finish it there, merging this one, so it's not blocking at this stage and we can release other stuff :)
Looking forward in #1361

2021-12-01 11:01 UTC, merged