966 Transform URL from other galleries into kodadot
kodadot/nft-gallery pull request #1339
Opened 2021-11-29 16:12 UTC by vikiival

- :top: updated can-i-use
- :tada: url transformer is working correclty
- :white_check_mark: updated tests for url transformer
- :lipstick: Disabled input can accept readonly prop
- :rocket: added Tranform component
- :earth_americas: added translation for the transform
- :zap: added translations, added transform to navbar, added ?url param

Thank you for your contribution to the KodaDot NFT gallery, 
we really appreciate your contribution!

### PR type
- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

### Before submitting this PR, please make sure:
- [x] Your code builds clean without any erros or warnigns
- [x] You've posted screenshot of demonstrated change in this PR
- [x] Merged recent default branch, **main** and you have no conflicts
- [x] Didn't break any original functionality 

### Optional
- [ ] You've tested it on mobile
- [ ] Are there any edge cases? Name if any 

### What's new? (may be part of changelog)
- closes #966

2021-11-29 17:08 UTC, roiLeo requested changes

2021-11-29 17:08 UTC, roiLeo commented on src/views/Transform.vue
> +    <div class="column is-6 is-offset-3">
I would change it by 
```html
<div class="columns is-centered">
  <div class="column is-half">
```

2021-11-29 17:08 UTC, roiLeo commented on src/views/Transform.vue
> +      <section>
You could try it with:
```html
<section class="section">
```
to add a gutter

2021-11-29 20:55 UTC, vikiival commented on src/views/Transform.vue
> +  protected url = ''
It's automatically given from the default value. If I add `string` eslint will shout

2021-11-30 07:26 UTC, roiLeo requested changes

2021-11-30 07:26 UTC, roiLeo commented on src/views/Transform.vue
> +            $t('Transform')
```suggestion
          {{ $t('Transform') }}
```
oups! my bad.

2021-11-30 13:17 UTC, merged