#1326 tooltip in profile
kodadot/nft-gallery pull request #1484
Opened 2021-12-10 14:38 UTC by prachi00

**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇  _ Do a quick check before the merge. 

### PR type
- [ ] Bugfix
- [ ] Feature
- [ ] Refactoring

### Before submitting Pull Request, please make sure:
- [ ] My contribution builds **clean without any errors or warnings**
- [ ] I've merged recent default branch -- **main** and I've no conflicts
- [ ] I've tried respect high code quality standards
- [ ] I've didn't break any original functionality
- [ ] I've posted screenshot of demonstrated change in this PR

### Optional
- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything works
- [ ] I found edge cases

### What's new?
- [ ] PR closes #1404 
- [ ] <brief_description_of_what_I've_added>

### Had issue bounty label ?
- [ ] Fill up your KSM address: [Payout](https://kodadot.xyz/transfer/?target=<My_Kusama_Address>)

### Community participation
- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot
- [ ] My fix has changed **something** on UI, a screenshot for others, is best to understand changes.

2021-12-10 14:47 UTC, roiLeo requested changes
- Duplicate Tabs in profile

2021-12-10 14:47 UTC, roiLeo commented on pages/rmrk/u/_id.vue
> +        class="collection-tabs"
```suggestion
```

2021-12-10 14:47 UTC, roiLeo commented on pages/rmrk/u/_id.vue
> +        </b-tab-item> -->
```suggestion
```

2021-12-10 14:49 UTC, yangwao commented
yeah works for me original feature, 

![image](https://user-images.githubusercontent.com/5887929/145592768-7fc0faa1-bb5f-427f-ae83-a669d07e99aa.png)

but behaves broken, might not be related to this commit, might be 

![image](https://user-images.githubusercontent.com/5887929/145592816-0f5fa4bf-f167-45f2-8793-877a01f40ab3.png)

2021-12-15 07:35 UTC, roiLeo commented
Hey! @prachi00 It seems that we still have the duplicated tabs here

2021-12-15 08:22 UTC, prachi00 commented
> Hey! @prachi00 It seems that we still have the duplicated tabs here

@roiLeo where? I am unable to see it

2021-12-15 08:27 UTC, roiLeo commented
> > Hey! @prachi00 It seems that we still have the duplicated tabs here
> 
> @roiLeo where? I am unable to see it

See preview:
https://deploy-preview-1484--koda-nuxt.netlify.app/rmrk/u/HCWd8fTKDejDe8nq2qJXzF3U9J3DZx3SQXUNmwLxC1sLrso
Something went wrong.

2021-12-15 10:10 UTC, prachi00 commented
> > > Hey! @prachi00 It seems that we still have the duplicated tabs here
> > 
> > 
> > @roiLeo where? I am unable to see it
> 
> See preview: https://deploy-preview-1484--koda-nuxt.netlify.app/rmrk/u/HCWd8fTKDejDe8nq2qJXzF3U9J3DZx3SQXUNmwLxC1sLrso Something went wrong.

Have fixed this

2021-12-15 10:23 UTC, roiLeo approved these changes
lgtm, one small change + indentation fix on `<b-tabs>`

2021-12-15 10:23 UTC, roiLeo commented on pages/rmrk/u/_id.vue
> +        size="is-medium"
```suggestion
```

2021-12-16 19:53 UTC, yangwao commented
Perfect, I’ve sent the payout 
https://kusama.subscan.io/extrinsic/0x20b6b4092c333f579ea953c5b322924a4e1be8f7950b3abbd2185d1f1d15476d

Let’s grab another issue and get rewarded! 
https://github.com/kodadot/nft-gallery/issues/

2021-12-16 19:53 UTC, merged