added unique collectors column in spotlight
kodadot/nft-gallery pull request #1504
Opened 2021-12-12 14:35 UTC by lohba

**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇  _ Do a quick check before the merge. 

### PR type
- [ ] Bugfix
- [X] Feature
- [ ] Refactoring

### Before submitting Pull Request, please make sure:
- [X] My contribution builds **clean without any errors or warnings**
- [X] I've merged recent default branch -- **main** and I've no conflicts
- [X] I've tried respect high code quality standards
- [X] I've didn't break any original functionality
- [X] I've posted screenshot of demonstrated change in this PR

### Optional
- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything works
- [ ] I found edge cases

### What's new?
- [X] PR closes ##1455
- [X] Added Unique Collectors Column 

### Had issue bounty label ?
- [X] Fill up your KSM address: [Payout](https://kodadot.xyz/transfer/?target=EAeSkdwjgMBmVFcACVFGzqxmGqib8k8uXdNmtWTcWsLoGPU)

### Community participation
- [X] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot
- [X] My fix has changed **something** on UI, a screenshot for others, is best to understand changes.
![Screen Shot 2021-12-12 at 9 32 22 AM](https://user-images.githubusercontent.com/55772762/145716620-12ff2ef9-7308-48ee-9166-2c2b83ebb1ad.png)

2021-12-13 11:27 UTC, yangwao commented
Curious, is there is mathematical annotation for unique? @vikiival @roiLeo  
If so, @lohba let's add it and add an explanation tooltip (don't forget put translations to en.json) and I can raise bounty! :)

2021-12-13 15:44 UTC, roiLeo requested changes
We just need to sync with main branch as it has already been done.
I'm not a fan of `uniqueCollectorFn` because it will remove nft that belongs to issuer.

> Curious, is there is mathematical annotation for unique? @vikiival @roiLeo If so, @lohba let's add it and add an explanation tooltip (don't forget put translations to en.json) and I can raise bounty! :)

From Wikipedia, it's "∃!"

2021-12-14 02:14 UTC, lohba commented
Thanks for the feedback @roiLeo @yangwao. I ended up using `uniqueCollectorFn` because while trying to reuse the unique collection number from CollectionItem, which queries from `nftListByCollection`,  SpotflightTable queries from `collectionIssuerList`. Is there a simple way to sync this up?

2021-12-14 07:39 UTC, roiLeo commented
> Thanks for the feedback @roiLeo @yangwao. I ended up using `uniqueCollectorFn` because while trying to reuse the unique collection number from CollectionItem, which queries from `nftListByCollection`, SpotflightTable queries from `collectionIssuerList`. Is there a simple way to sync this up?

You could try to open main branch on another window and compare the files in `components/spotlight`
Currently, I see that we miss Volume data on main-nuxt

2021-12-14 18:08 UTC, lohba commented
@roiLeo Sorry, I'm a bit confused. I'm not seeing unique collectors on the main branch. The only difference I see related to volume which I don't think is related.

2021-12-15 07:32 UTC, roiLeo commented
@lohba I got confused with `uniqueCollectors`  function in "series-insight" which is not the same.

Could you try to add Volume Column too?

2021-12-15 17:01 UTC, lohba commented
Added Volume column in spotlight 

![Screen Shot 2021-12-15 at 11 58 35 AM](https://user-images.githubusercontent.com/55772762/146231054-9dab8c1d-ebf4-4690-8976-f110c608893a.png)

2021-12-16 19:55 UTC, yangwao commented
Is this good to go? @lohba @roiLeo ?

2021-12-16 19:57 UTC, yangwao commented
@lohba let's change unique to ∃! then and unique collectors to ∃! collectors plus add there tooltip like it's on the score column with explanation unique and unique collectors :)

2021-12-17 01:52 UTC, lohba commented
Ok, will do - what is the definition of "Unique"?

2021-12-17 20:29 UTC, yangwao commented
> @yangwao Ok, will do - what is the difference between unique and unique collectors?

Oh good point, it's unique NFTs of an artist so thinking what should be better terminology here, maybe unique items would be best if no one will come something better 
It's counted by metadata which is might be bit skewed when I'm thinking as simple mint introduced other way around hmm

2021-12-20 09:03 UTC, roiLeo requested changes

2021-12-20 09:03 UTC, roiLeo commented on langDir/en.json
> +    "uniqueCollectors": "Unique Collectors"
```suggestion
    "uniqueCollectors": "∃! collectors"
```

2021-12-20 09:03 UTC, roiLeo commented on components/spotlight/utils.ts
> +  console.log("volume " + volume)
```suggestion
```

2021-12-20 21:52 UTC, lohba commented
unique items and unique collectors tooltip label 

![Screen Shot 2021-12-20 at 4 50 41 PM](https://user-images.githubusercontent.com/55772762/146837396-6cbedf4b-7bb2-4a59-a620-0d32dbdd9473.png)

2021-12-21 09:01 UTC, roiLeo approved these changes
lgtm, remove trailing space before merge

2021-12-24 01:57 UTC, lohba commented
@yangwao

2021-12-25 09:54 UTC, yangwao commented
I've sent a bit more as you put more effort here and we reward extra effort ;)

Perfect, I’ve sent the payout https://kusama.subscan.io/extrinsic/0xcf5c51a07c8fe686e6a6ffbb8da8b5489b7a3abb30e93e4183d797a5e7a029ea

Let’s grab another issue and get rewarded! 
https://github.com/kodadot/nft-gallery/issues/

2021-12-25 09:54 UTC, merged