Fix: Invalid component name
kodadot/nft-gallery pull request #1547
Opened 2021-12-16 14:07 UTC by codiini

**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇  _ Do a quick check before the merge. 

### PR type
- [ x ] Bugfix
- [ ] Feature
- [ ] Refactoring

### Before submitting Pull Request, please make sure:
- [ x ] My contribution builds **clean without any errors or warnings**
- [ x ] I've merged recent default branch -- **main** and I've no conflicts
- [ x ] I've tried respect high code quality standards
- [ x ] I've didn't break any original functionality
- [ ] I've posted screenshot of demonstrated change in this PR

### Optional
- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything works
- [ ] I found edge cases

### What's new?
- [ x ] PR closes #1533 
- [ x ] Fix Invalid component name issue

### Had issue bounty label ?
- [ ] Fill up your KSM address: [Payout](https://kodadot.xyz/transfer/?target=<My_Kusama_Address>)

### Community participation
- [ x ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot
- [ ] My fix has changed **something** on UI, a screenshot for others, is best to understand changes.

2021-12-16 14:20 UTC, vikiival requested changes
there is 6 other pages to process:

```bash
➜  nft-gallery git:(main-nuxt) ✗ find .  -regex ".*/_id.vue"         
./pages/rmrk/collection/_id.vue
./pages/rmrk/gallery/_id.vue
./pages/rmrk/u/_id.vue
./pages/rmrk/pack/_id.vue
./pages/rmrk/detail/_id.vue
./pages/index.vue
```

2021-12-16 14:58 UTC, vikiival reviewed
Can you commit the suggestions? 🥺

2021-12-16 14:58 UTC, vikiival commented on pages/rmrk/gallery/index.vue
> +import {Component, Vue } from 'nuxt-property-decorator'
```suggestion
import { Component, Vue } from 'nuxt-property-decorator'
```

2021-12-16 14:58 UTC, vikiival commented on pages/rmrk/gallery/index.vue
> +@Component({ name: 'GalleryPage' })
```suggestion

@Component({ name: 'GalleryPage' })
```

2021-12-16 14:59 UTC, roiLeo commented on pages/rmrk/gallery/index.vue
> +import {Component, Vue } from 'nuxt-property-decorator'
UwU

2021-12-16 16:26 UTC, codiini commented
@vikiival Done!

2021-12-17 08:56 UTC, vikiival approved these changes
LGTM

2021-12-17 09:14 UTC, yangwao commented
Let’s grab another issue and get rewarded! 
https://github.com/kodadot/nft-gallery/issues/

2021-12-17 09:14 UTC, merged