Fix text selection in collection description
kodadot/nft-gallery pull request #1621
Opened 2021-12-27 19:48 UTC by MubarakSULAYMAN

**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇  _ Do a quick check before the merge. 

### PR type
- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### Before submitting Pull Request, please make sure:
- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted screenshot of demonstrated change in this PR

### Optional
- [ ] I've tested it at </rmrk/collection/32888663bc9f50ee0e-6X3X9>
- [x] I've tested PR on mobile and everything works
- [ ] I found edge cases

### What's new?
- [x] PR closes #<1473>
- [x] Fix text selection in collection description

### Had issue bounty label ?
- [ ] Fill up your KSM address: [Payout](https://kodadot.xyz/transfer/?target=<My_Kusama_Address>)

### Community participation
- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot
[x] My fix has changed **something** on UI, a screenshot for others, is best to understand changes.
- Image showing text selection in collection description section
<img width="1440" alt="Image showing text selection in collection description section" src="https://user-images.githubusercontent.com/31209490/147502219-01f8e059-e867-4324-a3d5-bdde0dfd28ed.png" title="Image showing text selection in collection description section">

2021-12-27 20:10 UTC, vikiival requested changes
May Also thinking to wrap `VueMarkdown` to `SelectableMarkdown`

2021-12-27 20:10 UTC, vikiival commented on components/rmrk/Gallery/CollectionItem.vue
> +.description {
```suggestion
.is-selectable {
```

2021-12-27 20:10 UTC, vikiival commented on components/rmrk/Gallery/CollectionItem.vue
> +          <VueMarkdown :source="description" class="description" />
```suggestion
          <VueMarkdown :source="description" class="is-selectable" />
```

2021-12-27 20:10 UTC, vikiival commented on components/rmrk/Gallery/CollectionItem.vue
> +@import '@/styles/variables';
you do not use any variables here

2021-12-28 07:22 UTC, MubarakSULAYMAN commented on components/rmrk/Gallery/CollectionItem.vue
> +@import '@/styles/variables';
No, I removed it already.

2021-12-28 14:03 UTC, roiLeo requested changes
> May Also thinking to wrap `VueMarkdown` to `SelectableMarkdown`

Why? VueMarkdown component works well, text is selectable in GalleryItem component. 
Something wrong with CollapseWrapper component, see css rule:
```css
user-select: none;
```
could be fixed by changing to:
```css
user-select: text;
```

2021-12-28 14:07 UTC, MubarakSULAYMAN commented
@roiLeo, it seems @vikiival wants a [reusable component](https://github.com/MubarakSULAYMAN/nft-gallery/blob/patch-1/components/shared/SelectableMarkdown.vue) in case of possible future usages.

2021-12-28 22:07 UTC, roiLeo commented
I feel this `SelectableMarkdown` wrapper is not needed as `VueMarkdown` text is already selectable by default.
IMO, fix should be on `CollapseWrapper` component.
@vikiival What do you think?

2021-12-28 22:21 UTC, vikiival commented
Agree then. I though that vue markdown is not selectable

2021-12-29 11:25 UTC, MubarakSULAYMAN commented
@vikiival and @roiLeo, this broken check is not in my implementation. Kindly review.

2021-12-29 11:47 UTC, roiLeo commented on components/shared/collapse/CollapseWrapper.vue
> +      :class="[isSelectable ? 'is-selectable' : 'is-unselectable']"
```suggestion
      :class="{ 'is-unselectable': !isSelectable }"
```

2021-12-29 11:47 UTC, roiLeo commented on components/shared/collapse/CollapseWrapper.vue
> +</style>
```suggestion
```
I don't think this is needed

2021-12-29 11:47 UTC, roiLeo commented on components/shared/collapse/CollapseWrapper.vue
> +  @Prop({ type: Boolean, default: false }) isSelectable!: Boolean
```suggestion
  @Prop({ type: Boolean, default: false }) isSelectable!: boolean
```

2021-12-29 11:48 UTC, roiLeo commented on components/rmrk/Gallery/CollectionItem.vue
> +          :isSelectable="true"
```suggestion
          isSelectable
```

2021-12-29 13:24 UTC, roiLeo approved these changes
lgtm

2021-12-30 09:51 UTC, yangwao commented
@MubarakSULAYMAN let's update your PR to include KSM address

2021-12-30 13:55 UTC, MubarakSULAYMAN commented
@yangwao, can you give more details?

2021-12-30 22:40 UTC, yangwao commented
> @yangwao, can you give more details?

https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address

2022-01-04 13:19 UTC, yangwao commented
Perfect, I’ve sent the payout https://kusama.subscan.io/extrinsic/0x0795276eff93f1095da6313e0ae4778e353e78c9a8a94d0016a85f34fb2c3ffa

Let’s grab another issue and get rewarded! 
https://github.com/kodadot/nft-gallery/issues/

2022-01-04 13:19 UTC, merged