Initial e2e tests setup for https://github.com/kodadot/nft-gallery/issues/1503
kodadot/nft-gallery pull request #2102
Opened 2022-01-29 03:39 UTC by rchovatiya88

**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Do a quick check before the merge.

### PR type

- [ ] Bugfix
- [x ] Feature
- [ ] Refactoring

### What's new?

- [ ] PR closes #<issue_number>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [ ] My contribution builds **clean without any errors or warnings**
- [ ] I've merged recent default branch -- **main** and I've no conflicts
- [ ] I've tried respect high code quality standards
- [ ] I've didn't break any original functionality
- [ ] I've posted screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases

### Had issue bounty label ?

- [ ] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=<My_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address>)

### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix 
![Untitled_ Jan 28, 2022 10_05 PM (1)](https://user-images.githubusercontent.com/16197756/151645985-d874f31c-ed33-4790-8dbd-d3648184031d.gif)
has changed **something** on UI, a screenshot is best to understand changes for others.

2022-01-29 06:21 UTC, kkukelka requested changes
lots of things to improve 🌮

2022-01-29 06:21 UTC, kkukelka commented on cypress/integration/e2e/search.spec.js
> +    cy.wait(2000)
please don't use wait and instead try to watch for the response of initial graphql call via [cy.intercept](https://docs.cypress.io/api/commands/intercept)

2022-01-29 06:21 UTC, kkukelka commented on cypress/integration/e2e/smokeTests.spec.js
> +    cy.wait(2000)
here as well

2022-01-29 06:21 UTC, kkukelka commented on cypress/integration/e2e/search.spec.js
> +    cy.get('.input').type('generative', { force: true })
`.input` is a very generice selector. please query the element via [data-cy](https://docs.cypress.io/guides/references/best-practices#How-It-Works)

2022-01-29 06:21 UTC, kkukelka commented on cypress/integration/e2e/search.spec.js
> +    cy.get('.input').type('{enter}')
`.input` is a very generice selector. please query the element via [data-cy](https://docs.cypress.io/guides/references/best-practices#How-It-Works)

2022-01-29 06:21 UTC, kkukelka commented on cypress/integration/e2e/search.spec.js
> +    cy.get('.section').click({ force: true })
`.section` is a very generice selector. please query the element via [data-cy](https://docs.cypress.io/guides/references/best-practices#How-It-Works)

2022-01-29 06:21 UTC, kkukelka commented on cypress/integration/e2e/smokeTests.spec.js
> +    cy.get('.input').type('generative', { force: true })
same as above

2022-01-29 06:21 UTC, kkukelka commented on cypress/integration/e2e/smokeTests.spec.js
> +    cy.get('.input').type('{enter}')
same as above

2022-01-29 06:21 UTC, kkukelka commented on cypress/integration/e2e/smokeTests.spec.js
> +    cy.get('.section').click({ force: true })
same as above

2022-01-29 07:39 UTC, rchovatiya88 commented
Thanks!

This was first commit to make sure cypress is part of repo. So was jus example test 
 
You are correct and understood will def use data-cy or add selectors going forward 

Wait usage I argue to a point. 
I will need ur help in setting cy.intercept for graphql-- still a noob 

For now adding it and will create more tests accordingly 🥪

2022-01-29 08:43 UTC, kkukelka commented
> Thanks!
> 
> This was first commit to make sure cypress is part of repo. So was jus example test
> 
> You are correct and understood will def use data-cy or add selectors going forward
> 
> Wait usage I argue to a point. I will need ur help in setting cy.intercept for graphql-- still a noob
> 
> For now adding it and will create more tests accordingly 🥪

I mean, if everyone is ok with it @yangwao @roiLeo we can merge it like that as a base setup and I will do a more precise rework in a separate PR.

2022-01-30 13:57 UTC, yangwao commented
> I mean, if everyone is ok with it @yangwao @roiLeo we can merge it like that as a base setup and I will do a more precise rework in a separate PR.

Yup, let's move it to `/tests/cypress/` as I guess we will have `/tests/` directory already present :)

Let's merge it this stage then, no need to wait for me on this

2022-01-30 14:03 UTC, kkukelka approved these changes

2022-01-31 18:48 UTC, rchovatiya88 commented
@kkukelka if you would like to merge it, i'll create new branch with fixes n better tests :)

2022-01-31 18:54 UTC, kkukelka commented
> @kkukelka if you would like to merge it, i'll create new branch with fixes n better tests :)

I'm not allowed to merge sadly 😛 and this branch still has merge conflicts in `yarn.lock`

2022-02-01 13:23 UTC, yangwao commented
> @kkukelka if you would like to merge it, i'll create new branch with fixes n better tests :)

Let's merge this and you can make PR on top of this later :)

Like need to move `/cypress` directory under `/tests` and we are good to go :)

2022-02-04 11:51 UTC, merged