#2208 Show only first row from description at collection
kodadot/nft-gallery pull request #2225
Opened 2022-02-04 14:10 UTC by prachi00

**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [ ] PR closes #2208
- [ ] 

### Before submitting Pull Request, please make sure:

- [ ] My contribution builds **clean without any errors or warnings**
- [ ] I've merged recent default branch -- **main** and I've no conflicts
- [ ] I've tried to respect high code quality standards
- [ ] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [ ] Fill up your KSM address: 
[Payout](https://beta.kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)

### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
<img width="1437" alt="Screenshot 2022-02-04 at 7 39 00 PM" src="https://user-images.githubusercontent.com/39299315/152542934-2c21a9bd-736b-4a0f-8eea-cd3f8547bb0f.png">

2022-02-04 14:19 UTC, roiLeo requested changes
Instead of adding a new wrapper I would just change have the `maxCharsWrapper` attribute which was originally designed for this purpose.
You could try to pass it as a @Prop()

2022-02-04 14:22 UTC, prachi00 commented
> maxCharsWrapper

@roiLeo **maxCharsWrapper** decided whether or not to show the wrapper, the actual height is decided through this css only
<img width="520" alt="Screenshot 2022-02-04 at 7 52 42 PM" src="https://user-images.githubusercontent.com/39299315/152545072-e1d41268-0f36-49a8-b602-bc409b0f735a.png">

2022-02-04 14:26 UTC, roiLeo commented
> @roiLeo **maxCharsWrapper** decided whether or not to show the wrapper, the actual height is decided through this css only

Oh yes, you're right. I forgot about that one...

2022-02-04 14:33 UTC, roiLeo commented
So with your solution there will be no difference between row 2 and 3, wouldn't it be better to pass the height of the wrapper as a Prop?

2022-02-04 14:36 UTC, prachi00 commented
> So with your solution there will be no difference between row 2 and 3, wouldn't it be better to pass the height of the wrapper as a Prop?

you mean pass a whole class that has max height set?

2022-02-04 14:43 UTC, roiLeo commented
> > So with your solution there will be no difference between row 2 and 3, wouldn't it be better to pass the height of the wrapper as a Prop?
> 
> you mean pass a whole class that has max height set?

I would see something like this:
- pass height as prop number
- keep default: 130
- then in wrapper `:style="{max-height: $theprop + 'px'}"`

2022-02-04 14:48 UTC, prachi00 commented
> > > So with your solution there will be no difference between row 2 and 3, wouldn't it be better to pass the height of the wrapper as a Prop?
> > 
> > 
> > you mean pass a whole class that has max height set?
> 
> I would see something like this:
> 
> * pass height as prop number
> * keep default: 130
> * then in wrapper `:style="{max-height: $theprop + 'px'}"`

yes sounds better, made the required changes

2022-02-04 15:11 UTC, roiLeo commented on components/shared/collapse/DescriptionWrapper.vue
> +      }">
```suggestion
    <div
      :style="[activeWrapper && hasWrapper ? { maxHeight: `${rowHeight}px` } : null]"
      :class="{'description-wrapper': activeWrapper && hasWrapper }">
```

2022-02-04 15:13 UTC, roiLeo approved these changes

2022-02-05 09:39 UTC, yangwao commented
nice! 

![image](https://user-images.githubusercontent.com/5887929/152636551-e1ff93ba-74ed-4837-9b8c-c2908f613019.png)

pay 100 usd

2022-02-05 09:42 UTC, yangwao commented
pay 100 usd

2022-02-05 09:48 UTC, yangwao commented
pay 100 usd

2022-02-05 09:52 UTC, yangwao commented
okay lol unrelated to this issue

![image](https://user-images.githubusercontent.com/5887929/152636871-39efc567-d922-4462-bc5c-31b6b1479706.png)

2022-02-05 09:57 UTC, yangwao commented
pay 100 usd

2022-02-05 09:57 UTC, yangwao commented
😍 Perfect, I’ve sent the payout 
💵 $100 @ 184.32 USD/KSM ~ 0.543 $KSM
🧗 [EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU](https://kusama.subscan.io/account/EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)
🔗 [0xce2edc6b1e2e6ab55425228086b377043dc12620c98d572771ed2c5eaa6f7dfb](https://kusama.subscan.io/extrinsic/0xce2edc6b1e2e6ab55425228086b377043dc12620c98d572771ed2c5eaa6f7dfb)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

2022-02-05 09:57 UTC, merged