fix: hover aero style
kodadot/nft-gallery pull request #2510
Opened 2022-03-06 05:20 UTC by Jarsen136

**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #2498
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [x] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [x] I've tested PR on mobile and everything seems works
- [] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
<img width="861" alt="image" src="https://user-images.githubusercontent.com/31397967/156910308-3009ad8f-13fb-4997-b0eb-dc9052f1d7f4.png">

<img width="340" alt="image" src="https://user-images.githubusercontent.com/31397967/156910310-8646c5b7-d907-458d-8e8d-2a7698e0e287.png">

<img width="596" alt="image" src="https://user-images.githubusercontent.com/31397967/156910313-fa380bc3-ba9e-4b12-8c8a-72a91afd5961.png">

2022-03-06 09:34 UTC, vikiival commented
<img width="460" alt="Screenshot 2022-03-06 at 10 32 52" src="https://user-images.githubusercontent.com/22471030/156917434-59a86a1a-fc4c-4e18-95cf-29f90b5b4b8a.png">

This is nice

2022-03-06 09:42 UTC, vikiival requested changes
two things:
1. this (`rgba(12, 12, 12, 0.7);`) should become as variable
2. Wallet modal does not fit in the style

Check for example loader: it has sharp corners and and pink borders.
On the other hand wallet modal has rounded corners


Please make sure that WalletModal follows the same UI style

2022-03-06 09:42 UTC, vikiival commented on components/common/WalletModal.vue
> +    background: rgba(12, 12, 12, 0.7);
Please make it as `.scss` variable

2022-03-06 09:57 UTC, Jarsen136 commented on components/common/WalletModal.vue
> +    background: rgba(12, 12, 12, 0.7);
ok

2022-03-06 10:29 UTC, Jarsen136 commented
> two things:
> 
> 1. this (`rgba(12, 12, 12, 0.7);`) should become as variable
> 2. Wallet modal does not fit in the style
> 
> Check for example loader: it has sharp corners and and pink borders. On the other hand wallet modal has rounded corners
> 
> Please make sure that WalletModal follows the same UI style
Thanks!
1. I had changed it.
2. Wallet modal do fit the style and u can look at my screenshot.

2022-03-07 08:46 UTC, vikiival commented
> 2. Wallet modal do fit the style and u can look at my screenshot.

Sir, I do not want to be rude but do these squares look same to you?
![untitled-3](https://user-images.githubusercontent.com/22471030/156997690-b45d88bd-e7ba-4e34-a1c2-284040cc53ee.png)

2022-03-07 10:58 UTC, Jarsen136 commented
> Referen

Oh, I see. sorry, just give me some time to fix it.

2022-03-07 11:05 UTC, vikiival commented
> Oh, I see. sorry, just give me some time to fix it.

No problemo 👍

2022-03-07 17:23 UTC, vikiival commented
Why
<img width="448" alt="Screenshot 2022-03-07 at 18 23 29" src="https://user-images.githubusercontent.com/22471030/157085531-ba56f931-711a-4528-8bf6-71281a563630.png">

2022-03-07 17:54 UTC, vikiival commented
This look super hot
two last things:
**1. Can we have these buttons with sharp edges and dark background?
<img width="439" alt="Screenshot 2022-03-07 at 18 24 22" src="https://user-images.githubusercontent.com/22471030/157085787-84e30b00-dc28-4ee8-9d62-a748789581ec.png">

Moreover can we have modal with sharp edges? 
<img width="445" alt="Screenshot 2022-03-07 at 18 24 50" src="https://user-images.githubusercontent.com/22471030/157085817-0bc4934f-b385-4021-8845-a8ad6466cded.png">


That's all, can't wait to merge it 💘

2022-03-07 17:55 UTC, vikiival requested changes
last CSS magick

2022-03-08 00:32 UTC, Jarsen136 commented
> 

how about this?  @vikiival 
<img width="423" alt="image" src="https://user-images.githubusercontent.com/31397967/157141750-ff8e1a8b-2700-4ade-9b9c-3eda073858de.png">
<img width="445" alt="image" src="https://user-images.githubusercontent.com/31397967/157141803-8463013b-059b-4622-9c91-c674fef2656f.png">

2022-03-08 17:26 UTC, vikiival commented
Yup, awesome work mate!

2022-03-08 17:27 UTC, vikiival approved these changes
🎨 code looks LGTM

2022-03-10 09:52 UTC, yangwao commented
pay 100 usd

2022-03-10 09:52 UTC, yangwao commented
😍 Perfect, I’ve sent the payout 
💵 $100 @ 128.66 USD/KSM ~ 0.777 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0xfa908aa03010327f298be0cb88f207d8e4537897d6b4d968a228f197ac6d1c70](https://kusama.subscan.io/extrinsic/0xfa908aa03010327f298be0cb88f207d8e4537897d6b4d968a228f197ac6d1c70)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

2022-03-10 09:52 UTC, merged