fix: remove price sort in collection
kodadot/nft-gallery pull request #2636
Opened 2022-03-22 13:27 UTC by Jarsen136

**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #2632
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [x] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

<img width="1092" alt="image" src="https://user-images.githubusercontent.com/31397967/159492363-5e6131fc-ddb7-4670-af5a-556b88074bbf.png">

2022-03-22 14:09 UTC, vikiival requested changes
Code looks oki
I would just rename `defaultSort` to something more meaningful

2022-03-22 14:34 UTC, Jarsen136 commented on components/rmrk/Collection/List/CollectionList.vue
> +      :defaultSort="collectionSortConfigure">
done!

2022-03-22 14:40 UTC, vikiival approved these changes

2022-03-22 15:02 UTC, yangwao commented
pay 100 usd

2022-03-22 15:02 UTC, merged

2022-03-23 14:13 UTC, yangwao commented
updated #2641