fallback nft meta is null
kodadot/nft-gallery pull request #2749
Opened 2022-04-02 12:39 UTC by Jarsen136

**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #2747
- [ ] <brief_description_of_what_I've_added>

the error is caused by the incrooect nft meta, which is is null.
<img width="717" alt="image" src="https://user-images.githubusercontent.com/31397967/161383573-cda270ae-fe3b-471a-8594-7494b8082d1c.png">

the nft: /rmrk/gallery/10869444-c6017764e7a1d03b5e-MOOSENFT-MAGGIE_MOOSE_29-0000000000000029

expected nft meta is an object with id and image.
<img width="701" alt="image" src="https://user-images.githubusercontent.com/31397967/161383614-97c9d4c2-9cad-4cc9-8da9-2ad8bddad95c.png">

Would be cool if we can filter the events in  squid.

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

2022-04-05 09:31 UTC, vikiival requested changes
> fallback

fallback is when you ask one girl for a date but in case you ask another girl just in case the first one would say no

The implementation filters out nfts which does not have meta (which is super strange :)) But the correct fallback is to take `metadata` field and fetch it on the client

2022-04-05 12:32 UTC, Jarsen136 commented
I mock the empty meta and then it displays all the images and works well without any error.

2022-04-08 08:18 UTC, vikiival requested changes
Extend `queries/rmrk/subsquid/lastNftListByEvent.graphql`

1. extend query with metadata

```graphql
query lastNftListByEvent($limit: Int!, $event: Interaction!, $and: [EventWhereInput!]) {
  events(
    limit: $limit
    where: { interaction_eq: $event, AND: $and, nft: {burned_eq: false} }
    orderBy: timestamp_DESC
  ) {
    meta
    timestamp
    nft {
      id
      name
      issuer
      currentOwner
      metadata
      meta {
        id
        image
      }
    }
  }
}

```
2. fetch metadata
3. update cache
4. fetch image via cloudflare image

2022-04-08 21:05 UTC, yangwao commented
lol probably accidentally found that moment lol and seems working

![image](https://user-images.githubusercontent.com/5887929/162530165-0e32a4ae-a6f0-4d6c-96a2-68b9ebba64db.png)

![image](https://user-images.githubusercontent.com/5887929/162530220-d5e434aa-ad92-472d-b252-cd0ea9b9be31.png)

2022-04-09 00:47 UTC, Jarsen136 commented
> lol probably accidentally found that moment lol and seems working
> 
> ![image](https://user-images.githubusercontent.com/5887929/162530165-0e32a4ae-a6f0-4d6c-96a2-68b9ebba64db.png)
> 
> ![image](https://user-images.githubusercontent.com/5887929/162530220-d5e434aa-ad92-472d-b252-cd0ea9b9be31.png)

 yup, you caught the same error again 😄

2022-04-09 04:31 UTC, Jarsen136 commented
> Extend `queries/rmrk/subsquid/lastNftListByEvent.graphql`
> 
> 1. extend query with metadata
> 
> ```graphql
> query lastNftListByEvent($limit: Int!, $event: Interaction!, $and: [EventWhereInput!]) {
>   events(
>     limit: $limit
>     where: { interaction_eq: $event, AND: $and, nft: {burned_eq: false} }
>     orderBy: timestamp_DESC
>   ) {
>     meta
>     timestamp
>     nft {
>       id
>       name
>       issuer
>       currentOwner
>       metadata
>       meta {
>         id
>         image
>       }
>     }
>   }
> }
> ```
> 
> 2. fetch metadata
> 3. update cache
> 4. fetch image via cloudflare image

Now it works for me but I'm not sure if the code meets your expectation. 
The image url has been fetched appropriately.
And I still don't know should we try to fetch `meta.image` if 'meta' is null. 😕

2022-04-09 09:42 UTC, vikiival requested changes

2022-04-09 09:42 UTC, vikiival commented on components/rmrk/Gallery/LatestSales.vue
> +
avoid mutating data

2022-04-09 09:42 UTC, vikiival commented on components/rmrk/Gallery/NewestList.vue
> +    for (const event of data.events) {
DRY

2022-04-09 10:24 UTC, Jarsen136 commented on components/rmrk/Gallery/LatestSales.vue
> +
okay

2022-04-09 10:26 UTC, vikiival reviewed
👀

2022-04-12 09:45 UTC, vikiival approved these changes
YOLO MODE ON.

2022-04-12 09:46 UTC, vikiival commented
pay 99 usd

2022-04-12 09:46 UTC, yangwao commented
😍 Perfect, I’ve sent the payout 
💵 $99 @ 156.21 USD/KSM ~ 0.634 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0x9584cedba95dc54eb2dec18c4c0e176c21feb8182f809f9a566acc51f0d67bb2](https://kusama.subscan.io/extrinsic/0x9584cedba95dc54eb2dec18c4c0e176c21feb8182f809f9a566acc51f0d67bb2)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

2022-04-12 09:46 UTC, merged