fix: Refresh history component after actions user has made
kodadot/nft-gallery pull request #2813
Opened 2022-04-10 08:17 UTC by Jarsen136

**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #1290
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

2022-04-12 05:57 UTC, kkukelka requested changes

2022-04-12 05:57 UTC, kkukelka commented on components/rmrk/Gallery/AvailableActions.vue
> +            this.$emit('change', this.selectedAction)
hmm why do we need to emit `this.selectedAction` here though? you are not doing anything with the function parameter in parent

2022-04-12 19:18 UTC, kkukelka approved these changes
all good now

2022-04-12 19:18 UTC, kkukelka commented
pay 50

2022-04-12 19:19 UTC, yangwao commented
😍 Perfect, I’ve sent the payout 
💵 $50 @ 150.25 USD/KSM ~ 0.333 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0xdb90821b5a7a8c7c3d09ad2f8ff8f00038c20cf84f273f5161ca1d509695494e](https://kusama.subscan.io/extrinsic/0xdb90821b5a7a8c7c3d09ad2f8ff8f00038c20cf84f273f5161ca1d509695494e)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

2022-04-12 19:19 UTC, kkukelka commented
cant merge yet . hmmhmhm. i assume because of edge release destroying build process

2022-04-13 10:04 UTC, yangwao commented
Seems broken by a recent merge? 

@Jarsen136 


https://user-images.githubusercontent.com/5887929/163154827-d453c4ac-da0a-4556-82c9-11e1f27ca7f3.mov

2022-04-13 10:08 UTC, Jarsen136 commented
> Seems broken by a recent merge? 
> 
> 
> 
> @Jarsen136 
> 
> 
> https://user-images.githubusercontent.com/5887929/163154827-d453c4ac-da0a-4556-82c9-11e1f27ca7f3.mov
> 
> 
> 
> 
I will check it later.
This pr has not merged into main branch

2022-04-13 12:05 UTC, Jarsen136 commented
Seems that I could not reproduce this bug.
Could you pls have a try again ❓   @yangwao

2022-04-13 14:18 UTC, yangwao commented
yeah can't reproduce either lol, even tried cache and it happened so.. dunno! 
just someone could test this i.e. like buying something for example :)

2022-04-13 17:12 UTC, yangwao commented
tried here and haven't refreshed history :| 

but I clicked off loader.. maybe that's why?

![image](https://user-images.githubusercontent.com/5887929/163234144-40a32660-c2bc-436b-911d-c9cd8fff832c.png)

2022-04-13 17:17 UTC, yangwao commented
yeah it did not work even a second time. :| 
How did you test it? 

![image](https://user-images.githubusercontent.com/5887929/163235061-d42eec2d-9cc4-4858-bed2-92af51a19265.png)

2022-04-13 17:18 UTC, yangwao commented
oh I was doing buy! so let me try LIST

2022-04-14 00:28 UTC, Jarsen136 commented
Sorry, It may be because the data fetched immediately has not been updated after the `list、buy` action is submitted.  : )

I make history events to polling to ensure that events can update when they change.

2022-04-14 01:04 UTC, Jarsen136 commented
WFM just now, by doing buy action and list action on-chain.

2022-04-14 12:34 UTC, yangwao commented
wfm 

I just noticed that on collection tile switcher (large display small display) went missing?
![image](https://user-images.githubusercontent.com/5887929/163391352-3bfb53f5-4dd6-4b93-b1ad-63ce129f371a.png)


https://kodadot.xyz/rmrk/collection/d6e71489d50f818c09-TEWIN
![image](https://user-images.githubusercontent.com/5887929/163391302-1c27d256-9681-473f-8fdb-911dfb1ecc88.png)

2022-04-14 12:34 UTC, yangwao commented
pay 100 usd

2022-04-14 12:34 UTC, merged