wording change on FAQ page
kodadot/nft-gallery pull request #2889
Opened 2022-04-20 05:00 UTC by thea-exe

**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [ ] Feature
- [ X] Refactoring

### What's new?

- [ ] PR closes #<issue_number>
- [ X] <I went to [FAQ](https://kodadot.xyz/rmrk/faq) and changed "Frequently Asked Question" to "Frequently Asked Questions and changed "NO TIME FOR READING?" to "Don't have time to read?">

### Before submitting Pull Request, please make sure:

- [ ] My contribution builds **clean without any errors or warnings**
- [ ] I've merged recent default branch -- **main** and I've no conflicts
- [ ] I've tried to respect high code quality standards
- [ ] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [ ] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=<My_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address>)

### Community participation

- [X] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [X] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
<img width="1510" alt="Screen Shot 2022-04-20 at 1 00 02 AM" src="https://user-images.githubusercontent.com/65369742/164153762-6faa30da-acc7-4a71-a287-aed1a7411b7e.png">

2022-04-20 06:35 UTC, roiLeo requested changes
- check `langDir/en.json` file and you will find the translation (line :77)
- it would be nice to add the last two lines in translation file

2022-04-20 06:44 UTC, thea-exe commented
@roiLeo I understand that it is in the en.json folder, however, "Frequently Asked Question" isn't proper, especially referring to multiple questions.

I'll make sure to update the en.json file with the last two lines though

2022-04-20 07:21 UTC, roiLeo reviewed
this change will break other "Frequently Asked Question" translation
here's what i would do:
- change json file like this:
```json
"faq": {
    "title": "Frequently Asked Questions",
    "box_heading1": "Don't have time to read?",
    "box_heading2": "No problem, check out",
```
- create in all other json files the `faq.title` & copy "Frequently Asked Question" line into this one
- then change in `components/common/FrequentlyAsked.vue` {{ $t('faq.title') }}

2022-04-20 07:28 UTC, thea-exe commented
Oh! I understand now— let me implement this in the morning :)

On Wed, Apr 20, 2022 at 3:21 AM roiLeo ***@***.***> wrote:

> ***@***.**** commented on this pull request.
>
> this change will break other "Frequently Asked Question" translation
> here's what i would do:
>
>    - change json file like this:
>
> "faq": {
>     "title": "Frequently Asked Questions",
>     "box_heading1": "Don't have time to read?",
>     "box_heading2": "No problem, check out",
>
>
>    - create in all other json files the faq.title & copy "Frequently
>    Asked Question" line into this one
>    - then change in components/common/FrequentlyAsked.vue {{
>    $t('faq.title') }}
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/kodadot/nft-gallery/pull/2889#pullrequestreview-946698112>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APSXNDRHS2LJEDAWIXUPOS3VF6V7LANCNFSM5T2ZYSYA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-04-21 02:58 UTC, thea-exe commented
I decided to add 
`"box_heading1": "",
    "box_heading2": "",`
just in case people wanted to translate those lines!

2022-04-21 06:35 UTC, roiLeo reviewed
- remove empty `box_heading` this will automatically fallback to english
- add new translation to page

2022-04-21 06:35 UTC, roiLeo commented on components/common/FrequentlyAsked.vue
> +      Don't have time to read? <br />
```suggestion
      {{ $t('faq.box_heading1') }} <br />
```

2022-04-21 06:35 UTC, roiLeo commented on components/common/FrequentlyAsked.vue
> +      No problem, check out <br />
```suggestion
      {{ $t('faq.box_heading2') }}<br />
```

2022-04-21 06:35 UTC, roiLeo commented on langDir/bn.json
> +    "box_heading2": "",
```suggestion
```

2022-04-21 06:35 UTC, roiLeo commented on langDir/de.json
> +    "box_heading2": "",
```suggestion
```

2022-04-21 06:35 UTC, roiLeo commented on langDir/es.json
> +    "box_heading2": "",
```suggestion
```

2022-04-21 06:35 UTC, roiLeo commented on langDir/fr.json
> +    "box_heading2": "",
```suggestion
```

2022-04-21 06:35 UTC, roiLeo commented on langDir/hi.json
> +    "box_heading2": "",
```suggestion
```

2022-04-21 06:35 UTC, roiLeo commented on langDir/id.json
> +    "box_heading2": "",
```suggestion
```

2022-04-21 06:35 UTC, roiLeo commented on langDir/it.json
> +    "box_heading2": "",
```suggestion
```

2022-04-21 06:35 UTC, roiLeo commented on langDir/jp.json
> +    "box_heading2": "",
```suggestion
```

2022-04-21 06:35 UTC, roiLeo commented on langDir/ko.json
> +    "box_heading2": "",
```suggestion
```

2022-04-21 06:35 UTC, roiLeo commented on langDir/nl.json
> +    "box_heading2": "",
```suggestion
```

2022-04-21 06:35 UTC, roiLeo commented on langDir/pl.json
> +    "box_heading2": "",
```suggestion
```

2022-04-21 06:35 UTC, roiLeo commented on langDir/pt.json
> +    "box_heading2": "",
```suggestion
```

2022-04-21 06:35 UTC, roiLeo commented on langDir/sk.json
> +    "box_heading2": "",
```suggestion
```

2022-04-21 06:35 UTC, roiLeo commented on langDir/tu.json
> +    "box_heading2": "",
```suggestion
```

2022-04-21 06:35 UTC, roiLeo commented on langDir/ua.json
> +    "box_heading2": "",
```suggestion
```

2022-04-21 06:35 UTC, roiLeo commented on langDir/ur.json
> +    "box_heading2": "",
```suggestion
```

2022-04-21 06:35 UTC, roiLeo commented on langDir/vt.json
> +    "box_heading2": "",
```suggestion
```

2022-04-21 06:57 UTC, roiLeo approved these changes

2022-04-21 07:13 UTC, merged