feat: implement new generic error page
kodadot/nft-gallery pull request #2967
Opened 2022-05-06 18:13 UTC by kkukelka

**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check

### PR type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

<img width="1378" alt="Screenshot 2022-05-06 at 20 04 49" src="https://user-images.githubusercontent.com/17953978/167194735-c47cccc1-a98c-4365-bbe0-c4eb5bfb3149.png">
<img width="1312" alt="Screenshot 2022-05-06 at 20 05 15" src="https://user-images.githubusercontent.com/17953978/167194770-5116c3d6-d3d9-420a-b4fa-c2dd6d015ab1.png">
eck before the contribution.

### What's new?

- [x] PR closes #2958
- [x] get rid of old error handling mess and implement correct implementation for nuxt;
this will get even more beneficial once we utilize asyncData for fetching

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://kodadot.xyz/transfer/?target=EqdyzrzVmeHwMdMwvPeCMnNdbuQDbD3YrjY93xq9Ln3jUGW)

### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

2022-05-08 15:39 UTC, vikiival commented
Really nice :)

few thingies: 

Can we have a cat for each http err ? (e.g based on the status code ?)

also it is possible to have this? 

> query params like ?type=collection&reason=error.notfound&id=dasdas

It was written in the issue. 

The point is when user got a error screen it can tell which collection / nft caused that err :)

2022-05-08 15:39 UTC, vikiival reviewed
.

2022-05-08 17:54 UTC, kkukelka commented
> Really nice :)
> 
> few thingies:
> 
> Can we have a cat for each http err ? (e.g based on the status code ?)
> 
> also it is possible to have this?
> 
> > query params like ?type=collection&reason=error.notfound&id=dasdas
> 
> It was written in the issue.
> 
> The point is when user got a error screen it can tell which collection / nft caused that err :)

yes, NuxtError interface allows to propagate the path where the error occured.

<img width="750" alt="Screenshot 2022-05-08 at 19 53 28" src="https://user-images.githubusercontent.com/17953978/167308973-d4dbdfb6-7248-47f0-afbd-29f0275d829e.png">

just implemented it for collections

so wherever we want to explicitly track the URL that caused failure we just need to implement 
```javascript
  return this.$nuxt.error({
        statusCode: 404,
        message: 'Oops! Collection Not Found',
        path: this.$route.path,
      })
```

2022-05-09 09:44 UTC, vikiival requested changes

2022-05-09 09:44 UTC, vikiival commented on layouts/error.vue
> +      src="https://http.cat/500"
```suggestion
      src="`https://http.cat/${error.statusCode}`"
```

2022-05-09 16:40 UTC, kkukelka commented
@vikiival very neat, didnt know it had a picture for every status code 😎

2022-05-10 09:34 UTC, vikiival commented on layouts/error.vue
> +      src="`https://http.cat/${error.statusCode}`"
```suggestion
      :src="`https://http.cat/${error.statusCode}`"
```

2022-05-10 09:35 UTC, vikiival approved these changes
Looks oki

2022-05-10 11:22 UTC, vikiival commented
pay 75 usd

2022-05-10 11:22 UTC, merged

2022-05-10 11:22 UTC, yangwao commented
😍 Perfect, I’ve sent the payout 
💵 $75 @ 100.41 USD/KSM ~ 0.747 $KSM
🧗 [EqdyzrzVmeHwMdMwvPeCMnNdbuQDbD3YrjY93xq9Ln3jUGW](https://kusama.subscan.io/account/EqdyzrzVmeHwMdMwvPeCMnNdbuQDbD3YrjY93xq9Ln3jUGW)
🔗 [0x6a7a26810a8682b6fc7cf00c2b01266c1111c613da88e2673f700815fee19322](https://kusama.subscan.io/extrinsic/0x6a7a26810a8682b6fc7cf00c2b01266c1111c613da88e2673f700815fee19322)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)