user profil with history events
kodadot/nft-gallery pull request #2973
Opened 2022-05-07 18:22 UTC by MSghais

**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [V] Feature
- [ ] Refactoring

### What's new?

- [V] PR closes #2550
- [V] Create a history event of one User Profil Detail selected. Use the history component with pagination.

### Before submitting Pull Request, please make sure:

- [V] My contribution builds **clean without any errors or warnings**
- [V ] I've merged recent default branch -- **main** and I've no conflicts
- [V] I've tried to respect high code quality standards
- [V] I've didn't break any original functionality
- [V] I've posted a screenshot of demonstrated change in this PR

### Optional

- [] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [V] I've tested PR on mobile and everything seems works
- [V] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [V] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=EFuhGSJpetTgoZ2dfWxwirxADBWgAzWmVfJmTCauZuPxz6z

### Community participation

- [V] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [V] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

![Koda_work](https://user-images.githubusercontent.com/59928086/167266956-d7eb3984-b89a-4c70-b8e4-c48bba708b28.png)

2022-05-08 10:02 UTC, yangwao commented
Hey, when I clicked on own profile I should land me on my KSM ss58 address

`/rmrk/u/CuHWHNcBt3ASMVSJmcJyiBWGxxiWLyjYoYbGjfhL4ovoeSd`
but at your PR I've landed on
`https://deploy-preview-2973--koda-nuxt.netlify.app/rmrk/u/5CPfqy2jZX2EghfzY4oG5kpW8NgUhgAZ6Rhqt5PjrGbS4YdM`

on beta.kodadot.xyz works fine, that's `main` branch.

![image](https://user-images.githubusercontent.com/5887929/167291228-68870537-2f33-4ad0-8cc2-f8784a1a58d6.png)

2022-05-08 10:04 UTC, yangwao commented
I highly sense there will be a lot of events and probably writing rubick resolver would be needed. 
wyt @vikiival 👀

2022-05-08 10:07 UTC, yangwao commented
Okay, let me know when it's ready for testing :D 

![image](https://user-images.githubusercontent.com/5887929/167291409-24f8821d-f7a4-4ce9-8b0e-83efa785505c.png)

2022-05-08 15:23 UTC, vikiival commented
> [V]


pls use `[X]`

2022-05-08 15:25 UTC, vikiival commented
> I highly sense there will be a lot of events and probably writing rubick resolver would be needed.

Yup the query is not optimal

2022-05-08 15:57 UTC, MSghais commented
Hi @yangwao | KodaDot#1123 thanks ! 

1. For the substrate address format, I didn't change the address format for the profil.
Personaly,  when I click on the profil, I go directly on KSM ss58 address profil, and the history load very fastly.

I look sometimes with have some issues with the KSM format address on Profil.

We have already see this issues created for the KSM format address, it's the PR #2857. 
I take a look on it probably after please.

2022-05-09 10:41 UTC, vikiival commented
killian can u please check it? 🥺 🙏

2022-05-09 12:43 UTC, yangwao commented
Seems can't test on my end 
https://deploy-preview-2973--koda-nuxt.netlify.app/rmrk/u/CuHWHNcBt3ASMVSJmcJyiBWGxxiWLyjYoYbGjfhL4ovoeSd?tab=history

```
{"errors":[{"message":"Field \"limit\" is not defined by type \"EventWhereInput\".","extensions":{"code":"GRAPHQL_VALIDATION_FAILED","exception":{"stacktrace":["GraphQLError: Field \"limit\" is not defined by type \"EventWhereInput\".","    at ObjectField (/squid/node_modules/graphql/validation/rules/ValuesOfCorrectTypeRule.js:73:29)","    at Object.enter (/squid/node_modules/graphql/language/visitor.js:323:29)","    at Object.enter (/squid/node_modules/graphql/utilities/TypeInfo.js:370:25)","    at visit (/squid/node_modules/graphql/language/visitor.js:243:26)","    at validate (/squid/node_modules/graphql/validation/validate.js:69:24)","    at validate (/squid/node_modules/apollo-server-core/dist/requestPipeline.js:186:39)","    at processGraphQLRequest (/squid/node_modules/apollo-server-core/dist/requestPipeline.js:98:34)","    at runMicrotasks (<anonymous>)","    at processTicksAndRejections (node:internal/process/task_queues:96:5)","    at async processHTTPRequest (/squid/node_modules/apollo-server-core/dist/runHttpQuery.js:186:30)"]}}},{"message":"Field \"offset\" is not defined by type \"EventWhereInput\".","extensions":{"code":"GRAPHQL_VALIDATION_FAILED","exception":{"stacktrace":["GraphQLError: Field \"offset\" is not defined by type \"EventWhereInput\".","    at ObjectField (/squid/node_modules/graphql/validation/rules/ValuesOfCorrectTypeRule.js:73:29)","    at Object.enter (/squid/node_modules/graphql/language/visitor.js:323:29)","    at Object.enter (/squid/node_modules/graphql/utilities/TypeInfo.js:370:25)","    at visit (/squid/node_modules/graphql/language/visitor.js:243:26)","    at validate (/squid/node_modules/graphql/validation/validate.js:69:24)","    at validate (/squid/node_modules/apollo-server-core/dist/requestPipeline.js:186:39)","    at processGraphQLRequest (/squid/node_modules/apollo-server-core/dist/requestPipeline.js:98:34)","    at runMicrotasks (<anonymous>)","    at processTicksAndRejections (node:internal/process/task_queues:96:5)","    at async processHTTPRequest (/squid/node_modules/apollo-server-core/dist/runHttpQuery.js:186:30)"]}}}]}
```

![image](https://user-images.githubusercontent.com/5887929/167412109-27d3c5a6-1b87-45bb-81ea-8d5d229d8349.png)

2022-05-09 17:44 UTC, kkukelka commented
> killian can u please check it? 🥺 🙏

interesting... it actually loads quite fast for me initially and then on like page 8 i get same state like wao

<img width="1340" alt="Screenshot 2022-05-09 at 19 43 50" src="https://user-images.githubusercontent.com/17953978/167467140-894e05c1-6b05-4bc0-ba41-b02328a2f96d.png">

2022-05-09 17:45 UTC, kkukelka commented
<img width="593" alt="Screenshot 2022-05-09 at 19 45 06" src="https://user-images.githubusercontent.com/17953978/167467221-1735b1aa-aeec-46fd-84a8-26248f505990.png">

2022-05-09 17:48 UTC, kkukelka requested changes

2022-05-09 17:48 UTC, kkukelka commented on components/rmrk/Profile/ProfileDetail.vue
> +            // offset: (this.currentValue - 1) * this.first,
maybe remove this if not used?

2022-05-09 17:48 UTC, kkukelka commented on components/rmrk/Profile/ProfileDetail.vue
> +        // TODO : default value of HISTORY for BUY
is this still being done in the current PR?

2022-05-09 17:48 UTC, kkukelka commented on components/rmrk/Profile/ProfileDetail.vue
> +    // this.fetchCollectionEvents()
remove if not needed

2022-05-10 17:08 UTC, MSghais reviewed
Unused vars deleted @kkukelka, and the code self reviewed too. Let me know please !

2022-05-10 17:31 UTC, kkukelka commented
> Unused vars deleted @kkukelka, and the code self reviewed too. Let me know please !

sweet, could you take a look though at the weird bug me and wao experienced when clicking through pagination?

2022-05-10 20:05 UTC, MSghais commented
> > Unused vars deleted @kkukelka, and the code self reviewed too. Let me know please !
> 
> sweet, could you take a look though at the weird bug me and wao experienced when clicking through pagination?

Hum I take a look on it, but I don't have the bug me too on this page.
Certainly a problem of pagination on History component, I don't touch the pagination on this PR.
@kkukelka 

![image](https://user-images.githubusercontent.com/59928086/167712411-2c6881da-e814-400e-b73a-1f0ef9d05917.png)

2022-05-11 06:26 UTC, kkukelka commented
> > > Unused vars deleted @kkukelka, and the code self reviewed too. Let me know please !
> > 
> > 
> > sweet, could you take a look though at the weird bug me and wao experienced when clicking through pagination?
> 
> Hum I take a look on it, but I don't have the bug me too on this page. Certainly a problem of pagination on History component, I don't touch the pagination on this PR. @kkukelka
> 
> ![image](https://user-images.githubusercontent.com/59928086/167712411-2c6881da-e814-400e-b73a-1f0ef9d05917.png)

alright then. created a followup ticket if someone wants to dig deeper here
https://github.com/kodadot/nft-gallery/issues/2997

2022-05-11 06:26 UTC, kkukelka approved these changes

2022-05-11 10:59 UTC, yangwao commented
Technically it's on 9 page, so when you are going from 8 -> 9 , 10 -> 11, 21 -> 22
yet it stuck render on prev page.

https://deploy-preview-2973--koda-nuxt.netlify.app/rmrk/u/CuHWHNcBt3ASMVSJmcJyiBWGxxiWLyjYoYbGjfhL4ovoeSd?tab=history&page=9

2022-05-11 11:00 UTC, yangwao commented
pay 100 usd

2022-05-11 11:01 UTC, merged

2022-05-11 11:01 UTC, yangwao commented
pay 100 usd

2022-05-11 11:01 UTC, yangwao commented
😍 Perfect, I’ve sent the payout 
💵 $100 @ 88.18 USD/KSM ~ 1.134 $KSM
🧗 [EFuhGSJpetTgoZ2dfWxwirxADBWgAzWmVfJmTCauZuPxz6z](https://kusama.subscan.io/account/EFuhGSJpetTgoZ2dfWxwirxADBWgAzWmVfJmTCauZuPxz6z)
🔗 [0x836c9cbb8de40763c2528b99ae83a653faa59b0a7ff009854d7a150a8231d436](https://kusama.subscan.io/extrinsic/0x836c9cbb8de40763c2528b99ae83a653faa59b0a7ff009854d7a150a8231d436)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)