:zap: instant link to create on-chain identity from profile
kodadot/nft-gallery pull request #2987
Opened 2022-05-09 11:25 UTC by vikiival

**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [x] Feature
- [ ] Refactoring

### What's new?

- [ ] PR closes #<issue_number>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

2022-05-10 17:23 UTC, kkukelka requested changes

2022-05-10 17:23 UTC, kkukelka commented on components/rmrk/Profile/ProfileDetail.vue
> +        <nuxt-link v-if="!displayName && isMyProfile" :to="`/identity`">
should work without templateString, no?
```suggestion
        <nuxt-link v-if="!displayName && isMyProfile" to="/identity">
```

2022-05-11 13:05 UTC, kkukelka approved these changes

2022-05-11 15:10 UTC, kkukelka commented
@vikiival still 2 conflicting files here. 
apart from that: do i pay a bounty here since its not connected to any issue?

2022-05-12 09:02 UTC, vikiival commented
> do i pay a bounty here since its not connected to any issue 

nope :) 

+ I am out of the payout scheme ;D

2022-05-12 13:57 UTC, merged