Stats profil activitiy
kodadot/nft-gallery pull request #2995
Opened 2022-05-10 16:53 UTC by MSghais

**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [X] Feature
- [ ] Refactoring

### What's new?

- [X] PR closes #1238
- [X] Description : 
1. the total amount $KSM of sold items and number of sold items
2. how much the collector spent in lifetime in $KSM and the total count of items
3. current holdings of the profile, total in $KSM and total items

Good overview of profil

### Before submitting Pull Request, please make sure:

- [X] My contribution builds **clean without any errors or warnings**
- [] I've merged recent default branch -- **main** and I've no conflicts :
 conflict in package json and pnpm with new version deps.
Error.vue deleted otherwise nothing else.
I accept the Incoming changes when merge main into my branch.

- [X] I've tried to respect high code quality standards
- [X] I've didn't break any original functionality
- [X] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [X] I've tested PR on mobile and everything seems works
- [X] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [X] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=5DkJ2x6SCHsXw9jarxhv3mVx1cuGsWBLK7pZNnvdRmguDuyy

### Community participation

- [X] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [X] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

![image](https://user-images.githubusercontent.com/59928086/167680405-c9d1aa08-d544-41cf-986d-751b3bbae868.png)

![image](https://user-images.githubusercontent.com/59928086/167681725-16d66297-f06b-4f2c-9b4c-b19556a19b3e.png)

2022-05-12 11:08 UTC, petersopko requested changes
hey, thank you for your contribution :) can you please check if you see what I'm seeing here: 
https://deploy-preview-2995--koda-nuxt.netlify.app/rmrk/u/DSVZroU95KSVZKVr2pFdKfJkQtkgU5U1rkrBdeVnktHWmM4?tab=sold&page=1


Looks like a mismatch to me? 

![image](https://user-images.githubusercontent.com/73316633/168057578-1ac5cf9d-dbdd-4134-9a12-55414dc73872.png)

2022-05-12 18:40 UTC, MSghais reviewed
All is self reviewed @petersopko.

For the mismatch you mentionned, I think this is related on other issue : https://github.com/kodadot/nft-gallery/issues/898.

2022-05-13 00:47 UTC, MSghais reviewed
All is self reviewed @petersopko.

For the mismatch you mentionned, I think this is related on other issue : https://github.com/kodadot/nft-gallery/issues/898.

2022-05-13 07:57 UTC, petersopko commented
> All is self reviewed @petersopko.
> 
> For the mismatch you mentionned, I think this is related on other issue : #898.

It may be also related to the other issue, but if you look at the issue specs in #1238 (which you're trying to close by this PR), it seems that the task isn't done? 
Another example : https://deploy-preview-2995--koda-nuxt.netlify.app/rmrk/u/Gek2uCr3kWqdt8eSaYzE1GxNn3b1RB1FYgzyQuKhhJ63X7r?tab=sold
![image](https://user-images.githubusercontent.com/73316633/168237596-9f442945-d553-4c39-8fa1-b7ff67d3c7f0.png)

2022-05-13 12:31 UTC, MSghais commented
> > All is self reviewed @petersopko.
> > For the mismatch you mentionned, I think this is related on other issue : #898.
> 
> It may be also related to the other issue, but if you look at the issue specs in #1238 (which you're trying to close by this PR), it seems that the task isn't done? Another example : https://deploy-preview-2995--koda-nuxt.netlify.app/rmrk/u/Gek2uCr3kWqdt8eSaYzE1GxNn3b1RB1FYgzyQuKhhJ63X7r?tab=sold ![image](https://user-images.githubusercontent.com/73316633/168237596-9f442945-d553-4c39-8fa1-b7ff67d3c7f0.png)

Yes pretty strange issue. I receive the data after the query, but the check after apollo query see the data like a null values in this profil. 
Is just only on this profil, otherwise all profil work pretty well for me.

![Bug - data](https://user-images.githubusercontent.com/59928086/168283326-2ce1d0c6-2c2c-4880-a40b-1821a86394bc.png)

2022-05-13 12:50 UTC, petersopko commented
@vikiival could you please take a look, not sure what to do with this one

2022-05-16 05:14 UTC, vikiival requested changes

2022-05-16 05:14 UTC, vikiival commented on components/rmrk/Profile/ProfilActivity.vue
> +      .reduce((acc, cur) => acc + cur, BigInt(0))
DRY

2022-05-16 05:14 UTC, vikiival commented on components/rmrk/Profile/ProfileDetail.vue
> +        <ProfilActivity :id="id" />
```suggestion
        <ProfileActivity :id="id" />
```

2022-05-16 05:14 UTC, vikiival commented on langDir/en.json
> +  "profil_stats": {
```suggestion
  "profileStats": {
```

2022-05-16 05:14 UTC, vikiival commented on queries/rmrk/subsquid/profilStatsById.graphql
> +query profilStatsById($id: String!, $search_listed: [EventWhereInput!],  $search_collected: [NFTEntityWhereInput!],  $search_sold: [EventWhereInput!], $search_invested:[EventWhereInput!]) {
```suggestion
query profileStatsById($id: String!, $search_listed: [EventWhereInput!],  $search_collected: [NFTEntityWhereInput!],  $search_sold: [EventWhereInput!], $search_invested:[EventWhereInput!]) {
```

2022-05-16 05:14 UTC, vikiival commented on queries/rmrk/subsquid/profilStatsById.graphql
> +  listed : events(where: {  caller_eq: $id , AND: $search_listed },  ) {
pleease use fragments sir

2022-05-16 05:14 UTC, vikiival commented on components/rmrk/Profile/ProfilActivity.vue
> +        search_listed: {
Please follow code guidline :)

2022-05-16 19:44 UTC, MSghais reviewed
Feedback done, clean & refacto

2022-05-17 07:43 UTC, vikiival commented on queries/rmrk/subsquid/profileStatsById.graphql
> +  }
wtf

2022-05-17 07:46 UTC, vikiival requested changes

2022-05-17 07:46 UTC, vikiival commented on queries/rmrk/subsquid/profileStatsById.graphql
> +  }
You query events to get nfts to get events?

2022-05-17 07:46 UTC, vikiival commented on components/rmrk/Profile/ProfileActivity.vue
> +      </div>
Make a component

2022-05-17 07:46 UTC, vikiival commented on components/rmrk/Profile/ProfileActivity.vue
> +        },
This should be handled by query

2022-05-17 07:46 UTC, vikiival commented on components/rmrk/Profile/ProfileActivity.vue
> +    })
what does this do?

2022-05-18 08:48 UTC, vikiival requested changes

2022-05-18 08:48 UTC, vikiival commented on components/rmrk/Profile/ProfileActivity.vue
> +    })
rubick 006 contains current owner for the event

2022-05-18 08:48 UTC, vikiival commented on components/shared/ScrollTopButton.vue
> +<template>
?

2022-05-18 08:48 UTC, vikiival commented on components/shared/format/StatsColumn.vue
> +</template>
```suggestion
<template>
      <div class="level-item has-text-centered">
        <div>
          <p class="title">
             <slot name="title"></slot>
          </p>
          <p class="heading">
             <slot name="heading"></slot>
          </p>
        </div>
      </div>
</template>
```

2022-05-18 08:48 UTC, vikiival commented
```graphql
query profileStatsByAccount($id: String!) {
  listed: nftEntitiesConnection(where: {currentOwner_eq: $id, price_gt: "0"}, orderBy: name_ASC) {
    totalCount
  }
  collected: nftEntitiesConnection(where: {currentOwner_eq: $id, issuer_not_eq: $id, events_some: {interaction_eq: BUY}}, orderBy: name_ASC) {
    totalCount
    edges {
      node {
        events(where: {interaction_eq: BUY, caller_eq: $id}) {
          meta
        }
      }
    }
  }
  sold: nftEntitiesConnection(where: {currentOwner_not_eq: $id, issuer_eq: $id, events_some: {interaction_eq: BUY}}, orderBy: name_ASC) {
    totalCount
    edges {
      node {
        events(where: {interaction_eq: BUY, currentOwner_eq: $id}) {
          meta
        }
      }
    }
  }
  obtained: nftEntitiesConnection(where: {currentOwner_eq: $id, issuer_not_eq: $id}, orderBy: name_ASC) {
    totalCount
  }
}

```

let me know if you are missing any value

2022-05-20 19:43 UTC, MSghais reviewed
Add new subquery more fast

2022-05-20 19:44 UTC, MSghais reviewed
Done

2022-05-21 10:31 UTC, vikiival requested changes
Some stuff

2022-05-21 10:31 UTC, vikiival commented on components/shared/format/StatsColumn.vue
> +    round: function roundOffNumber(value, limit) {
move to utils

2022-05-21 10:31 UTC, vikiival commented on components/shared/format/StatsColumn.vue
> +    checkInvalidBalance: checkInvalidBalanceFilter,
```suggestion
import { checkInvalidBalanceFilter as checkInvalidBalance } from '@/utils/formatBalance'

@Component({
  filters: {
    checkInvalidBalance,
```

2022-05-21 10:31 UTC, vikiival commented on components/shared/format/StatsColumn.vue
> +    | undefined
```suggestion
  @Prop({ type: String, default: 'profileStats.totalBuys' }) readonly label: string
```

2022-05-21 10:31 UTC, vikiival commented on components/shared/format/StatsColumn.vue
> +  private readonly coinId: string = 'kusama'
What's this?

2022-05-21 10:31 UTC, vikiival commented on components/shared/format/StatsColumn.vue
> +  }
Use chainMixin

2022-05-21 12:32 UTC, MSghais reviewed
Stuff done

2022-05-23 13:53 UTC, vikiival commented
<img width="847" alt="Screenshot 2022-05-23 at 15 52 30" src="https://user-images.githubusercontent.com/22471030/169834871-be5e69bd-0510-46e7-9ddc-80ec1530433d.png">

2022-05-24 06:30 UTC, vikiival commented
@petersopko can u pls check? 🥺

2022-05-24 08:38 UTC, petersopko commented
> hey, thank you for your contribution :) can you please check if you see what I'm seeing here: https://deploy-preview-2995--koda-nuxt.netlify.app/rmrk/u/DSVZroU95KSVZKVr2pFdKfJkQtkgU5U1rkrBdeVnktHWmM4?tab=sold&page=1
> 
> Looks like a mismatch to me?
> 
> ![image](https://user-images.githubusercontent.com/73316633/168057578-1ac5cf9d-dbdd-4134-9a12-55414dc73872.png)

@MSghais your added feature still doesn't work. Mismatch between sold in the tabs vs. your added feature is still there.
Currently, the totalCount of sold items should be 300. Please check again. This is what the added query shows:
![image](https://user-images.githubusercontent.com/73316633/169988172-d9ae97b1-dcde-4e4c-9e73-2f98a96afcc9.png)

2022-05-26 07:52 UTC, petersopko commented
> > > hey, thank you for your contribution :) can you please check if you see what I'm seeing here: https://deploy-preview-2995--koda-nuxt.netlify.app/rmrk/u/DSVZroU95KSVZKVr2pFdKfJkQtkgU5U1rkrBdeVnktHWmM4?tab=sold&page=1
> > > Looks like a mismatch to me?
> > > ![image](https://user-images.githubusercontent.com/73316633/168057578-1ac5cf9d-dbdd-4134-9a12-55414dc73872.png)
> > 
> > 
> > @MSghais your added feature still doesn't work. Mismatch between sold in the tabs vs. your added feature is still there. Currently, the totalCount of sold items should be 300. Please check again. This is what the added query shows: ![image](https://user-images.githubusercontent.com/73316633/169988172-d9ae97b1-dcde-4e4c-9e73-2f98a96afcc9.png)
> 
> @petersopko for the mismatch you mentionned, this is related on other issue : #898.
> 
> In my query, I take all Sold event. In the Tab you compare, we have also the Gifted event related on the issue above, that's why the difference is here for the totalCount.


Okay, but the number still isn't correct? Another example, when I check the query below at rubick https://app.gc.subsquid.io/beta/rubick/006/graphql with account `CgGKH1dsPgJkQ3caFsnDtMUWUqVJKEpRt1ekM5RDW4UrYhP` I see total count of 66. I think the query is correct. When I check the profile stats there, I see the number 50. This has nothing to do with the tab. Also, sometimes this happens: 
![image](https://user-images.githubusercontent.com/73316633/170443233-9e67fc27-98fe-458a-890e-4d3224c36871.png) 

Data just doesn't load?


```graphql 
sold: nftEntitiesConnection(
    where: {
      currentOwner_not_eq: $id
      issuer_eq: $id
      name_not_eq: "%Kanaria%"
      burned_not_eq: true
      events_some: { interaction_eq: BUY }
    }
    orderBy: name_ASC
  ) {
    totalCount
    edges {
      node {
        events(
          where: {
            interaction_eq: BUY
            currentOwner_eq: $id
            caller_not_eq: $id
          }
        ) {
          meta
        }
      }
    }
  }
```

2022-05-26 12:21 UTC, petersopko approved these changes
lgtm

2022-05-26 12:25 UTC, vikiival approved these changes

2022-05-26 12:26 UTC, petersopko commented
pay 200 usd

2022-05-26 12:26 UTC, merged

2022-05-26 12:26 UTC, yangwao commented
😍 Perfect, I’ve sent the payout 
💵 $200 @ 71.09 USD/KSM ~ 2.813 $KSM
🧗 [5DkJ2x6SCHsXw9jarxhv3mVx1cuGsWBLK7pZNnvdRmguDuyy](https://kusama.subscan.io/account/5DkJ2x6SCHsXw9jarxhv3mVx1cuGsWBLK7pZNnvdRmguDuyy)
🔗 [0x01896f925b34b70a39f9bd3fc5761414a01034bc99d2d31323a1ddb62612e8ee](https://kusama.subscan.io/extrinsic/0x01896f925b34b70a39f9bd3fc5761414a01034bc99d2d31323a1ddb62612e8ee)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)