issue 2222 passion gallery
kodadot/nft-gallery pull request #3023
Opened 2022-05-15 13:50 UTC by KngZhi

- feat: passion feed request
- feat: passion feed switch ui

**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #2222
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [x] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer?target=DaWoVNNhBTdqJ5iPN3UcaLeamkPpJeGWdrs8LhvX9TQbadc)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

2022-05-15 14:22 UTC, KngZhi commented
You can check the effect when Rubick was deployed.

2022-05-15 15:02 UTC, yangwao commented
> You can check the effect when Rubick was deployed.

let's a link which PR on Rubick?

2022-05-15 15:08 UTC, KngZhi commented
> > You can check the effect when Rubick was deployed.
> 
> let's a link which PR on Rubick?

updated

2022-05-17 08:02 UTC, petersopko commented
@KngZhi actually, I've found out what the problem is with the linked issue which you've been unassigned from (#2647) 
If you want to close multiple issues with one PR you need to use different format, i.e. `closes #1, closes #2`, otherwise bot doesn't know it's closing issue and not just linked issue 🚀  https://stackoverflow.com/questions/60027222/github-how-can-i-close-the-two-issues-with-commit-message

2022-05-17 08:19 UTC, KngZhi commented
> @KngZhi actually, I've found out what the problem is with the linked issue which you've been unassigned from (#2647) If you want to close multiple issues with one PR you need to use different format, i.e. `closes #1, closes #2`, otherwise bot doesn't know it's closing issue and not just linked issue 🚀 https://stackoverflow.com/questions/60027222/github-how-can-i-close-the-two-issues-with-commit-message

@petersopko Oh, I see, learned, didn't realize the `closes` matters. Many thanks for the info and link!

2022-05-26 17:33 UTC, kkukelka requested changes
sorry, i totally forgot about this PR. would these changes be ok with you?

2022-05-26 17:33 UTC, kkukelka commented on components/landing/Landing.vue
> +    return passionFeed.map((item) => item.id)
```suggestion
    return passionFeed?.map(item => item.id) || []
```

2022-05-26 17:33 UTC, kkukelka commented on components/rmrk/Gallery/Gallery.vue
> +    this.passionList = passionFeed.map((x) => x.id)
```suggestion
    this.passionList = passionFeed?.map(x => x.id) || []
```

2022-05-26 17:33 UTC, kkukelka commented on components/rmrk/Gallery/NewestList.vue
> +  @Prop({ required: false, default: [''] }) passionList: string[]
```suggestion
  @Prop({ type: Array, default: () => []}) passionList?: string[]
```

2022-05-26 17:33 UTC, kkukelka commented on components/rmrk/Gallery/LatestSales.vue
> +  @Prop({ required: false, default: [''] }) passionList: string[]
```suggestion
  @Prop({ type: Array, default: () => [] }) passionList?: string[]
```

2022-05-27 06:57 UTC, KngZhi commented
> sorry, i totally forgot about this PR. would these changes be ok with you?

No worries :). Those are definitely good changes, thanks for the review, Kilian.

2022-05-27 08:49 UTC, kkukelka approved these changes
all good now!

2022-05-27 08:49 UTC, merged

2022-05-27 08:50 UTC, kkukelka commented
pay 350

2022-05-27 08:50 UTC, yangwao commented
😍 Perfect, I’ve sent the payout 
💵 $350 @ 67.34 USD/KSM ~ 5.198 $KSM
🧗 [DaWoVNNhBTdqJ5iPN3UcaLeamkPpJeGWdrs8LhvX9TQbadc](https://kusama.subscan.io/account/DaWoVNNhBTdqJ5iPN3UcaLeamkPpJeGWdrs8LhvX9TQbadc)
🔗 [0x3d58d29f06f6f569332069bbc94bb798382e4f43df30856c4c4f181d7e7a8e9d](https://kusama.subscan.io/extrinsic/0x3d58d29f06f6f569332069bbc94bb798382e4f43df30856c4c4f181d7e7a8e9d)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)