Feat(#1165) : Collector whale stats
kodadot/nft-gallery pull request #3049
Opened 2022-05-22 15:32 UTC by MSghais

**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [X] Feature
- [ ] Refactoring

### What's new?

- [X] PR closes #1165
- [X] Collector whale view with column: 
all bought items
hold items
average
volume
scoring holding
30 buy history

### Before submitting Pull Request, please make sure:

- [X] My contribution builds **clean without any errors or warnings**
- [X] I've merged recent default branch -- **main** and I've no conflicts
- [X] I've tried to respect high code quality standards
- [X] I've didn't break any original functionality
- [X] I've posted a screenshot of demonstrated change in this PR

### Optional

- [X] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [X] I've tested PR on mobile and everything seems works
- [X] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [X] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=EFuhGSJpetTgoZ2dfWxwirxADBWgAzWmVfJmTCauZuPxz6z

### Community participation

- [X] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [X] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

2022-05-23 05:47 UTC, kkukelka commented
deployment preview somehow gets stuck on graphql request for me 🤔 
![Screenshot 2022-05-23 at 07 46 40](https://user-images.githubusercontent.com/17953978/169751711-f9640c57-de48-4174-880a-646418aa3838.png)

2022-05-28 05:14 UTC, kkukelka requested changes

2022-05-28 05:14 UTC, kkukelka commented on components/collector/SpotlightDetail.vue
> +  watchAccount(val: string, oldVal: string) {
```suggestion
  onAccountChange(val: string, oldVal: string) {
```

2022-05-28 05:14 UTC, kkukelka commented on components/collector/utils.ts
> +export const nftFn = (a: any): Row => {
is there no parameter type for this? ☹️

2022-05-28 05:14 UTC, kkukelka commented on components/collector/utils.ts
> +    collectors: 0, // a.nfts.nodes.reduce(uniqueCollectorFn, new Set()),
i assume there's no property in the response to calculate this right? can we do a TODO comment here then to solve this in the future

2022-05-28 05:14 UTC, kkukelka commented on components/collector/utils.ts
> +  const unique = a.nfts.nodes.reduce(uniqueFn, new Set()).size
```suggestion
  const sold = a.nfts.nodes?.reduce(soldFn, 0)
  const unique = a.nfts.nodes?.reduce(uniqueFn, new Set())?.size
```

2022-05-28 05:14 UTC, kkukelka commented on components/collector/utils.ts
> +  const buyEvents = a.nfts.nodes.map(onlyEvents).map(pairListBuyEvent).flat()
```suggestion
  const uniqueCollectors = a.nfts.nodes?.reduce(
    uniqueCollectorFn,
    new Set()
  )?.size
  const buyEvents = a.nfts.nodes?.map(onlyEvents)?.map(pairListBuyEvent)?.flat()
```

2022-05-28 05:14 UTC, kkukelka commented on pages/collector-whale.vue
> +      url: '/spotlight',
```suggestion
      url: '/collector-whale',
```

2022-05-28 05:14 UTC, kkukelka commented on pages/collector-whale.vue
> +      description: 'Discover new collectors based on ranking',
```suggestion
      description: 'Discover the most active collector whales on RMRK.',
```

2022-05-28 05:14 UTC, kkukelka commented on pages/collector-whale.vue
> +    const title = 'NFT Collector rank'
```suggestion
    const title = 'Collector Whales on RMRK'
```

2022-05-28 05:14 UTC, kkukelka commented on langDir/en.json
> +    "subtitle": "Featuring the most active collectors whale on RMRK.",
```suggestion
    "subtitle": "Featuring the most active collector whales on RMRK.",
```

2022-05-28 17:43 UTC, kkukelka approved these changes
lgtm, waiting for new rubick deploy

2022-05-29 13:05 UTC, MSghais commented
Hi @vikiival, this PR is tested. 
Could you merge the collector_whale on the rubick server, and deployed it please, for this PR please ?

2022-05-31 09:23 UTC, vikiival commented
> Hi @vikiival, this PR is tested.

Lovely to hear waiting for the rubick testing

2022-06-16 10:28 UTC, vikiival requested changes
Does this work? 
you use `rmrk` indexer but queries are for subsquid?

2022-06-16 10:28 UTC, vikiival commented on components/collector/CollectorDetail.vue
> +      client: 'rmrk',
why is `rmrk` here?

2022-06-21 13:28 UTC, vikiival requested changes
why the code has like 400 LOC?

2022-06-21 13:28 UTC, vikiival commented on components/collector/CollectorDetail.vue
> +      client: 'subsquid',
```suggestion
      client: this.client,
```

2022-06-21 13:28 UTC, vikiival commented on components/collector/CollectorDetail.vue
> +import nftSimpleListByAccount from '@/queries/nftSimpleListByAccount.graphql'
pls use correct path

2022-06-21 13:29 UTC, vikiival commented
Pls resolve conflicts, fix the suggestions 

and we can merge

2022-06-21 18:27 UTC, kkukelka commented
> why the code has like 400 LOC?

CollectorTable.vue takes up a chunk of it, which seems valid though

2022-06-23 11:48 UTC, vikiival commented
Marked as unread ✅

2022-06-24 09:40 UTC, petersopko commented
@MSghais any updates on this?

2022-06-24 12:17 UTC, vikiival requested changes

2022-06-24 12:17 UTC, vikiival commented on components/collector/CollectorDetail.vue
> +  }
I doubt that this works, please make it workable for all chains

2022-06-28 13:04 UTC, petersopko commented
@MSghais mate, I'm sorry but we'll have to close this one. We're happy that you're contributing but this particular PR is here for a very long time, without improvement. Some feedback so we can avoid wasting your time in the future:
- if you're not sure about the codebase, I'd suggest picking up smaller issues. There are many issues connected to basilisk which are fairly easy to implement, I expect that after the indexer for moonsama is done, there will be many more.
- if you open up a PR, you should see the end of the task you're solving around the corner
- if you're not sure about the finishing of the task, you can open up a PR with unfinished code and expect help, but in that case, **your communication is required**
- try to keep the communication in the open (comments/reviews). I see that you're sending me DMs about the PRs you're solving, I'm, generally speaking, avoiding replying to those as we're working here as a team and there are multiple people participating :)

At time of closing, deploy has failed some time ago, all the checks are not passing and you're not responding to review comments for ~4 days. Feel free to reopen with new code, or ask the questions you have in the issue you're trying to solve.

2022-06-28 13:04 UTC, closed without merging