fix: remove duplicate item from Newest List
kodadot/nft-gallery pull request #3062
Opened 2022-05-24 00:24 UTC by Jarsen136

**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #3059 
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
before:   
<img width="1418" alt="image" src="https://user-images.githubusercontent.com/31397967/169924613-48964674-b0eb-4359-ad1c-e2ae3856176a.png">

after fix:    
<img width="1477" alt="image" src="https://user-images.githubusercontent.com/31397967/169924585-188e9381-78ba-4b68-85e2-c89560f16900.png">

2022-05-24 06:51 UTC, roiLeo reviewed
IMO it would be better to do something at the query level maybe try to hack with filters

This might introduce edge case where an user LIST more than 10 times and it's going to show only one nft in NewestList

2022-05-24 12:55 UTC, Jarsen136 commented
> IMO it would be better to do something at the query level maybe try to hack with filters
> 
> This might introduce edge case where an user LIST more than 10 times and it's going to show only one nft in NewestList

Yes, but I think the best solution is to make a resolver for LIST event. ref: https://github.com/kodadot/rubick/issues/29 cc @vikiival 

I will try to make it.

2022-05-25 05:36 UTC, Jarsen136 commented
> Yes, but I think the best solution is to make a resolver for LIST event. ref: [kodadot/rubick#29](https://github.com/kodadot/rubick/issues/29) cc @vikiival
> 
> I will try to make it.

ref https://github.com/kodadot/rubick/pull/89

2022-06-13 10:14 UTC, roiLeo reviewed
With https://github.com/kodadot/rubick/pull/89 merged, will you change fix #3059 or do you have to create a new query?

2022-06-13 12:31 UTC, Jarsen136 commented
> With [kodadot/rubick#89](https://github.com/kodadot/rubick/pull/89) merged, does it fix #3059 or do you have to create a new query?

Yes, I need to create a new query to apply the new resolver.

2022-06-18 08:50 UTC, Jarsen136 commented
I just found a bug from the new resolver : )  https://github.com/kodadot/rubick/pull/100

2022-06-19 15:44 UTC, yangwao commented
so it's ready to test/merge? :p

2022-06-19 16:07 UTC, Jarsen136 commented
> so it's ready to test/merge? :p

not yet. I am waiting for its deployment again :)

2022-06-19 16:11 UTC, vikiival commented
> I am waiting for its deployment again :)

deploying

2022-06-20 14:13 UTC, Jarsen136 commented
- [x] remove duplicate item from [Newest List]/[Latest sales]

I found two new bugs : )

- [ ]  inaccurate time about listing

<img width="1120" alt="image" src="https://user-images.githubusercontent.com/31397967/174620415-94edcd4b-b100-468d-a807-06f64f44bbd1.png">

<img width="561" alt="image" src="https://user-images.githubusercontent.com/31397967/174619979-37a33f82-398a-4354-99a6-e7719c6ba5a6.png">

- [ ] nft may be displayed on [Newest List] even if  its listing price equal to 0.

2022-06-20 19:38 UTC, vikiival requested changes
Smol stuff 

+ please do not copy paste stuff 3 times :)

https://en.wikipedia.org/wiki/Don%27t_repeat_yourself

2022-06-20 19:38 UTC, vikiival commented on queries/rmrk/subsquid/lastNftListByEvent.graphql
> +  lastEvent(
```suggestion
  events: lastEvent(
```

2022-06-20 19:38 UTC, vikiival commented on utils/carousel.ts
> +export const convertLastEventToNft = (e: any) => {
lol `any` :)

2022-06-20 19:39 UTC, vikiival commented
> nft may be displayed on [Newest List] even if its listing price equal to 0.

this was already solved couple of PRs ago

2022-06-21 01:28 UTC, Jarsen136 commented
Updated: 
- [x] remove duplicate item from [Newest List]/[Latest sales]

- [x]  inaccurate time to nft listing
https://github.com/kodadot/rubick/pull/101
- [x] nft may be displayed on [Newest List] even if  its listing price equal to 0.

- [ ] support passion feed

2022-06-21 07:14 UTC, roiLeo approved these changes
✅ code lgtm
didn't test yet

2022-06-21 19:36 UTC, prachi00 commented
pay 100 usd

2022-06-21 19:36 UTC, merged

2022-06-21 19:36 UTC, yangwao commented
😍 Perfect, I’ve sent the payout 
💵 $100 @ 55.34 USD/KSM ~ 1.807 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0xe409d5d52188536e415e2a66bcbf54d22271f2d2c6d40050e395bce3ba8dee23](https://kusama.subscan.io/extrinsic/0xe409d5d52188536e415e2a66bcbf54d22271f2d2c6d40050e395bce3ba8dee23)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)