Feat(2882) : Chart collection V2
kodadot/nft-gallery pull request #3064
Opened 2022-05-25 00:29 UTC by MSghais

**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [X] Bugfix
- [X] Feature
- [ ] Refactoring

### What's new?

- [X] PR closes #2882
- [X]
 Change first chart simple for lisibility.
 Add other Graph for specific stats.

### Before submitting Pull Request, please make sure:

- [X] My contribution builds **clean without any errors or warnings**
- [X] I've merged recent default branch -- **main** and I've no conflicts
- [X] I've tried to respect high code quality standards
- [X] I've didn't break any original functionality
- [X] I've posted a screenshot of demonstrated change in this PR

### Optional

- [X] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [X] I've tested PR on mobile and everything seems works
- [] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [X] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=5DkJ2x6SCHsXw9jarxhv3mVx1cuGsWBLK7pZNnvdRmguDuyy

### Community participation

- [X] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [X] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

![image](https://user-images.githubusercontent.com/59928086/170153387-3c8d0f41-22b0-420b-b925-a393c0b88902.png)

2022-05-26 00:49 UTC, prachi00 commented
@vikiival @roiLeo can you please also take a look at this once?

2022-05-31 07:11 UTC, roiLeo reviewed
is it possible to put all data in the same graph? it's not very pretty to have two graphs one under the other

2022-05-31 09:22 UTC, vikiival requested changes
Some minor stuff

2022-05-31 09:22 UTC, vikiival commented on components/rmrk/Gallery/CollectionBarStats.vue
> +  }
I heard that a `ChartMixin` would a be good friend here

2022-06-02 14:43 UTC, MSghais commented
> is it possible to put all data in the same graph? it's not very pretty to have two graphs one under the other

It is possible but not very readable. I tried a lot, but it's much more readable with simple graphs that are easily interpretable.

2022-06-08 19:22 UTC, prachi00 commented
@roiLeo @vikiival can we merge this one yet?

2022-06-11 13:29 UTC, vikiival commented
~ So as I understand correctly the change is that @MSghais added the barchart?

2022-06-20 05:32 UTC, prachi00 commented
@MSghais any update on this one?

2022-06-22 16:57 UTC, prachi00 commented
> > ~ So as I understand correctly the change is that @MSghais added the barchart?
> 
> At the moment, I added the bar graph to represent more clearly two variables. The older graphic is pretty hard to read with 4 stats variables. That is why I divide that. I used all data available in rubick at this moment for the collection chart stats.
> 
> Let me know please

@vikiival

2022-06-23 11:47 UTC, vikiival commented
> Let me know please

I was thinking about this issue for a couple of days and:
- your contribution is really nice
- like the bar chart for the value

but
- this won't close #2882 

finally:
- I've seen a couple of issues in deepsource, make sure they are resolved
- @prachi00 will do a code review and test that 🧪 
- once approved we can payout some bounty and happy to merge

2022-06-24 04:36 UTC, prachi00 commented
@MSghais can you resolve the conversations?

2022-06-26 16:29 UTC, MSghais commented
Hi yes I try to solve the deepsource issues. 

But this rules is unecessary for the context of this PR and this commit, because document needed to checked strictly with non-null values, and also the function return void.  

Thanks for understanding @prachi00 @vikiival

2022-06-28 00:01 UTC, prachi00 approved these changes

2022-07-27 11:03 UTC, petersopko commented
bump, @MSghais any update?

2022-07-29 13:20 UTC, yangwao commented
Closing this as staled PR
Once @MSghais will 
- resolve deepsource issues 
- provide links where I can check and test it

happy to proceed.

2022-07-29 13:20 UTC, closed without merging