#842 WIP : Ability to sort by multiple metrics
kodadot/nft-gallery pull request #3067
Opened 2022-05-26 01:32 UTC by prachi00

**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [ ] PR closes #842
- [ ] 

### Before submitting Pull Request, please make sure:

- [ ] My contribution builds **clean without any errors or warnings**
- [ ] I've merged recent default branch -- **main** and I've no conflicts
- [ ] I've tried to respect high code quality standards
- [ ] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [ ] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=<My_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address>)

### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

2022-05-26 01:39 UTC, prachi00 commented
So I am in still in doubt about the query
because if I sort by `most reacted` and `high to low` at the same time, the result is confusing, not sure how to fix it though. 

Secondly, there is this weird error on console even though I think I did it right , its happening because of having 2 VModels but they have different values so it should be fine right?
Still trying to figure this one out but thought I'd raise the PR just in case someone else has any idea

<img width="633" alt="Screen Shot 2022-05-25 at 6 36 49 PM" src="https://user-images.githubusercontent.com/39299315/170397264-08546621-2a6a-4f17-b15f-d4852dd470f2.png">
 
 
![Screen Shot 2022-05-25 at 6 37 31 PM](https://user-images.githubusercontent.com/39299315/170397334-96d21c19-0c40-45a7-977b-878ddc2d2593.png)

2022-05-26 01:39 UTC, prachi00 commented
> So I am in still in doubt about the query because if I sort by `most reacted` and `high to low` at the same time, the result is confusing, not sure how to fix it though.
> 
> Secondly, there is this weird error on console even though I think I did it right , its happening because of having 2 VModels but they have different values so it should be fine right? Still trying to figure this one out but thought I'd raise the PR just in case someone else has any idea
> 
> <img alt="Screen Shot 2022-05-25 at 6 36 49 PM" width="633" src="https://user-images.githubusercontent.com/39299315/170397264-08546621-2a6a-4f17-b15f-d4852dd470f2.png">
> 
> ![Screen Shot 2022-05-25 at 6 37 31 PM](https://user-images.githubusercontent.com/39299315/170397334-96d21c19-0c40-45a7-977b-878ddc2d2593.png)

CC @vikiival @roiLeo

2022-05-27 05:14 UTC, prachi00 commented
> IMO I would rather use https://buefy.org/documentation/dropdown/#multiple :)

used dropdown component

2022-05-31 09:25 UTC, vikiival reviewed
code looks LGTM
would be nice to test it

2022-05-31 11:58 UTC, roiLeo reviewed
Tested on `/rmrk/explore?page=1&tab=GALLERY&search=&sort=PRICE_DESC&sort=EMOTES_COUNT_DESC&listed=true`

2022-05-31 11:58 UTC, roiLeo commented on components/rmrk/Gallery/Search/SearchSortDropdown.vue
> +        <b-button type="is-primary" icon-right="menu-down"> Sort by </b-button>
Missing translation here + fix icon
```suggestion
        <b-button type="is-primary" icon-right="caret-down"> Sort by </b-button>
```

2022-06-02 06:54 UTC, petersopko requested changes
@prachi00 there was a request to rename most of the filters in the issue, please check

2022-06-03 00:14 UTC, prachi00 commented
> @prachi00 there was a request to rename most of the filters in the issue, please check

<img width="334" alt="Screen Shot 2022-06-02 at 5 13 16 PM" src="https://user-images.githubusercontent.com/39299315/171760542-77677d7e-4050-4e1c-b4eb-84db6867ed26.png">
Done

2022-06-04 06:17 UTC, petersopko approved these changes
LGTM

2022-06-04 06:42 UTC, petersopko commented
pay 200 usd

2022-06-04 06:42 UTC, yangwao commented
😍 Perfect, I’ve sent the payout 
💵 $200 @ 68.5 USD/KSM ~ 2.92 $KSM
🧗 [EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU](https://kusama.subscan.io/account/EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)
🔗 [0xd8fa62324483c87739eed855972c58880f7be00a20ba7ba810564c2de10feac5](https://kusama.subscan.io/extrinsic/0xd8fa62324483c87739eed855972c58880f7be00a20ba7ba810564c2de10feac5)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

2022-06-04 06:42 UTC, merged