feat(3208): Stats of the whole Basilisk marketplace
kodadot/nft-gallery pull request #3251
Opened 2022-06-23 10:13 UTC by petersopko

**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #3208 
- [x] Requires deployment of new snekk @vikiival 
- [x] New screen for stats about BSX marketplace 

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [ ] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=<My_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address>)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
![image](https://user-images.githubusercontent.com/73316633/175275739-0cf255d0-0a39-41e0-9226-4b133bde6f1b.png)

2022-06-23 11:33 UTC, vikiival requested changes

2022-06-23 11:33 UTC, vikiival commented on components/bsx/Offer/StatsOverview.vue
> +      </div>
Make component. 

DRY

2022-06-23 11:34 UTC, vikiival commented
What i would do is 


```ts
export function countOf(value: SomethingWithCount) {
  return value.count || value.totalCount
}
```

then in vue you can use

```ts
this.buys = countOf(buys)
```

2022-06-26 12:30 UTC, yangwao commented
Let's add one more column with relative time 

<img width="609" alt="image" src="https://user-images.githubusercontent.com/5887929/175814074-b6075b59-beb7-4657-a708-d0f37f4a7482.png">

> Link to NFT
Let's rename it to "Item"

2022-06-26 14:35 UTC, petersopko commented
> Let's add one more column with relative time, like we have in history

added relative time, not the same way as history, since history relative time is currently broken on BSX
- #3280 

> Let's rename it to "Item"\

done

2022-06-26 15:01 UTC, vikiival approved these changes

2022-06-26 15:07 UTC, merged