🔧 bsx seo preview & canonical links
kodadot/nft-gallery pull request #3282
Opened 2022-06-27 08:59 UTC by roiLeo

**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [x] Feature

### What's new?

- [x] PR closes #3243 
- [x] fix bsx GalleryItem seo preview
- [x] add canonical url on item & collection

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Had issue bounty label?

- [ ] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=<My_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address>)

### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

2022-06-27 14:09 UTC, yangwao commented
curious if that would work on `kodadot.xyz` domain as on `beta.kodadot.xyz` it used to work here and there

2022-06-28 06:37 UTC, roiLeo commented
> curious if that would work on `kodadot.xyz` domain as on `beta.kodadot.xyz` it used to work here and there

might be related with #2759

2022-07-03 06:35 UTC, prachi00 approved these changes

2022-07-04 13:15 UTC, yangwao commented
pay 100 usd

2022-07-04 13:15 UTC, yangwao commented
😍 Perfect, I’ve sent the payout 
💵 $100 @ 50.12 USD/KSM ~ 1.995 $KSM
🧗 [DVYy1qnocE8t6ZvUfPx3rEjG829khNRXx3YrCGVHHj19Lcb](https://kusama.subscan.io/account/DVYy1qnocE8t6ZvUfPx3rEjG829khNRXx3YrCGVHHj19Lcb)
🔗 [0x43306577632da3ad0c79ff075b4244f1289840dee4b00a71cdc40a7f6bcb065b](https://kusama.subscan.io/extrinsic/0x43306577632da3ad0c79ff075b4244f1289840dee4b00a71cdc40a7f6bcb065b)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

2022-07-05 07:09 UTC, roiLeo commented
> oh wait seems, can't test because have 524 and 429 errors :(
> 
> <img alt="image" width="388" src="https://user-images.githubusercontent.com/5887929/177163268-eac404f5-b9c8-41a3-b869-9408fd18231a.png">

?
I doubt we use cloudflare for seo

Tested with facebook opengraph debugger
![Capture d’écran 2022-07-05 à 9 04 55 AM](https://user-images.githubusercontent.com/9987732/177269788-cd5d38cc-4be5-4a31-9779-7c8b2d671c5e.png)

2022-07-07 11:43 UTC, yangwao commented
wfm 

<img width="749" alt="image" src="https://user-images.githubusercontent.com/5887929/177765531-9db428ce-6e4b-44e2-a1c2-34a79b25a5de.png">

2022-07-07 11:46 UTC, yangwao commented
> wait for this one, let me remove decimals from BSX amount

ooook 

<img src="https://media3.giphy.com/media/A8Uo4id6WCk8rJkJk5/giphy.gif"/>

2022-07-07 13:09 UTC, yangwao commented
chill we are far beyond worst 

<img src="https://media1.giphy.com/media/kyXIb4vkSFhPbh9gLc/giphy.gif"/>

2022-07-07 13:17 UTC, roiLeo commented
not working as excepted for now will change it a bit latter

2022-07-08 08:59 UTC, roiLeo commented
Blocked by #3374 can't make my local env to work (it show rmrk metadata in bsx item)

2022-07-09 19:40 UTC, roiLeo commented
Better now without empty decimals an added space on BSX (ref #3038)
![Capture](https://user-images.githubusercontent.com/9987732/178120324-bad7a2cd-b7b9-49d2-95e3-bc4ee8c81676.PNG)

I sense we need to do something to extend polkadot js `formatAmount` method

2022-07-12 06:03 UTC, kkukelka requested changes

2022-07-12 06:03 UTC, kkukelka commented on utils/format/balance.ts
> +) => {
adding return type here?
```suggestion
): string => {
```

2022-07-12 06:03 UTC, kkukelka commented on components/bsx/Gallery/Item/GalleryItem.vue
> +    return `${this.nft.name || ''}`
no template string needed here
```suggestion
    return this.nft?.name || ''
```

2022-07-12 06:28 UTC, roiLeo commented on components/bsx/Gallery/Item/GalleryItem.vue
> +    return `${this.nft.name || ''}`
oh no why did I copy this

2022-07-12 07:29 UTC, kkukelka approved these changes
excellent 👍

2022-07-12 15:38 UTC, merged

2022-07-12 15:38 UTC, kkukelka commented
pay 150

2022-07-12 16:04 UTC, roiLeo commented
![myman](https://user-images.githubusercontent.com/9987732/178539828-ae6285fe-190f-4cb0-90d4-48a6e2e6908a.jpg)