feat: Keep top border only on action buttons for on-chain actions
kodadot/nft-gallery pull request #3373
Opened 2022-07-07 17:12 UTC by zhengow

**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

### What's new?

- [ ] PR closes #3363
- [ ] Requires deployment <rubick/magick_issue>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [ ] My contribution builds **clean without any errors or warnings**
- [ ] I've merged recent default branch -- **main** and I've no conflicts
- [ ] I've tried to respect high code quality standards
- [ ] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [ ] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=<My_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address>)

### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

2022-07-08 00:13 UTC, Jarsen136 commented on components/rmrk/Gallery/Item/Sharing.vue
> +  // }
Why not put the logic here so that we don't need to write `$store.getters['history/getCurrentlyViewedItem']` many times.

2022-07-08 00:13 UTC, Jarsen136 commented on components/rmrk/Gallery/Item/Sharing.vue
> +  }
How about using a boolean value as its prop, to control the display of the download button.

2022-07-08 00:13 UTC, Jarsen136 commented on utils/shoppingActions.ts
> -  ShoppingActions.DOWNLOAD,
There are still some `ShoppingActions.DOWNLOAD` in the codebase, pls remove all of them.

2022-07-08 04:17 UTC, zhengow commented
@Jarsen136 
great idea, thx.
Already fix, pls check again.

2022-07-08 11:18 UTC, yangwao commented
have you checked it on BSX as well? 

<img width="343" alt="image" src="https://user-images.githubusercontent.com/5887929/177982258-2e448b8e-16c2-4024-8d10-7a2e68877ede.png">

2022-07-08 16:15 UTC, zhengow commented
> have you checked it on BSX as well?
> 
> <img alt="image" width="343" src="https://user-images.githubusercontent.com/5887929/177982258-2e448b8e-16c2-4024-8d10-7a2e68877ede.png">

My mistake. Already fix it.
<img width="1199" alt="image" src="https://user-images.githubusercontent.com/38389586/178030760-15e01054-a401-437f-a33f-4446a0f13349.png">

2022-07-09 03:40 UTC, Jarsen136 commented on components/unique/Gallery/Item/AvailableActions.vue
> +<style scoped lang="scss">
```suggestion
<style scoped>
```
because it does not need `scss`

2022-07-09 03:40 UTC, Jarsen136 commented on components/rmrk/Gallery/GalleryItem.vue
> +                  <Sharing show-download-icon class="mb-4" />
```suggestion
                  <Sharing enableDownload class="mb-4" />
```
according to `STYLE_GUIDE.md`

```
<MyCustomComponent :propertyName="doSomething">
    {{ someProperty }}
</MyCustomComponent>
```

2022-07-09 03:40 UTC, Jarsen136 commented on components/unique/Gallery/Item/AvailableActions.vue
> +}
I have seen this class name three times. 👀 

@roiLeo Do you have any idea about reusing this `top-border `effect?

2022-07-09 03:47 UTC, Jarsen136 commented
I could download any nft even though I'm not its owner.


<img width="916" alt="image" src="https://user-images.githubusercontent.com/31397967/178090326-8e892743-acb0-496e-b0e8-1e70e21e2f54.png">

Pls fix this problem.

2022-07-09 09:59 UTC, zhengow commented
> I could download any nft even though I'm not its owner.
> 
> 
> 
> https://deploy-preview-3373--koda-nuxt.netlify.app/rmrk/gallery/10281449-72544d5b203a79d527-DBE6E-STREET_IN_CETINJE-0000000000000003
> 
> <img width="1178" alt="image" src="https://user-images.githubusercontent.com/31397967/178090386-94cb6084-9425-4b2a-9f66-49dd0ae7e67e.png">
> 
> 
> 
> User could only download his own nft.
> 
> Pls fix this bug.
> 
> 
> 
> 

Emmm, but user could still download nft in other way?👀
Still need to fix this?

2022-07-09 10:39 UTC, Jarsen136 commented
> 
> Emmm, but user could still download nft in other way?👀 

Yes, but we should not provide that button. 
ref: https://github.com/kodadot/nft-gallery/issues/2557

2022-07-09 12:16 UTC, yangwao commented
> Emmm, but user could still download nft in other way?👀

yeah, we "disabled right-click", but of course, through the console, it would be possible. 

> Still need to fix this?

@Jarsen136 meant you should check the same condition if a user is the owner of it as it was in shopping actions iirc :)

2022-07-09 15:20 UTC, zhengow commented
got it. I will fix it later

2022-07-09 17:20 UTC, zhengow commented
> > Emmm, but user could still download nft in other way?👀
> 
> Yes, but we should not provide that button. ref: #2557

Already hidden it, pls check:)

2022-07-09 19:08 UTC, roiLeo reviewed
we already have a `$sleek-primary-border` that can do the work

2022-07-09 19:08 UTC, roiLeo commented on components/rmrk/Gallery/AvailableActions.vue
> +}
again but this one is scoped

2022-07-09 19:08 UTC, roiLeo commented on components/bsx/Gallery/Item/AvailableActions.vue
> +</style>
if global I would move this outside component

2022-07-09 19:08 UTC, roiLeo commented on components/rmrk/Gallery/Item/ActionList.vue
> +</style>
again same code

2022-07-10 17:42 UTC, zhengow commented
> we already have a `$sleek-primary-border` that can do the work

Fix it by refactor `only-border-top` scss to `@/styles/border.scss` and import them where it need.
However, I think `$sleek-primary-border` can't be used cuz each button has different color, and it need to hidden other three border. How do u think?

2022-07-11 11:35 UTC, yangwao commented
hey I've noticed in this PR I can make offer on own NFT 
https://deploy-preview-3373--koda-nuxt.netlify.app/bsx/gallery/3606678538-1
<img width="498" alt="image" src="https://user-images.githubusercontent.com/5887929/178255457-7291a39f-1d3d-4f6e-9ae1-ce547f35c955.png">

seems on https://beta.kodadot.xyz/bsx/gallery/3606678538-1 it's ok
<img width="534" alt="image" src="https://user-images.githubusercontent.com/5887929/178255514-153067fa-f949-4306-a28a-e623fc48caa3.png">

just noticed it now

2022-07-13 10:47 UTC, yangwao commented
@zhengow let's merge upstream and fix conflicts, maybe my last issues was fixed meanwhile :)

2022-07-16 06:15 UTC, zhengow commented
> @zhengow let's merge upstream and fix conflicts, maybe my last issues was fixed meanwhile :)

Already fix the bug, pls check again:)
<img width="1650" alt="image" src="https://user-images.githubusercontent.com/38389586/179342485-e7e9cbea-77bb-4f07-bdc9-2c47bbaa5619.png">

<img width="1675" alt="image" src="https://user-images.githubusercontent.com/38389586/179342657-367c8a24-a21c-45a3-8d5e-a03630f70524.png">

2022-07-16 06:23 UTC, Jarsen136 approved these changes
Awesome.

LGTM

2022-07-16 08:10 UTC, petersopko requested changes
pls check share button on rmrk

2022-07-16 08:10 UTC, petersopko commented
rmrk, on nft I bought 👀 

![image](https://user-images.githubusercontent.com/73316633/179346507-0e2a1c16-ac6a-420f-a5ef-3972894a945c.png)

2022-07-16 17:26 UTC, zhengow commented
> 

<img width="315" alt="image" src="https://user-images.githubusercontent.com/38389586/179365619-c789d4e3-cd75-40cf-8a15-a7fad14f3604.png">

Done

2022-07-17 08:00 UTC, petersopko approved these changes

2022-07-17 08:23 UTC, petersopko commented
pay 100 usd

2022-07-17 08:23 UTC, yangwao commented
😍 Perfect, I’ve sent the payout 
💵 $100 @ 56.54 USD/KSM ~ 1.769 $KSM
🧗 [EgCzZLpVe7zg7RHh79qPyC8UrykVkA22YY2oj7sWMZf15Ws](https://kusama.subscan.io/account/EgCzZLpVe7zg7RHh79qPyC8UrykVkA22YY2oj7sWMZf15Ws)
🔗 [0xf91c887411fa3be200c1081bac434b702d05a1ede0db15ac4c71faa7bc1f295f](https://kusama.subscan.io/extrinsic/0xf91c887411fa3be200c1081bac434b702d05a1ede0db15ac4c71faa7bc1f295f)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

2022-07-17 08:23 UTC, merged