feat: replace range slider with input fields
kodadot/nft-gallery pull request #3474
Opened 2022-07-18 17:08 UTC by zhengow

**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

### What's new?

- [ ] PR closes #<issue_number>
- [ ] Requires deployment <rubick/magick_issue>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [ ] My contribution builds **clean without any errors or warnings**
- [ ] I've merged recent default branch -- **main** and I've no conflicts
- [ ] I've tried to respect high code quality standards
- [ ] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=EgCzZLpVe7zg7RHh79qPyC8UrykVkA22YY2oj7sWMZf15Ws)

### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
![image](https://user-images.githubusercontent.com/38389586/179564860-efad615e-8b52-43bb-b36d-267e243a90ed.png)

![image](https://user-images.githubusercontent.com/38389586/179564949-2408a4de-46a8-437f-b930-7a1906fc7fe7.png)

![image](https://user-images.githubusercontent.com/38389586/179564983-8d66bdc1-c78b-46ec-8782-248eba11f919.png)

![image](https://user-images.githubusercontent.com/38389586/179565043-0722d916-49de-49aa-846c-e430cd02309c.png)

![image](https://user-images.githubusercontent.com/38389586/179565101-c9d9b3c3-4b24-499f-b5ac-e0af3faca1f3.png)

2022-07-19 04:21 UTC, zhengow commented
> 

Done, I add `type='number'`, it will not allowed to type non-number char.
btw, it will be disabled when `min price > max price`.
I allow empty input, since users maybe need to clearout price range.

2022-07-19 08:31 UTC, roiLeo reviewed
Works really well! 

Here's some comments

would it be possible to format number like we do in price? (10 000)
![Capture d’écran 2022-07-19 à 10 21 27 AM](https://user-images.githubusercontent.com/9987732/179704305-08914179-9e3e-4861-b8b5-dea3d73bdcae.png)

Since you choose to hide inputs when "BUY NOW" is disabled, how users will now they can filter by price range?
![Capture d’écran 2022-07-19 à 10 20 25 AM](https://user-images.githubusercontent.com/9987732/179704309-91d15e7c-1df7-49b9-9ce4-c978abcc0387.png)

2022-07-19 08:31 UTC, roiLeo commented on components/rmrk/Gallery/Search/SearchBar.vue
> +    return ''
can we add translation with values please?

2022-07-19 10:01 UTC, zhengow commented on components/rmrk/Gallery/Search/SearchBar.vue
> +    return ''
> can we add translation with values please?

Do you mean add in `en.json`?

2022-07-19 10:05 UTC, zhengow commented
> Since you choose to hide inputs when "BUY NOW" is disabled, how users will now they can filter by price range? ![Capture d’écran 2022-07-19 à 10 20 25 AM](https://user-images.githubusercontent.com/9987732/179704309-91d15e7c-1df7-49b9-9ce4-c978abcc0387.png)

That's right, I notice that old codes are in this logic. So I need to show them no matter whether it is `buy now`?

2022-07-19 10:08 UTC, roiLeo commented
> That's right, I notice that old codes are in this logic. So I need to show them no matter whether it is `buy now`?

This could be done now or latter don't bother with it

2022-07-19 10:52 UTC, zhengow commented
> 

I think it still better hide price filter if user choose `no buy now`.
Because some nft has no price if it is not listed.

2022-07-19 11:09 UTC, zhengow commented
> > That's right, I notice that old codes are in this logic. So I need to show them no matter whether it is `buy now`?
> 
> This could be done now or latter don't bother with it

Already fix all the advice, pls check again:)

2022-07-20 09:25 UTC, cryptodamsky requested changes
The way it’s done on BSX, for example " from 50,000 BSX to 55,000 BSX" is fine, makes sense

But the way it’s done on RMRK is confusing to me.

<img width="343" alt="image" src="https://user-images.githubusercontent.com/92786519/179947470-818623a2-87ef-4f72-8265-a5d4e298215c.png">

If you have a look, in some countries 1.000 means 1000.

Why have so many 0 there? I would just do " From range 1 to 15"

2022-07-20 09:42 UTC, roiLeo commented
@zhengow can you try to enable "BUY NOW" button when we click on "Apply" button?

2022-07-20 10:15 UTC, zhengow commented
> @zhengow can you try to enable "BUY NOW" button when we click on "Apply" button? because it's not displaying price on gallery cards

Sure

2022-07-20 10:37 UTC, roiLeo commented
> How about raise a new issue for this format problem in `Money Component`?

Depends how you planned to format RMRK values, but we can continue in #3355

2022-07-20 10:56 UTC, cryptodamsky reviewed
Feel like it’s not working?

<img width="1378" alt="image" src="https://user-images.githubusercontent.com/92786519/179965657-4675bc60-2520-442f-b5a7-7fa39084b534.png">


or is this the same issue related to the money component? or smth new

2022-07-20 12:26 UTC, zhengow commented
> > How about raise a new issue for this format problem in `Money Component`?
> 
> Depends how you planned to format RMRK values, but we can continue in #3355

Fix format RMRK values, looks like this:
<img width="1009" alt="image" src="https://user-images.githubusercontent.com/38389586/179981567-942c1c5e-b91c-4f18-aabc-2f77f28fd392.png">

2022-07-20 12:27 UTC, roiLeo commented
Hey don't forget to resolve conflicts please :)

2022-07-20 13:58 UTC, roiLeo commented
> > Still same issue?
> 
> ![Screenshot 2022-07-20 at 15-55-49 Low minting fees and carbonless NFTs KodaDot - Kusama NFT Market Explorer](https://user-images.githubusercontent.com/9987732/180000788-a9ead479-e0ac-4a9c-9102-3b832533207c.png)
> 
> Same for me, please don't use tooltip to display error message, [Buefy](https://buefy.org/documentation/input/#validation) inputs has validation or you can provide messages to `<b-field />` (plus there is a typo in your text)

2022-07-20 15:41 UTC, zhengow commented
> Still same issue?
> 
> <img alt="image" width="700" src="https://user-images.githubusercontent.com/92786519/179997108-4097054c-3a2c-425e-b1f6-9e213f1f352a.png">

My bugs, for not change type of variables `min` and `max` and compare them. Now fix it:

![image](https://user-images.githubusercontent.com/38389586/180025019-54d562eb-f216-410f-b795-bbbc09fbdb1d.png)
![image](https://user-images.githubusercontent.com/38389586/180025084-8be0c3e9-da9f-4b40-8726-37b9038cb9aa.png)

2022-07-20 15:42 UTC, zhengow commented
> > Still same issue?
> 
> ![Screenshot 2022-07-20 at 15-55-49 Low minting fees and carbonless NFTs KodaDot - Kusama NFT Market Explorer](https://user-images.githubusercontent.com/9987732/180000788-a9ead479-e0ac-4a9c-9102-3b832533207c.png)
> 
> Same for me, please don't use tooltip to display error message, [Buefy](https://buefy.org/documentation/input/#validation) inputs has validation or you can provide custom messages to `<b-field />` (plus there is a typo in your text)

Show validation massage in the bottom:

![image](https://user-images.githubusercontent.com/38389586/180025238-b22e9219-0248-49da-9648-52d81f0b3978.png)

2022-07-21 08:54 UTC, roiLeo requested changes
Hey! Tested on bsx & rmrk

Small last changes, see review
![Screenshot 2022-07-21 at 10-56-52 Low minting fees and carbonless NFTs KodaDot - Kusama NFT Market Explorer](https://user-images.githubusercontent.com/9987732/180174109-142f051f-eb2b-4a86-baaa-f242c35d20f4.png)

 - It throw errors when i type decimal number. Fix can be using `step` attribute (ref [spec](https://html.spec.whatwg.org/multipage/forms.html#the-step-attribute))
 - when filter minimum 20bsx, I would like to see items >= 20bsx

2022-07-21 08:54 UTC, roiLeo commented on components/rmrk/Gallery/Gallery.vue
> +              greaterThan: minPrice,
```suggestion
              greaterThanOrEqualTo: minPrice,
```

2022-07-21 08:54 UTC, roiLeo commented on components/rmrk/Gallery/Gallery.vue
> +            price: { greaterThan: minPrice },
```suggestion
            price: { greaterThanOrEqualTo: minPrice },
```

2022-07-21 08:54 UTC, roiLeo commented on components/rmrk/Gallery/Gallery.vue
> +            price_gt: minPrice,
```suggestion
            price_gte: minPrice,
```

2022-07-21 08:54 UTC, roiLeo commented on components/rmrk/Gallery/Gallery.vue
> +            price_gt: minPrice,
```suggestion
            price_gte: minPrice,
```

2022-07-21 08:54 UTC, roiLeo commented on components/rmrk/Gallery/Search/SearchBar.vue
> +            min="0"
```suggestion
            min="0"
            step="any"
```

2022-07-21 08:54 UTC, roiLeo commented on components/rmrk/Gallery/Search/SearchBar.vue
> +            min="0"
```suggestion
            min="0"
            step="any"
```

2022-07-21 10:29 UTC, zhengow commented
> Hey! Tested on bsx & rmrk
> 
> Small last changes, see review ![Screenshot 2022-07-21 at 10-56-52 Low minting fees and carbonless NFTs KodaDot - Kusama NFT Market Explorer](https://user-images.githubusercontent.com/9987732/180174109-142f051f-eb2b-4a86-baaa-f242c35d20f4.png)
> 
> * It throw errors when i type decimal number. Fix can be using `step` attribute (ref [spec](https://html.spec.whatwg.org/multipage/forms.html#the-step-attribute))
> * when filter minimum 20bsx, I would like to see items >= 20bsx

Fix it:)

2022-07-21 11:24 UTC, roiLeo approved these changes
✅ Tested & code lgtm

Thank you for your good work!

2022-07-21 11:43 UTC, petersopko approved these changes
wfm

2022-07-21 11:45 UTC, roiLeo commented
Oups since my last review, I totaly forgot that not listed nfts have a price of 0, so when we toggle "BUY NOW" it will filter nfts with a price greaterThanOrEqualTo 0 (which corresponds to all nfts)

2022-07-21 11:47 UTC, petersopko commented
> @petersopko Oups since my last review, I totaly forgot that not listed nfts have a price of 0, so when we toggle "BUY NOW" it will filter nfts with a price greaterThanOrEqualTo 0 (which corresponds to all nfts)

let's deal with it in 
- #3515

2022-07-21 11:48 UTC, roiLeo commented
wait i'm currently on this branch

2022-07-21 11:49 UTC, petersopko commented
> wait i'm currently on this branch

ah great, I'll wait for this one then :)

2022-07-21 11:51 UTC, roiLeo commented
noooo :(

2022-07-21 11:55 UTC, roiLeo commented
> noooo :(

now fixed! sorry for that but everytime someone enable merge from main I can't push anymore (not a fan of rebase)

2022-07-21 12:00 UTC, petersopko commented
> now fixed! sorry for that but everytime someone enable merge from main I can't push anymore (not a fan of rebase)

I didn't see your comment before I updated the branch, sorry 😆 

btw it seems to have issues even in the other way around? when I untoggle 'BUY NOW' the filter for gt.than > 0 disappears, but when I'm sorting by price desc.; I get to see NFTs with highest price (but price isn't showing in the gallery card).

Maybe this is something we should fix elsewhere, if the price is 0 we don't need the gallery card desc. but if it's more than that, we should show the price regardless of the 'BUY NOW' toggle position

current state:
![image](https://user-images.githubusercontent.com/73316633/180208050-53f30afc-ffdc-40d7-9b0f-609d07172ae7.png)

desired outcome:
![image](https://user-images.githubusercontent.com/73316633/180208656-7f651547-551c-4992-ab5f-ee3ff28840e2.png)

2022-07-21 12:04 UTC, roiLeo commented
> btw it seems to have issues even in the other way around? when I untoggle 'BUY NOW' the filter for gt.than > 0 disappears, but when I'm sorting by price desc.; I get to see NFTs with highest price (but price isn't showing in the gallery card).

Always been like this, no? 
https://kodadot.xyz/rmrk/explore?page=1&tab=GALLERY&listed=false&sort=PRICE_DESC

> Maybe this is something we should fix elsewhere, if the price is 0 we don't need the gallery card desc. but if it's more than that, we should show the price regardless of the 'BUY NOW' toggle position

Or we could try to toggle "BUY NOW" when sorting by PRICE and it would show the price on cards

2022-07-21 12:12 UTC, petersopko commented
pay 200 usd

2022-07-21 12:12 UTC, yangwao commented
😍 Perfect, I’ve sent the payout 
💵 $200 @ 59.07 USD/KSM ~ 3.386 $KSM
🧗 [EgCzZLpVe7zg7RHh79qPyC8UrykVkA22YY2oj7sWMZf15Ws](https://kusama.subscan.io/account/EgCzZLpVe7zg7RHh79qPyC8UrykVkA22YY2oj7sWMZf15Ws)
🔗 [0x9eb083b9206254a74695485cdfa3c312eaf6d7cfdebd19602c988df2d747a364](https://kusama.subscan.io/extrinsic/0x9eb083b9206254a74695485cdfa3c312eaf6d7cfdebd19602c988df2d747a364)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

2022-07-21 12:12 UTC, merged