#3333 Add explainer text in create nft
kodadot/nft-gallery pull request #3627
Opened 2022-07-31 00:13 UTC by prachi00

**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [ ] PR closes #3333
- [ ] Requires deployment <rubick/magick_issue>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [ ] My contribution builds **clean without any errors or warnings**
- [ ] I've merged recent default branch -- **main** and I've no conflicts
- [ ] I've tried to respect high code quality standards
- [ ] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [ ] Fill up your KSM address: 
[Payout](https://beta.kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)

### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
![Screen Shot 2022-07-30 at 5 12 37 PM](https://user-images.githubusercontent.com/39299315/182004298-f14f8577-a5b6-4392-bb04-25b27cbf34a9.png)

2022-07-31 09:00 UTC, petersopko commented
let's wait for
- https://github.com/kodadot/nft-gallery/issues/3630

before testing this accurately, just static look at this:
![image](https://user-images.githubusercontent.com/73316633/182018777-0ac4c532-8e06-4d5d-9a74-7f056aa20c59.png)

can we make the text appear only if I'm redirected there from the collection mint? Seems like an overkill to show the message all the time

2022-07-31 22:19 UTC, prachi00 commented
> let's wait for
> 
> * [minting on rmrk currently doesn't work #3630](https://github.com/kodadot/nft-gallery/issues/3630)
> 
> before testing this accurately, just static look at this: ![image](https://user-images.githubusercontent.com/73316633/182018777-0ac4c532-8e06-4d5d-9a74-7f056aa20c59.png)
> 
> can we make the text appear only if I'm redirected there from the collection mint? Seems like an overkill to show the message all the time

but it is possible that the user reloads and it wont still be visible, happened to me a couple of times

2022-08-01 08:33 UTC, petersopko commented
> but it is possible that the user reloads and it wont still be visible, happened to me a couple of times

that's okay, there's gonna be many people who are going to mint into existing collection, we don't want to keep showing them the message all the time

2022-08-01 11:58 UTC, JustLuuuu commented
> > but it is possible that the user reloads and it wont still be visible, happened to me a couple of times
> 
> that's okay, there's gonna be many people who are going to mint into existing collection, we don't want to keep showing them the message all the time

Yes I agree, seeing the message before I ever tried to mint something is also not very ideal.

2022-08-04 05:11 UTC, kkukelka requested changes

2022-08-04 05:11 UTC, kkukelka commented on components/base/BaseTokenForm.vue
> +      :showExplainerTest="showExplainerTest" />
should this be `text`instead of `test`?
```suggestion
      :showExplainerText="showExplainerText" />
```

2022-08-04 05:11 UTC, kkukelka commented on components/base/BaseTokenForm.vue
> +  @Prop({ type: Boolean, default: true }) showExplainerTest!: boolean
```suggestion
  @Prop({ type: Boolean, default: true }) showExplainerText!: boolean
```

2022-08-04 05:11 UTC, kkukelka commented on components/base/CollectionSelect.vue
> +    <div class="mb-2" v-if="showExplainerTest">
```suggestion
    <div class="mb-2" v-if="showExplainerText">
```

2022-08-04 05:11 UTC, kkukelka commented on components/base/CollectionSelect.vue
> +  @Prop({ type: Boolean, default: true }) showExplainerTest!: boolean
```suggestion
  @Prop({ type: Boolean, default: true }) showExplainerText!: boolean
```

2022-08-04 05:11 UTC, kkukelka commented on components/bsx/Create/CreateToken.vue
> +      :showExplainerTest="showExplainerTest"
```suggestion
      :showExplainerText="showExplainerText"
```

2022-08-04 05:11 UTC, kkukelka commented on components/bsx/Create/CreateToken.vue
> +  @Prop({ type: Boolean, default: true }) showExplainerTest!: boolean
```suggestion
  @Prop({ type: Boolean, default: true }) showExplainerText!: boolean
```

2022-08-04 05:11 UTC, kkukelka commented on pages/bsx/create.vue
> +    this.showExplainerTest = true
```suggestion
  public showExplainerText = false

  protected switchToNft() {
    this.switchToCreateNFT()
    this.showExplainerText = true
```

2022-08-04 05:11 UTC, kkukelka commented on pages/bsx/create.vue
> +          :showExplainerTest="showExplainerTest"
```suggestion
          :showExplainerText="showExplainerText"
```

2022-08-04 05:49 UTC, kkukelka approved these changes

2022-08-04 05:50 UTC, merged

2022-08-04 05:50 UTC, kkukelka commented
pay 100

2022-08-04 05:50 UTC, yangwao commented
😍 Perfect, I’ve sent the payout 
💵 $100 @ 62.54 USD/KSM ~ 1.599 $KSM
🧗 [EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU](https://kusama.subscan.io/account/EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)
🔗 [0x5418d8421a55bb41c226007bb930e480e992239b95539fe57e06d89972ee1749](https://kusama.subscan.io/extrinsic/0x5418d8421a55bb41c226007bb930e480e992239b95539fe57e06d89972ee1749)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

2022-08-04 09:58 UTC, petersopko commented
okay, the message seems to be showing up all the time though? every time I open 
- https://kodadot.xyz/rmrk/create
- https://beta.kodadot.xyz/rmrk/create/

shows up even when I'm not logged in, @JustLuuuu ?
![image](https://user-images.githubusercontent.com/73316633/182819612-af9c7b75-b639-497a-8039-f5c5e31e0b64.png)