#3463 Master offers component
kodadot/nft-gallery pull request #3692
Opened 2022-08-07 00:18 UTC by prachi00

**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [ ] PR closes #3463
- [ ] Requires deployment <rubick/magick_issue>
- [ ] route is` /bsx/offers`

### Before submitting Pull Request, please make sure:

- [ ] My contribution builds **clean without any errors or warnings**
- [ ] I've merged recent default branch -- **main** and I've no conflicts
- [ ] I've tried to respect high code quality standards
- [ ] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [ ] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=<My_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address>)

### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
![Screen Shot 2022-08-06 at 5 17 53 PM](https://user-images.githubusercontent.com/39299315/183269850-3cb99550-ae40-4ca1-95c3-9836dbd95a62.png)

![Screen Shot 2022-08-06 at 5 15 58 PM](https://user-images.githubusercontent.com/39299315/183269817-70a6c585-7b75-44cc-b0f1-0d689875c822.png)

2022-08-08 09:48 UTC, petersopko commented
tested without wallet logged in, received 400 network error, pls check

2022-08-08 09:48 UTC, petersopko requested changes
error without wallet

2022-08-08 20:05 UTC, prachi00 commented
> https://deploy-preview-3692--koda-nuxt.netlify.app

where? because if you are not logged in, then the option is hidden 
<img width="386" alt="Screen Shot 2022-08-08 at 1 04 47 PM" src="https://user-images.githubusercontent.com/39299315/183504554-c90460c6-b5af-4918-ae90-c005566a6a73.png">

2022-08-09 10:35 UTC, petersopko commented
So some feedback after checking this more thoroughly:

1. the tabs should be filter (F2) with two options as described in the issue, but let's make it three with first one being `All offers`, dropdown as the one for the offer status (F1). If there isn't valid address inserted, the F2 can be disabled dropdown (stuck at `All offers`), becoming enabled once there's valid address, giving two more filtering options, i.e. `Offers Created` and `Incoming Offers`

2. logged out user should be able to land at this page, and still see all of the offers (without entering address), data should be fetched the same way as in `/bsx/stats`

3. the entry field for address doesn't need `Check offers` button next to it, it could be 2 sec debounce and offers can be fetched once there's valid address

2022-08-10 01:31 UTC, prachi00 commented
> So some feedback after checking this more thoroughly:
> 
> 1. the tabs should be filter (F2) with two options as described in the issue, but let's make it three with first one being `All offers`, dropdown as the one for the offer status (F1). If there isn't valid address inserted, the F2 can be disabled dropdown (stuck at `All offers`), becoming enabled once there's valid address, giving two more filtering options, i.e. `Offers Created` and `Incoming Offers`
> 2. logged out user should be able to land at this page, and still see all of the offers (without entering address), data should be fetched the same way as in `/bsx/stats`
> 3. the entry field for address doesn't need `Check offers` button next to it, it could be 2 sec debounce and offers can be fetched once there's valid address

Regarding 2nd, can logged out users see the input box?

2022-08-10 01:53 UTC, prachi00 commented
Also, for all offers option, there should be no input box right?

2022-08-10 09:23 UTC, petersopko commented
> can logged out users see the input box?

yes 

> also initially, when the user reloads, there will be address in the input box and option will be all, so wouldn't it be confusing that what the address id doing?

Hmm maybe we don't understand each other here, if there will be an address in the input field, you will be fetching all of the offers related to the address (incoming offers and made offers), if there isn't address, you're fetching all of the offers.

2022-08-10 18:03 UTC, prachi00 commented
> > can logged out users see the input box?
> 
> yes
> 
> > also initially, when the user reloads, there will be address in the input box and option will be all, so wouldn't it be confusing that what the address id doing?
> 
> Hmm maybe we don't understand each other here, if there will be an address in the input field, you will be fetching all of the offers related to the address (incoming offers and made offers), if there isn't address, you're fetching all of the offers.
<img width="1486" alt="Screen Shot 2022-08-10 at 11 01 57 AM" src="https://user-images.githubusercontent.com/39299315/183984289-f5067497-82e6-4a8f-9ceb-b03e025e1763.png">
 okay, so logged in users will see these 3 options right and there is address in the input field by default for them, so which filter do they see first, `incoming` or `created`?

2022-08-10 18:05 UTC, prachi00 commented
> > > can logged out users see the input box?
> > 
> > 
> > yes
> > > also initially, when the user reloads, there will be address in the input box and option will be all, so wouldn't it be confusing that what the address id doing?
> > 
> > 
> > Hmm maybe we don't understand each other here, if there will be an address in the input field, you will be fetching all of the offers related to the address (incoming offers and made offers), if there isn't address, you're fetching all of the offers.
> 
> <img alt="Screen Shot 2022-08-10 at 11 01 57 AM" width="1486" src="https://user-images.githubusercontent.com/39299315/183984289-f5067497-82e6-4a8f-9ceb-b03e025e1763.png">
> 
> okay, so logged in users will see these 3 options right and there is address in the input field by default for them, so which filter do they see first, `incoming` or `created`?



Also, if logged out users can see the input box, can they enter address and view incoming or created? because I was under the assumption that they cant do that

2022-08-11 20:32 UTC, prachi00 commented
> Also, if logged out users can see the input box, can they enter address and view incoming or created? because I was under the assumption that they cant do that

@petersopko ⬆️

2022-08-12 07:56 UTC, petersopko commented
> Also, if logged out users can see the input box, can they enter address and view incoming or created? because I was under the assumption that they cant do that

yes, they can enter address and view incoming/created. input field is always enabled to enter an address, thing which is disabled is the filter until the valid address it's entered

2022-08-15 14:38 UTC, petersopko commented
@prachi00 any updates on this one? :)

2022-08-15 17:32 UTC, prachi00 commented
> @prachi00 any updates on this one? :)

sorry about the delay, I was out the whole last week but getting back to this from today

2022-08-17 05:47 UTC, prachi00 commented
@petersopko initially when the user first opens it, should they see their own offers or general offers same as stats?

2022-08-17 07:02 UTC, petersopko commented
> @petersopko initially when the user first opens it, should they see their own offers or general offers same as stats?

to quote from the initial issue description

> When the logged-in user visits /bsx/offers it lands on its own address stats by default, i.e. in my case
> /bsx/offers?u=bXgvP2cQzEnPvuPQHRghz9dUYovqzyPhXBRXbNwVCef7nsmqb
> where default would be incoming offers

2022-08-18 01:35 UTC, prachi00 commented
@petersopko fixed the issues mentioned

2022-08-18 06:06 UTC, petersopko commented
> @petersopko fixed the issues mentioned

Test failed, and deepsource seems to have some kind of problem with the code tho ?

2022-08-18 06:09 UTC, petersopko commented
On mobile it looks like this
![image](https://user-images.githubusercontent.com/73316633/185306644-58aa0b46-c4b5-4e8d-a62f-be1fddfaeca3.png)

2022-08-19 01:40 UTC, prachi00 commented
> On mobile it looks like this ![image](https://user-images.githubusercontent.com/73316633/185306644-58aa0b46-c4b5-4e8d-a62f-be1fddfaeca3.png)

just merged with the main branch, should be fixed now

2022-08-19 12:03 UTC, petersopko requested changes
1. if I visit `/bsx/offers` without being logged in, and I log in, my address doesn't fill out
2. if I visit `/bsx/offers` while logged in, my address doesn't fill the search
3. the only time address input bar behaves correctly is when I get there through navbar, please fix that
4. please rename `Offer stats` to `Offers stats`

2022-08-19 12:23 UTC, petersopko commented
I have fixed the failing tests for you, please check [this part of CONTRIBUTING.md](https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#keeping-tests-relevant) for further reference on how to make the tests happy once you change some of the tested subjects :)

2022-08-20 23:57 UTC, prachi00 commented
> I have fixed the failing tests for you, please check [this part of CONTRIBUTING.md](https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#keeping-tests-relevant) for further reference on how to make the tests happy once you change some of the tested subjects :)

got it, thank you for fixing this time, I'll make sure to do it from next time

2022-08-21 00:02 UTC, prachi00 commented
> 4\. Offers

for 1 and 2, I actually depend on the url to fill out the address in the input
`/bsx/offers?target=bXjGftu3aagU6RzMCKHi66X84jap3RKtvv6t1kxD2KXbJMiG2`

2022-08-21 17:09 UTC, kkukelka requested changes

2022-08-21 17:09 UTC, kkukelka commented on components/bsx/Offer/MasterOfferTable.vue
> +    this.skipUserOffer = skipAddress
the method is called once without giving any value to `skipAddress`so I'm not sure what will happen when setting `skipUserOffer` to optional value. I think its better to just set it to false as default value
```suggestion
  public checkOfferForAddress(skipAddress = false) {
    this.skipUserOffer = skipAddress
```

2022-08-21 17:09 UTC, kkukelka commented on components/bsx/Offer/MyOffer.vue
> +  onAddressChange(value) {
```suggestion
  onAddressChange(value: string) {
```

2022-08-23 02:43 UTC, prachi00 commented
> > 4. Offers
> 
> for 1 and 2, I actually depend on the url to fill out the address in the input `/bsx/offers?target=bXjGftu3aagU6RzMCKHi66X84jap3RKtvv6t1kxD2KXbJMiG2` because not doing this was creating a lot of edge cases for example, if you erase the input bar to view all the offers and then reload, it would show user's offers again

@petersopko let me know if this seems okay to you?

2022-08-23 05:24 UTC, kkukelka approved these changes
lg now

2022-08-25 17:59 UTC, yangwao commented
let's resolve conflicts :)

2022-08-25 18:05 UTC, prachi00 commented
> let's resolve conflicts :)

done

2022-08-27 11:37 UTC, petersopko approved these changes
ok lgtm

2022-08-27 11:38 UTC, merged

2022-08-27 11:38 UTC, petersopko commented
> @petersopko let me know if this seems okay to you?

it's not ideal, but this issue wasn't defined in great detail, so let's follow up with some tweaks

2022-08-27 11:39 UTC, petersopko commented
pay 150 usd

2022-08-27 11:39 UTC, yangwao commented
😍 Perfect, I’ve sent the payout 
💵 $150 @ 45.38 USD/KSM ~ 3.305 $KSM
🧗 [EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU](https://kusama.subscan.io/account/EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)
🔗 [0x6ae7f9ab6b7fc3ea6a5dd18664c064f823e5b730ab15ec746513dc9f50c0c07b](https://kusama.subscan.io/extrinsic/0x6ae7f9ab6b7fc3ea6a5dd18664c064f823e5b730ab15ec746513dc9f50c0c07b)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)