refactor: Curated List - Vue Composition API
kodadot/nft-gallery pull request #3825
Opened 2022-08-24 09:04 UTC by preschian

**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

### What's new?

- [x] PR closes #3772
- [x] WIP, branching from https://github.com/kodadot/nft-gallery/pull/3771
- [ ] Requires deployment <rubick/magick_issue>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

2022-09-01 11:49 UTC, petersopko commented
wfm 🚀

2022-09-01 11:50 UTC, petersopko approved these changes
✅

2022-09-01 15:25 UTC, kkukelka requested changes
2 tiny things 😅

2022-09-02 05:54 UTC, preschian commented on pages/snek/create.vue
> +          v-if="components[activeTab] === x"
sure, that would be nice. will update it 👍

actually, these changes are from the main branch, it was triggered with lint-staged on my local

2022-09-02 08:48 UTC, kkukelka approved these changes
all good now

2022-09-02 08:49 UTC, merged

2022-09-02 08:49 UTC, kkukelka commented
@preschian whats the payment range for this, i cannot tell from the linked tickets