feat: Migrating Offers related components to /snek
kodadot/nft-gallery pull request #3893
Opened 2022-08-31 16:17 UTC by zhengow

**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #3888 
- [ ] Requires deployment <rubick/magick_issue>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [ ] My contribution builds **clean without any errors or warnings**
- [ ] I've merged recent default branch -- **main** and I've no conflicts
- [ ] I've tried to respect high code quality standards
- [ ] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [ ] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=<My_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address>)

### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

2022-09-01 04:34 UTC, kkukelka requested changes

2022-09-01 04:34 UTC, kkukelka commented on components/rmrk/Profile/NavbarProfileDropdown.vue
> +      <b-dropdown-item v-if="isBsx || isSnek" has-link aria-role="menuitem">
can we make this just 1 prop called "showIncommingOffers"
and in `Navbar.vue` just propagate it via `:show-incomming-offers="isBsx || isSnek"`

2022-09-01 04:34 UTC, kkukelka commented on components/rmrk/Profile/NavbarProfileDropdown.vue
> +  @Prop() public isSnek!: boolean
so let's combine them

2022-09-01 11:11 UTC, petersopko commented
@zhengow let's make sure the displayed currency matches everywhere (should be KSM, not BSX)
examples I quickly found:
![image](https://user-images.githubusercontent.com/73316633/187900299-ddc0359d-f228-4bd3-a103-7837b3a568c2.png)
and
![image](https://user-images.githubusercontent.com/73316633/187900348-d84a7031-c7df-423f-9ae1-add0d847b74f.png)

2022-09-01 12:50 UTC, kkukelka commented
+ 2 new conflicts

2022-09-01 13:37 UTC, petersopko commented
@zhengow if #3884 gets merged before this one, please uncomment some of the navbar tests in `basicE2E.cy.ts` -> they were disabled until we get stats back in navbar

2022-09-03 05:40 UTC, zhengow commented
> * 2 new conflicts

resolved:)

2022-09-03 05:41 UTC, zhengow commented
> @zhengow let's make sure the displayed currency matches everywhere (should be KSM, not BSX) examples I quickly found: ![image](https://user-images.githubusercontent.com/73316633/187900299-ddc0359d-f228-4bd3-a103-7837b3a568c2.png) and ![image](https://user-images.githubusercontent.com/73316633/187900348-d84a7031-c7df-423f-9ae1-add0d847b74f.png)

Fix it by looking at #3906

2022-09-03 05:44 UTC, zhengow commented
> @zhengow if #3884 gets merged before this one, please uncomment some of the navbar tests in `basicE2E.cy.ts` -> they were disabled until we get stats back in navbar

There is no commented navbar tests now, is now ok?

2022-09-03 06:13 UTC, zhengow commented
> @zhengow if #3884 gets merged before this one, please uncomment some of the navbar tests in `basicE2E.cy.ts` -> they were disabled until we get stats back in navbar

Done,
![image](https://user-images.githubusercontent.com/38389586/188258396-d5408680-d855-4586-9c66-d78bb5e3f8de.png)

2022-09-03 10:07 UTC, kkukelka approved these changes
all good now

2022-09-04 07:12 UTC, petersopko approved these changes
wfm

2022-09-04 07:13 UTC, petersopko commented
some leftovers with BSX->KSM as displayed currency, can be possibly solved in:
- https://github.com/kodadot/nft-gallery/pull/3906

2022-09-04 07:15 UTC, petersopko commented
pay 50 usd

2022-09-04 07:15 UTC, yangwao commented
😍 Perfect, I’ve sent the payout 
💵 $50 @ 49.8 USD/KSM ~ 1.004 $KSM
🧗 [EgCzZLpVe7zg7RHh79qPyC8UrykVkA22YY2oj7sWMZf15Ws](https://kusama.subscan.io/account/EgCzZLpVe7zg7RHh79qPyC8UrykVkA22YY2oj7sWMZf15Ws)
🔗 [0x7dc5bf5ab3055ea883eb4e4d9dcf34420e47c1454206e57d31ca8cc6c677783c](https://kusama.subscan.io/extrinsic/0x7dc5bf5ab3055ea883eb4e4d9dcf34420e47c1454206e57d31ca8cc6c677783c)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

2022-09-04 07:15 UTC, merged