fix: light mode leftovers
kodadot/nft-gallery pull request #3977
Opened 2022-09-18 11:24 UTC by alohaw0

**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [X] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [X] PR closes #3972
- [ ] Requires deployment <rubick/magick_issue>
- [X] fix: light mode leftovers

### Before submitting Pull Request, please make sure:

- [X] My contribution builds **clean without any errors or warnings**
- [X] I've merged recent default branch -- **main** and I've no conflicts
- [X] I've tried to respect high code quality standards
- [X] I've didn't break any original functionality
- [X] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [X] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=<My_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address>)

### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [X] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
![图片](https://user-images.githubusercontent.com/113782793/190899493-1e3911d8-091c-4eec-a0b9-96e7ac8c8060.png)
![图片](https://user-images.githubusercontent.com/113782793/190899517-0daebef9-f58f-441e-bf04-322c0098a36a.png)
![图片](https://user-images.githubusercontent.com/113782793/190899547-9d830e96-b2be-4c9f-a698-d3332bfcdc9a.png)
![图片](https://user-images.githubusercontent.com/113782793/190899571-78681a30-522c-4ce0-bf53-b58cc10bba87.png)
etc...

2022-09-18 13:59 UTC, petersopko commented
nice, wfm

2022-09-18 13:59 UTC, petersopko approved these changes

2022-09-19 10:00 UTC, roiLeo requested changes
Small note:
`.card .card-content` css rule is going to overide all card content design from app

2022-09-19 10:00 UTC, roiLeo commented on styles/themes/_light.scss
> +	.card .card-content,
![Capture d’écran 2022-09-19 à 11 57 20 AM](https://user-images.githubusercontent.com/9987732/190993502-75f80cdc-4b03-4571-bbcd-8a8c336b9268.png)

What are you trying to fix here?

2022-09-19 12:38 UTC, petersopko commented
@alohaw0 let's please adjust the changes to only reflect what needs to be done based on the issue :)

2022-09-19 15:57 UTC, alohaw0 commented
> @alohaw0 let's please adjust the changes to only reflect what needs to be done based on the issue :)

I noticed that the .nft-card is the only class works to cards in that case. 
So I changed the `.card` to `.nft-card` in the newer commit.

@petersopko @roiLeo PTAL

2022-09-19 16:14 UTC, roiLeo approved these changes
✅ code looks good

2022-09-20 10:34 UTC, petersopko commented
wfm 🚀

2022-09-20 10:45 UTC, merged

2022-09-20 10:46 UTC, petersopko commented
pay 30 usd

2022-09-20 10:46 UTC, yangwao commented
😍 Perfect, I’ve sent the payout 
💵 $30 @ 39.88 USD/KSM ~ 0.752 $KSM
🧗 [HL37EEfDA8Bfn5E7sHxuNn1xHuT1wmeQKaQfZV3eTq1XymN](https://kusama.subscan.io/account/HL37EEfDA8Bfn5E7sHxuNn1xHuT1wmeQKaQfZV3eTq1XymN)
🔗 [0x2a6b5bd3878d33cc35faaf1491c8c8f4991615c8a8658549e1aa6a3d6817edbe](https://kusama.subscan.io/extrinsic/0x2a6b5bd3878d33cc35faaf1491c8c8f4991615c8a8658549e1aa6a3d6817edbe)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)