WIP: #3948 Footer redesign
kodadot/nft-gallery pull request #4016
Opened 2022-09-23 18:17 UTC by prachi00

**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [ ] PR closes #3948
- [ ] Requires deployment <rubick/magick_issue>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [ ] My contribution builds **clean without any errors or warnings**
- [ ] I've merged recent default branch -- **main** and I've no conflicts
- [ ] I've tried to respect high code quality standards
- [ ] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [ ] Fill up your KSM address: 
[Payout](https://beta.kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)

### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

2022-09-23 18:17 UTC, prachi00 commented
Left:
- [ ] INPUT - working on this

2022-09-24 09:10 UTC, vikiival commented
🫣

![5C10C386-8384-47E0-A399-94B5F80D3306](https://user-images.githubusercontent.com/22471030/192090084-9d2519da-c747-4388-ab8d-36574a9cbf43.jpeg)

2022-09-24 14:16 UTC, roiLeo requested changes
On OSX 13-inch:

**preview**
![Screenshot 2022-09-24 at 16-02-04 KodaDot - Kusama NFT Market Explorer](https://user-images.githubusercontent.com/9987732/192102643-a87c0316-dec6-4908-be1b-1f47efe78212.png)

**figma**
<img width="1440" alt="Capture d’écran 2022-09-24 à 4 11 22 PM" src="https://user-images.githubusercontent.com/9987732/192102664-e16647ac-ab3e-43f8-8dd1-46bd34a0ef83.png">

Could you please use [Columns](https://bulma.io/documentation/columns/) as it would help to make the footer responsive
And also remove single quote changes for .scss files

2022-09-25 16:58 UTC, yangwao commented
we just had a call @exezbcz that will update Figma with new footer where we put two columns as current one breaks on mobile interface :)

2022-09-28 14:09 UTC, exezbcz commented
Hey @prachi00 @roiLeo, I redesigned the footer and added columns, it's updated in Figma, second page - design, under the landing page. There is also a mobile version. Thanks and sorry for the delay.

2022-09-29 03:11 UTC, prachi00 commented
@yangwao @roiLeo 
<img width="1504" alt="Screen Shot 2022-09-28 at 8 11 19 PM" src="https://user-images.githubusercontent.com/39299315/192930138-e0fb88f7-5c07-4a15-8377-8673c00b7cdb.png">
also what are we doing about the iframe, as I am not sure if there is other way to handle it

2022-09-29 03:34 UTC, prachi00 commented
@roiLeo also using `columns` is creating spacing differences from figma and we anyway have to give extra css to override those, so I was thinking of manually doing the responsive for this, its easier

2022-09-29 06:42 UTC, roiLeo commented
> @roiLeo also using `columns` is creating spacing differences from figma and we anyway have to give extra css to override those, so I was thinking of manually doing the responsive for this, its easier

- https://bulma.io/documentation/columns/gap/
- to many redundant css
- use new font
- no hover state on "Community" buttons
- I would suggest adding an icon next to the external links
- substack input?

2022-09-30 06:07 UTC, prachi00 commented
> * no hover state on "Community" buttons

okay I'll check these later today
@exezbcz for community buttons, what is the hover state?

2022-09-30 10:16 UTC, exezbcz commented
@prachi00 Hi, I think I have already mentioned it somewhere, but the hover state is k-accentlight

2022-09-30 18:58 UTC, prachi00 commented
> k-accentlight

yeah for text and links right, how do we apply k-accentlight here on these buttons 
![Screen Shot 2022-09-30 at 11 58 44 AM](https://user-images.githubusercontent.com/39299315/193338579-51a00d38-53f2-4019-bf35-6f0f6fbd09d1.png)

2022-09-30 19:50 UTC, prachi00 commented
![Screen Shot 2022-09-30 at 12 50 27 PM](https://user-images.githubusercontent.com/39299315/193346013-f4857dd6-6c9f-4d8f-9c75-a7ddb735367e.png)

2022-10-01 11:06 UTC, exezbcz commented
nope, @prachi00 the links - about, FAQ... are behaving the same as nav bar links - bold text on hover. Buttons like Instagram, discord, etc. are changing bg from k-white to k-accentlight on hover.

2022-10-02 06:42 UTC, prachi00 commented
> k-accentlight

so I added it, it looks a little weird though, and also doesnt support dark mode
<img width="338" alt="Screen Shot 2022-10-01 at 11 42 33 PM" src="https://user-images.githubusercontent.com/39299315/193441596-daf39681-c809-41b1-9776-a3af12e674da.png">

2022-10-02 07:38 UTC, exezbcz commented
![image](https://user-images.githubusercontent.com/90852205/193443333-e995f96f-5183-4733-844a-9434b7c11aff.png)
This is how the colors should look in dark mode. In white mode, the buttons work the same as for example selection of timeframe in top collections. It's consistent with the whole design/system. 
White mode buttons (the middle button is on hover)
![image](https://user-images.githubusercontent.com/90852205/193443445-0a3b191d-d178-482e-b570-c09c944c7030.png)

2022-10-03 05:54 UTC, prachi00 commented
> ![image](https://user-images.githubusercontent.com/90852205/193443333-e995f96f-5183-4733-844a-9434b7c11aff.png) This is how the colors should look in dark mode. In white mode, the buttons work the same as for example selection of timeframe in top collections. It's consistent with the whole design/system. White mode buttons (the middle button is on hover) ![image](https://user-images.githubusercontent.com/90852205/193443445-0a3b191d-d178-482e-b570-c09c944c7030.png)

okay makes sense, thank you

2022-10-03 06:34 UTC, roiLeo reviewed
Hey! Substack input looks better.
Found 2 small things:

![Capture d’écran 2022-10-03 à 8 30 27 AM](https://user-images.githubusercontent.com/9987732/193514232-e0132bd3-7940-41ed-a07e-727328588a0c.png)

- From Figma file, footer should be wrapped in `.container` class (check landing div/section wrapper)


https://user-images.githubusercontent.com/9987732/193514517-0a1066b9-da4b-455a-8095-e0c6cd06a6a7.mov

- cursor on hover state on social link are working only on icon and not on the button


![Screenshot 2022-10-03 at 08-49-31 KodaDot - Kusama NFT Market Explorer](https://user-images.githubusercontent.com/9987732/193516867-3ed4ae72-908c-4eb1-a8c8-556927657ca0.png)


- include icon in hover state

2022-10-04 07:03 UTC, roiLeo reviewed
Feel free to migrate `TheFooter` component to Vue3 way

2022-10-04 07:03 UTC, roiLeo commented on components/TheFooter.vue
> +        <span class="footer-container-heading">{{
instead of span I would use something like `<h4 class="has-text-white subtitle is-5">` that would do the same without your css

2022-10-04 07:03 UTC, roiLeo commented on components/TheFooter.vue
> +        <span class="footer-container-heading">KodaDot</span>
same comment here

2022-10-04 07:03 UTC, roiLeo commented on components/TheFooter.vue
> +        <span class="footer-container-heading">{{ $t('footer.join') }}</span>
same stuff here

2022-10-04 07:04 UTC, roiLeo commented on components/TheFooter.vue
> +        <span class="footer-container-heading">{{
semantic + respect spacing from design

2022-10-07 06:50 UTC, roiLeo commented on package.json
> +  "dependencies": {
```suggestion
  "dependencies": {
```

2022-10-07 06:52 UTC, roiLeo approved these changes
✅ lgtm, scss might need some refacto

2022-10-07 09:09 UTC, petersopko approved these changes
✅

2022-10-07 09:10 UTC, petersopko commented
pay 100 usd

2022-10-07 09:10 UTC, yangwao commented
😍 Perfect, I’ve sent the payout 
💵 $100 @ 43.39 USD/KSM ~ 2.305 $KSM
🧗 [EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU](https://kusama.subscan.io/account/EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)
🔗 [0x3a7f3c1b5770fc544d1d447079b9adf5e658c72ae6ec1c6ee924806f27176a42](https://kusama.subscan.io/extrinsic/0x3a7f3c1b5770fc544d1d447079b9adf5e658c72ae6ec1c6ee924806f27176a42)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

2022-10-07 09:39 UTC, merged