redesign: wallet connect
kodadot/nft-gallery pull request #4113
Opened 2022-10-13 18:02 UTC by zhengow

**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [] Feature
- [x] Refactoring

### What's new?

- [x] PR closes #4112
- [ ] Requires deployment <rubick/magick_issue>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=EgCzZLpVe7zg7RHh79qPyC8UrykVkA22YY2oj7sWMZf15Ws)

### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

https://user-images.githubusercontent.com/38389586/195671831-5ca492aa-5736-4c21-b65e-f984d613a100.mp4

2022-10-14 07:41 UTC, kkukelka requested changes
remove the unnecessary style attributes

2022-10-14 07:41 UTC, kkukelka commented on components/common/WalletModal.vue
> +                style="display: inline-block; vertical-align: middle"></b-image>
you can make a self-closing tag out of this and use dedicated bulma classes instead of styles
`is-inline-block`

2022-10-14 07:41 UTC, kkukelka commented on components/common/WalletModal.vue
> +              style="display: inline-block; vertical-align: middle" />
use bulma class instead of inline-block style. maybe you even find one for vertical-align too

2022-10-14 07:41 UTC, kkukelka commented on components/common/WalletModal.vue
> +            style="width: 100%">
`is-fullwidth` should work i assume

2022-10-14 07:41 UTC, kkukelka commented on components/common/WalletModal.vue
> +                    style="display: inline-block; vertical-align: middle" />
same as above

2022-10-14 07:41 UTC, kkukelka commented on components/common/WalletModal.vue
> +                  <b style="color: #ffffff">{{
`is-white`

2022-10-14 12:03 UTC, exezbcz commented
![image](https://user-images.githubusercontent.com/90852205/195842005-39d9cea6-0786-4c92-b0cc-4b4d87af9d76.png)
Hi, the wallet name boxes should all be the same size and when you click on one the dropdown should get bigger at the expense of the others, it shouldn't be like another page. So for example download the extension and learn how to connect will replace the other wallet selectors. Also, these buttons should be the same size
 ![image](https://user-images.githubusercontent.com/90852205/195842005-39d9cea6-0786-4c92-b0cc-4b4d87af9d76.png).
The back arrow is there just in case someone doesn't know that if they collapse the wallet back they get to the initial selection. 
Does that make sense? Thanks!

2022-10-14 12:18 UTC, exezbcz commented
also, the icons should be different. 
![image](https://user-images.githubusercontent.com/90852205/195842790-b58ef312-49c1-4c54-9268-39b2dd231f98.png)
The first frame is how its by default when you click on it. It Shows 3 wallets, and every box has the same size. When you click on one, the other disappears and your wallet selection is shown. Drop down = height of two wallet boxes. Like this: 
![image](https://user-images.githubusercontent.com/90852205/195844418-159a882c-497a-4523-a46d-7437759d9c51.png)
it's so that the outer box stays the same size.

2022-10-14 13:41 UTC, zhengow commented on components/common/WalletModal.vue
> +                  <b style="color: #ffffff">{{
@kkukelka thanks for your advice:)

2022-10-15 17:10 UTC, exezbcz commented
easy fix 
![image](https://user-images.githubusercontent.com/90852205/195999229-2877f6c3-20a9-4596-8aa2-2715ee72e9a3.png)

2022-10-16 16:53 UTC, yangwao commented
Let's push new dark mode @zhengow so we can close this one :)

2022-10-17 13:45 UTC, zhengow commented
> also, the icons should be different. ![image](https://user-images.githubusercontent.com/90852205/195842790-b58ef312-49c1-4c54-9268-39b2dd231f98.png) The first frame is how its by default when you click on it. It Shows 3 wallets, and every box has the same size. When you click on one, the other disappears and your wallet selection is shown. Drop down = height of two wallet boxes. Like this: ![image](https://user-images.githubusercontent.com/90852205/195844418-159a882c-497a-4523-a46d-7437759d9c51.png) it's so that the outer box stays the same size.

I am wonder what if user has only one address? What need to be fill for another three address?
![image](https://user-images.githubusercontent.com/38389586/196193449-44ea2c73-9297-4bcc-9fb8-6455b8a9534e.png)

2022-10-17 13:58 UTC, exezbcz commented
![image](https://user-images.githubusercontent.com/90852205/196196567-c1a60b99-7bcd-49fc-8242-f573eeb1fde9.png)
if more, the wallet section will be on a vertical scroll.

2022-10-17 14:16 UTC, exezbcz commented
yup, scroll on the section with wallets
> if more, the wallet section will be on a vertical scroll. 

![image](https://user-images.githubusercontent.com/90852205/196200774-902a1ba7-6b98-47ef-823e-1e543b0e3cf8.png)

2022-10-17 15:57 UTC, zhengow commented
already fix style as what you said.
pls check again:)

2022-10-18 10:08 UTC, yangwao commented
It seems that on connect dialogue has been broken in width. 

In dark mode, "X" is not there :)
![image](https://user-images.githubusercontent.com/5887929/196401221-6517dfd2-715a-4830-b1d6-4987e297aef4.png)

![image](https://user-images.githubusercontent.com/5887929/196401300-927356d2-e8ed-4724-9e25-3cb07dcdcee7.png)

2022-10-18 13:14 UTC, zhengow commented
> 

fix it:)

2022-10-18 14:00 UTC, merged

2022-10-18 14:00 UTC, yangwao commented
😍 Perfect, I’ve sent the payout 
💵 $100 @ 37.61 USD/KSM ~ 2.659 $KSM
🧗 [EgCzZLpVe7zg7RHh79qPyC8UrykVkA22YY2oj7sWMZf15Ws](https://kusama.subscan.io/account/EgCzZLpVe7zg7RHh79qPyC8UrykVkA22YY2oj7sWMZf15Ws)
🔗 [0xd99f0a4b3ebe722a32b2e9e4860ec185ebfb58a495eefcb6f1309241647b823d](https://kusama.subscan.io/extrinsic/0xd99f0a4b3ebe722a32b2e9e4860ec185ebfb58a495eefcb6f1309241647b823d)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

2022-10-18 14:01 UTC, yangwao commented
wfm, still have some missing stuff, but let's merge it and move on, we can then bring some smol adjustments or someone else will see some issue will raise it in issues, there is still some left overs

- #4090

2022-10-19 08:51 UTC, roiLeo commented
Hello! small notes with new design:
- no more change account button?
- disconnect is clearing `localStorage` so it will always ask for wallet authentification check
- how can I know wich extension is supported on kodadot since we hide the one that are not installed?
- mobile responsiveness & wallet selection are small:
![Screenshot 2022-10-19 at 10-38-30 KodaDot - Kusama NFT Market Explorer](https://user-images.githubusercontent.com/9987732/196641096-cae3616d-b509-4a93-a550-b30ba38420af.png)