#4271 adding change account button
kodadot/nft-gallery pull request #4272
Opened 2022-11-06 00:59 UTC by prachi00

**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [ ] Feature
- [ ] Refactoring

## PR Context?

- [ ] Closes #4271
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [ ] My contribution builds **clean without any errors or warnings**
- [ ] I've merged recent default branch -- **main** and I've no conflicts
- [ ] I've tried to respect high code quality standards
- [ ] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [ ] Fill up your KSM address: 
[Payout](https://beta.kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)

#### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
![Screen Shot 2022-11-05 at 5 58 56 PM](https://user-images.githubusercontent.com/39299315/200149101-23707198-164e-43f0-857b-44b5d69f967d.png)

2022-11-06 14:36 UTC, yangwao commented
@exezbcz I guess we can have much better design for this?

2022-11-07 04:40 UTC, prachi00 commented
![Screen Shot 2022-11-06 at 8 39 41 PM](https://user-images.githubusercontent.com/39299315/200227822-cd710c9e-3a92-46c7-a9ef-01e8af152dad.png)
@yangwao @exezbcz updated the btns according to format, for the rest (asset, balance, usd), I feel like it should be a new issue since it would include logical changes and should be handled in a new issue

2022-11-07 07:47 UTC, roiLeo requested changes
- "Change Account" btn is not working on mobile for me

2022-11-09 04:16 UTC, prachi00 commented
@roiLeo works now

2022-11-09 07:34 UTC, roiLeo reviewed
> works now

![Capture d’écran 2022-11-09 à 8 33 09 AM](https://user-images.githubusercontent.com/9987732/200766962-5cd82225-c3e1-491b-bd2a-4c4a93e0d121.png)

☹️

2022-11-09 13:26 UTC, roiLeo reviewed
small notes

2022-11-09 13:26 UTC, roiLeo commented on components/rmrk/Profile/NavbarProfileDropdown.vue
> +      </div>
I would change this code by something more simple

```suggestion
      <b-dropdown-item
        custom
        aria-role="menuitem">
        <div class="buttons is-justify-content-space-between my-2">
          <ConnectWalletButton
          label="general.change_account"
          class="navbar__sign-out-button menu-item is-size-7"
          @closeBurgerMenu="closeBurgerMenu" />
          <b-button
            class="navbar__sign-out-button menu-item is-size-7"
            @click="disconnect()">
            {{ $t('profileMenu.disconnect') }}
          </b-button>
        </div>
      </b-dropdown-item>
    </b-dropdown>
```

2022-11-09 13:26 UTC, roiLeo commented on components/rmrk/Profile/NavbarProfileDropdown.vue
> +  }
& remove this 
```suggestion
```

2022-11-09 13:26 UTC, roiLeo commented on styles/themes/_dark.scss
> +      background: $dark-accent!important;;
```suggestion
      background: $dark-accent!important;
```

2022-11-10 07:28 UTC, roiLeo approved these changes
✅ lgtm, let's finish #4222 too

2022-11-10 17:38 UTC, yangwao commented
pay 50

2022-11-10 17:38 UTC, merged

2022-11-10 17:38 UTC, yangwao commented
😍 Perfect, I’ve sent the payout 
💵 $50 @ 28.23 USD/KSM ~ 1.771 $KSM
🧗 [EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU](https://kusama.subscan.io/account/EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)
🔗 [0x51f3429868cdb605018bfd06886e8dd5bff71ae5dcee27766d6739694c49bcae](https://kusama.subscan.io/extrinsic/0x51f3429868cdb605018bfd06886e8dd5bff71ae5dcee27766d6739694c49bcae)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)