#4496 gallery card changes
kodadot/nft-gallery pull request #4511
Opened 2022-12-16 05:00 UTC by prachi00

**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

- [x] Closes #4496
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: 
[Payout](https://beta.kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
![Screen Shot 2022-12-15 at 8 59 03 PM](https://user-images.githubusercontent.com/39299315/208025792-957b11ee-eebf-408c-8221-8e1652f5dba5.png)
![Screen Shot 2022-12-15 at 8 59 13 PM](https://user-images.githubusercontent.com/39299315/208025813-3c6d445c-8c87-4804-88dc-65907d259b8a.png)

2022-12-16 08:16 UTC, roiLeo reviewed
Oh no.. CarouselCard, I find it misleading.
Can't we have a fresh `GalleryCard` component?

2022-12-16 16:49 UTC, prachi00 commented
> Oh no.. CarouselCard, I find it misleading.
> 
> Can't we have a fresh `GalleryCard` component?

Or can we rename carousel card and use it in both places? Since the ui and functionality is totally same

2022-12-16 17:02 UTC, roiLeo commented
> Or can we rename carousel card and use it in both places? Since the ui and functionality is totally same

if the design is exactly the same I'm not against, as long as we don't end up with special cases, I'm fine with it.
Or the best would be to to create GalleryCard component in histoire that will be used by carousel & explore layout.

2022-12-16 20:38 UTC, exezbcz commented
![image](https://user-images.githubusercontent.com/90852205/208184650-1644ecec-3ad7-4721-a177-93d9bc38aa99.png)
price should not be bold
- the hover on the nft name is for the hover card which isnt implemented yet #4340

2022-12-20 04:54 UTC, prachi00 commented
@roiLeo so I shifted the gallery card to histoire but I haven't used that yet for carousel, I feel like shifting carousel should be done in a new issue as there is some logical part for that, that might need some moving too 
so currently, carousel stays the same like before and the gallery one uses the new histoire component

2022-12-20 07:52 UTC, roiLeo requested changes
Hey! Why did you change the carousel code if the outcome is not affected?

### what needs to change in histoire component:
- use placeholder/fixed data
- don't use nuxt 
- don't use buefy helpers
- rename `NftCard` to `NeoCard`?

I don't see the point of `components/rmrk/Gallery/NftCard.vue` file you can directly import the component

2022-12-20 12:14 UTC, yangwao commented
@prachi00  Can we please move it outside of `rmrk` folder? 🥹

https://github.com/kodadot/nft-gallery/pull/4511/files#diff-bc15d2a15f1220c1ae5eaa62bb0d747486a1cee56b21204b5439c46d7dd2e0ec

2022-12-20 18:09 UTC, prachi00 commented
> 
 I just did the UI changes for the carousel card that should be according to the design

2022-12-21 05:47 UTC, prachi00 commented
@roiLeo by buefy helpers, do you mean buefy css classes? is-flex and all?

2022-12-21 07:44 UTC, roiLeo reviewed
> @roiLeo by buefy helpers, do you mean buefy css classes? is-flex and all?

Nvm since we use Bulma theme in histoire it's working.

> Also, using histoire newNftCard in a component that is not in vue compostion (gallery.vue) doesnt work, that is why I created a new composition component and used it there

lol, Nice move! I didn't knew that Gallery wasn't rewritten in Vue3 way.

- What's the difference between `NeoNftCard` & `NftCard`? if one of them is not used please delete it
- Could you please create story for each component you create?
- `components/rmrk/Gallery/NftCard.vue` stil inside `rmrk` folder

2022-12-21 08:01 UTC, prachi00 commented
> > @roiLeo by buefy helpers, do you mean buefy css classes? is-flex and all?
> 
> Nvm since we use Bulma theme in histoire it's working.
> 
> > Also, using histoire newNftCard in a component that is not in vue compostion (gallery.vue) doesnt work, that is why I created a new composition component and used it there
> 
> lol, Nice move! I didn't knew that Gallery wasn't rewritten in Vue3 way.
> 
> * What's the difference between `NeoNftCard` & `NftCard`? if one of them is not used please delete it
> * Could you please create story for each component you create?
> * `components/rmrk/Gallery/NftCard.vue` stil inside `rmrk` folder

so NftCard is in vue composition, so it is using NeoNftCard which gallery is not able to yet as it isnt in vue3, I guess we can remove NftCard once gallery is in vue3 and then directly use NeoNftCard in gallery

2022-12-21 08:05 UTC, roiLeo commented
> so NftCard is in vue composition...

I'm referring to `NeoNftCard` & `NftCard` component in histoire

2022-12-22 06:18 UTC, prachi00 commented
@roiLeo I added the story file, but I dont know how to see it, I ran story:dev 
But I dont see any of the components, its just loading forever
<img width="1467" alt="Screen Shot 2022-12-21 at 10 18 37 PM" src="https://user-images.githubusercontent.com/39299315/209069975-d11ab7bc-6289-42c7-9d37-44ef7110dd60.png">

2022-12-22 07:55 UTC, roiLeo commented on libs/ui/src/components/NeoNftCard/NeoNftCard.story.vue
> +      <NeoNftCard :nft="nft" prefix="'rmrk'" :show-price="true" />
```suggestion
      <NeoNftCard :nft="nft" prefix="rmrk" show-price />
```

2022-12-22 07:55 UTC, roiLeo commented on components/shared/gallery/NftCard.vue
> +  nft?: NFT
optional prop?
```suggestion
  nft: NFT
```

2022-12-22 07:55 UTC, roiLeo commented on libs/ui/src/components/NeoNftCard/NeoNftCard.vue
> +  nft?: NFT
same thing here
```suggestion
  nft: NFT
```

2022-12-22 07:55 UTC, roiLeo commented on libs/ui/src/components/NeoNftCard/NeoNftCard.vue
> +  nft?: NFT
ref #4544, missing `image`; `animationUrl`; `mimeType`; `collectionName`

2022-12-22 07:56 UTC, roiLeo approved these changes
✅ let's move on

2022-12-22 08:03 UTC, roiLeo commented
wfm too, might need to wrap Story in grid layout
![Screenshot 2022-12-22 at 09-02-22 NeoNftCard › Nft Card Histoire](https://user-images.githubusercontent.com/9987732/209086609-e48bcc3a-f816-46f5-a4e0-3e1edf4739cd.png)

2022-12-22 11:28 UTC, yangwao commented
pay 80 usd

2022-12-22 11:28 UTC, yangwao commented
😍 Perfect, I’ve sent the payout 
💵 $80 @ 24.65 USD/KSM ~ 3.245 $KSM
🧗 [EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU](https://kusama.subscan.io/account/EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)
🔗 [0x9ab254460bf51eabb19888b2e20f862217adcb795c02dcbf80e3f73ffd42ff58](https://kusama.subscan.io/extrinsic/0x9ab254460bf51eabb19888b2e20f862217adcb795c02dcbf80e3f73ffd42ff58)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

2022-12-22 11:29 UTC, merged