feat: integrate offer button
kodadot/nft-gallery pull request #4554
Opened 2022-12-23 09:43 UTC by preschian

**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [ ] Feature
- [ ] Refactoring
- [x] Redesign

## Context

- [x] Closes #4542

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [ ] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=<My_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address>)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

2022-12-23 10:00 UTC, roiLeo commented
> I need your help @roiLeo @Jarsen136. Does the offer button work on your side on this PR? I just followed the `submit()` function on `AvailableActions`. If not, What do I miss anyway?

wfm, block hash [0xa537886e39455a2d6e0cde1f96177433b5d4c65d996422f9abf0dc1431c6c9ad](https://polkadot.js.org/apps/#/explorer/query/0xa537886e39455a2d6e0cde1f96177433b5d4c65d996422f9abf0dc1431c6c9ad)  

it's been a few weeks that Snek [Rococo] endpoint is "stuck" but you can see that the call has been made on chain

2022-12-23 10:40 UTC, Jarsen136 commented
> I need your help @roiLeo @Jarsen136. Does the offer button work on your side on this PR? I just followed the `submit()` function on `AvailableActions`. If not, What do I miss anyway?

WFM too

2022-12-23 15:20 UTC, Jarsen136 commented on composables/useToast.ts
> +export default function useToast() {
It seems that this composables method was not being used anymore. Should we remove it ?

2022-12-23 16:40 UTC, yangwao commented
> Snek [Rococo] endpoint is "stuck"

After Brick I sense @vikiival updated only snek@05 for BSX, not for Rococo?

2022-12-23 16:58 UTC, vikiival commented
Looks like something is wrong with offers. I pinged BSX team

2023-01-01 21:31 UTC, yangwao commented
I've made offer on this one https://deploy-preview-4554--koda-nuxt.netlify.app/bsx/gallery/2608295324-7

But it seems on old one doesn't show up. 
![image](https://user-images.githubusercontent.com/5887929/210185070-102b77f2-b17d-4947-a927-da3647679ec5.png)

https://basilisk.subscan.io/extrinsic/2460385-2

![image](https://user-images.githubusercontent.com/5887929/210185061-1b33bb4e-6c49-4a45-9fa4-adbf64084034.png)

Oh, seems it's on Basilisk team side something ...

2023-01-11 12:28 UTC, vikiival commented
Offers should be already available

2023-01-11 12:43 UTC, roiLeo commented
> Offers should be already available

Tx is good but it's not visible for me on snek Rococo

2023-01-11 13:55 UTC, vikiival commented
> Tx is good but it's not visible for me on snek Rococo

Because the one that @yangwao made was on BSX

2023-01-12 08:53 UTC, roiLeo commented on composables/useTransaction.ts
> +export const useTransaction = () => {
```ts
  const transactionMap = (item: Actions, api: ApiPromise) => {
    return {
      [Interaction.LIST]: execTsxList(item as ActionList, api, executeTransaction),
      [Interaction.SEND]: execTsxSend(item as ActionSend, api, executeTransaction),
      [ShoppingActions.MAKE_OFFER]: execTsxOffer(item as ActionOffer, api, executeTransaction),
    }[item.interaction] || 'UNKNOW'
  }

  const transaction = async (item: Actions) => {
    const api = await apiInstance.value

    return transactionMap(item, api)
  }
```
no ts error lmk what you think

2023-01-12 09:39 UTC, roiLeo commented on composables/useTransaction.ts
> +export const useTransaction = () => {
nevermind I'll try to debug this

2023-01-12 09:41 UTC, roiLeo reviewed
On dark mode text is hard to see
![Screenshot 2023-01-12 at 10-29-50 KodaDot - Kusama NFT Market Explorer](https://user-images.githubusercontent.com/9987732/212031980-fca78d04-d5c9-4931-8e71-1d26c9b8afb2.png)

I've tested it on `/snek/gallery/659233203-7?redesign=true` and when I log `item` I find a wrong tokenId

```json
{
  "interaction": "MAKE_OFFER",
  "currentOwner": "bXhWeVLtArWauM8UmbaVdDmXmo5uSDk6DAa2YxQ5zbt2sDcbW",
  "day": 3,
  "price": ".1",
  "tokenId": "659233203-659233203-7",
  "urlPrefix": "snek",
  "successMessage": "Offer successfully created",
  "errorMessage": "Failed to send item"
}
```

2023-01-12 10:08 UTC, roiLeo commented on composables/useTransaction.ts
> +export const useTransaction = () => {
```ts
  const transactionMap = (item: Actions, api: ApiPromise) => {
    const map = {
      [Interaction.LIST]: (item, api) => execTsxList(item as ActionList, api, executeTransaction),
      [Interaction.SEND]: (item, api) => execTsxSend(item as ActionSend, api, executeTransaction),
      [ShoppingActions.MAKE_OFFER]: (item, api) => execTsxOffer(item as ActionOffer, api, executeTransaction)
    }

    return map[item.interaction]?.(item, api) ?? 'UNKNOW'
  }
```

or shorthand

```ts
  const transactionMap = (item: Actions, api: ApiPromise) =>
    ({
      [Interaction.LIST]: (item, api) =>
        execTsxList(item as ActionList, api, executeTransaction),
      [Interaction.SEND]: (item, api) =>
        execTsxSend(item as ActionSend, api, executeTransaction),
      [ShoppingActions.MAKE_OFFER]: (item, api) =>
        execTsxOffer(item as ActionOffer, api, executeTransaction),
    }[item.interaction]?.(item, api) ?? 'UNKNOW')
```

2023-01-12 10:23 UTC, roiLeo commented
✅ Block hash: 0xe77afe69d0712c73bfc45df5a9ac5300ba46d22bb05bf548bfd281ab24e76546 on Rococo

Still blocked by kodadot/snek#130

2023-01-12 11:20 UTC, Jarsen136 approved these changes
code lgtm

2023-01-12 14:26 UTC, vikiival commented
Merged

https://github.com/kodadot/snek/pull/136

2023-01-12 14:45 UTC, roiLeo commented
> Merged
> 
> [kodadot/snek#136](https://github.com/kodadot/snek/pull/136)

https://squiki.kodadot.workers.dev/status/snekk

new endpoint again??? (`https://squid.subsquid.io/snekk/graphql`)

2023-01-12 14:50 UTC, vikiival commented
> new endpoint again???

Following good practises 
https://docs.subsquid.io/deploy-squid/promote-to-production/

2023-01-12 15:07 UTC, roiLeo commented
Yeah!! offers are back
![Screenshot 2023-01-12 at 16-06-34 Golden Gate KodaDot - Kusama NFT Market Explorer](https://user-images.githubusercontent.com/9987732/212102674-97a8f158-8f97-4f30-aed0-8e4fd708b762.png)

2023-01-12 15:08 UTC, roiLeo approved these changes
✅ wfm 🚀

2023-01-12 15:37 UTC, vikiival requested changes
Smol

2023-01-12 15:37 UTC, vikiival commented on composables/transaction/transactionOffer.ts
> +export async function execTsxOffer(item: ActionOffer, api, executeTransaction) {
execTsxOffer

`exec{What}Tx` ?

```suggestion
export async function exectMakeOfferTx(item: ActionOffer, api, executeTransaction) {
```

2023-01-12 16:37 UTC, vikiival approved these changes
let it roll 🎲

2023-01-13 08:54 UTC, merged