🐛 show real image ratio in gallery redesign
kodadot/nft-gallery pull request #4649
Opened 2023-01-09 19:39 UTC by petersopko

**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #<issue_number>
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [x] I've tested it at </bsx/collection>
- [x] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=FNyt7T1xdbhN7dagf7yGYCRJuE3R45VmTCE3tjzy1rKxa7y)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
![image](https://user-images.githubusercontent.com/73316633/211393269-97048113-33c8-40c0-9ef9-a511a07b7740.png)
![image](https://user-images.githubusercontent.com/73316633/211393352-bb9e8931-8aef-40b1-ab16-e3b6c26a4d89.png)

2023-01-09 19:42 UTC, petersopko commented
@exezbcz, there isn't a design for wide images in Figma; how do we want to handle it? Is this way okay?

2023-01-09 20:28 UTC, exezbcz commented
for mobile it looks ok but on desktop it destroys the layout. I was thinking about making the img fit(width/height) to the rectangle. So we eliminate changing the layout. 
like this: 
![image](https://user-images.githubusercontent.com/90852205/211401749-297f7df8-2f27-4161-ac70-16f831d385bb.png)

Is that okay?

2023-01-10 09:00 UTC, petersopko commented
I didn't want to add the event listener, so it won't resize responsively (you need to refresh between mobile and desktop), but that's usually only possible with devtools or if somebody wants to make their screen super small. I think it's okay, but maybe @roiLeo can take a look.

Also, I don't know if artists creating full-width pictures will be happy to have those images fitted inside a square. 

![image](https://user-images.githubusercontent.com/73316633/211505432-45a8313a-de7f-4642-afb5-e1c69f3fcbca.png)
![image](https://user-images.githubusercontent.com/73316633/211505739-00fbf696-affe-47b9-997d-0dce151a6426.png)

2023-01-10 09:12 UTC, roiLeo reviewed
tested on `/rmrk/gallery/13528762-f091ff4a3f410ee872-ROXYNFT_FUN_BANNERS-FUN_BANNER_030-0000000000000030?redesign=true` 

With this change many items will now have "black square" frame, I'm not sure this is the best option

ex:
`/rmrk/gallery/10371533-b6c51bd8c8868edc70-6ML5P-KUSAMA_WONDERLAND_037_OR_OCCUPIED-0000000000000043?redesign=true`
![Screenshot 2023-01-10 at 10-10-03 KodaDot - Kusama NFT Market Explorer](https://user-images.githubusercontent.com/9987732/211509002-9e3560e6-d49c-48b3-9b87-34c0697048af.png)

or `/snek/gallery/185770742-2?redesign=true`

![Screenshot 2023-01-10 at 10-11-22 KodaDot - Kusama NFT Market Explorer](https://user-images.githubusercontent.com/9987732/211509409-4bdd236e-d199-4f56-88ba-6b82b9b37652.png)

2023-01-10 19:07 UTC, exezbcz commented
hmm, my bad. 

I thought that like 90% are square images and different ratios are quite rare. Not sure what is the best solution for this. 
Adding bars for the full widht img is not that bad but it does not work for imgs that are portrait oriented. 

Possible solution is add a full screen button to the top right button section? Then it would be ok if we scale-crop the art to gallery img box. 

Again, what are your thoughts? Also curious about the data, how many images are not square?

2023-01-11 09:50 UTC, roiLeo commented
> Possible solution is add a full screen button to the top right button section? Then it would be ok if we scale-crop the art to gallery img box.

In #4593 you've added it under the img box
Or we can add it in the top right like on OS

> Again, what are your thoughts? 

I would be in favour of removing the black stripes
First solution proposed by peter might be good, but we should still check if it doesn't disturb display of "square" images

> Also curious about the data, how many images are not square?

I don't think you can tell, but you have to assume that any image size can be added

2023-01-11 11:59 UTC, vikiival requested changes

2023-01-11 11:59 UTC, vikiival commented on libs/ui/src/components/MediaItem/type/ImageMedia.vue
> +</script>
missing new line

2023-01-11 11:59 UTC, vikiival commented on libs/ui/src/components/MediaItem/type/ImageMedia.vue
> +<style>
missing scoped or better targeting of image

2023-01-11 14:42 UTC, petersopko commented
> I would be in favour of removing the black stripes
First solution proposed by peter might be good, but we should still check if it doesn't disturb display of "square" images

So are we going with this version? Can somebody confirm what should the final outcome here look like?

2023-01-11 16:00 UTC, exezbcz commented
> > Possible solution is add a full screen button to the top right button section? Then it would be ok if we scale-crop the art to gallery img box.
> 
> In #4593 you've added it under the img box Or we can add it in the top right like on OS
>
yup, that was only quick idea and i posted it. Nothing rock solid imo :D  
> > Again, what are your thoughts?
> 
> I would be in favour of removing the black stripes First solution proposed by peter might be good, but we should still check if it doesn't disturb display of "square" images
> 
Well, its not that bad removing the stripes, not against it. What if we add the fullscreen button before production release? 
I might be wrong, but i think the entire nft experience is still tailored to squares. Possible adding "art" view in the future? Will switch your layout and make the nft fit top part without cropping.
> > Also curious about the data, how many images are not square?
> 
> I don't think you can tell, but you have to assume that any image size can be added

yup


Sooo, lets handle it like on the nft cards?

2023-01-13 15:02 UTC, petersopko commented
> So are we going with this version? Can somebody confirm what should the final outcome here look like? 

I'm sorry if I'm misunderstanding here, but can somebody tell me what should be done here to finish up? 

I don't want to stall, but I didn't get the sense the discussion was over.

2023-01-13 15:39 UTC, roiLeo commented
> > So are we going with this version? Can somebody confirm what should the final outcome here look like?
> 
> I'm sorry if I'm misunderstanding here, but can somebody tell me what should be done here to finish up?
> 
> I don't want to stall, but I didn't get the sense the discussion was over.

**before**
![Screenshot 2023-01-13 at 16-32-57 KodaDot - Kusama NFT Market Explorer](https://user-images.githubusercontent.com/9987732/212358573-27d991fe-c9e8-4379-baf0-cb15d5f2e244.png)

**after**
![Screenshot 2023-01-13 at 16-32-41 KodaDot - Kusama NFT Market Explorer](https://user-images.githubusercontent.com/9987732/212358525-5fa1e0d6-3f03-4489-a0bb-797903b81552.png)

if it's ok for @exezbcz it's ok for me but you still got some small code changes request

2023-01-13 16:47 UTC, petersopko commented
updated 👍🏻

2023-01-16 08:36 UTC, roiLeo approved these changes
✅ code lgtm

2023-01-16 08:36 UTC, roiLeo commented on libs/ui/src/components/MediaItem/type/ImageMedia.vue
> +    :class="[!original && !isMobile ? 'is-square image' : '']">
```suggestion
    :class="{ 'is-square image': !original && !isMobile }">
```

2023-01-16 12:14 UTC, vikiival approved these changes

2023-01-17 12:58 UTC, vikiival commented
pay 40 usd

2023-01-17 12:58 UTC, merged

2023-01-18 06:48 UTC, petersopko commented
>  🔗 [0x92ba0920a80f39c39c1d9a655e0e7badb10adce4e06e78af9672dcb3478ab211](https://kusama.subscan.io/extrinsic/0x92ba0920a80f39c39c1d9a655e0e7badb10adce4e06e78af9672dcb3478ab211)

👀

2023-01-18 08:16 UTC, vikiival commented
Mr @yangwao was notified

2023-01-18 09:51 UTC, yangwao commented
me & my few notifications

<img src="https://media2.giphy.com/media/nmE8YkDIaB1OE/giphy.gif"/>

yup registered, will proceed

![image](https://user-images.githubusercontent.com/5887929/213139327-a385c4fd-bebf-458e-9e68-60b9c8aeb408.png)

2023-01-18 12:09 UTC, yangwao commented
pay 40