fix(profile): show first nft image as metadata (#465)
kodadot/nft-gallery pull request #489
Opened 2021-06-22 07:05 UTC by roiLeo

![Capture d’écran 2021-06-22 à 9 02 40 AM](https://user-images.githubusercontent.com/9987732/122878989-a84a4100-d338-11eb-96eb-f477e516c15b.png)

2021-06-22 07:13 UTC, yangwao commented
Seems doesn't work in tg or Twitter 👀
![IMG_20210622_091158](https://user-images.githubusercontent.com/5887929/122880159-fe6bb400-d339-11eb-94e3-c38866e76f76.jpg)
![IMG_20210622_091217](https://user-images.githubusercontent.com/5887929/122880153-fc095a00-d339-11eb-8078-68b1e295369d.jpg)

2021-06-22 07:59 UTC, yangwao requested changes
you need to rename that default file as you mentioned hash bundle there

2021-06-22 07:59 UTC, yangwao commented on src/views/Profile.vue
> +    return `${url.protocol}${url.hostname}/img/kodadot_logo_v1_transparent_400px.56bb186b.png`;
`.56bb186b.` in file name is probably just bundle hash, you want to remove it :)

2021-06-22 09:13 UTC, yangwao commented
Still doesn't render... 
Maybe try to add these, I sense it's conditional for that
`twitter:title`
`og:title`

2021-06-22 09:17 UTC, roiLeo commented
I think the card is not showing because we don't provide 'description' and 'title' for twitter and open graph. 
I will try to set with some data. Should I rely on the first nft ?

2021-06-22 09:18 UTC, yangwao commented
Okay, that would be awesome, yes try that one.
Meanwhile I'm testing it on other PR til lit build with some generic ones https://github.com/kodadot/nft-gallery/pull/493
Will know in few seconds :)

2021-06-22 09:20 UTC, yangwao commented
Oh hint, to mitigate cache, it's fine to add some parameter, like ?abc to end of URL while testing rendering on crawlers, as some cache it hard, even for 3days+

2021-06-22 09:21 UTC, yangwao commented
This one seems working tho! 
https://deploy-preview-493--nftkodadot.netlify.app/rmrk/u/CxQJNQeowRUJBgUHQpspudWy4BU6Rk2u93yDZEKe6GzcLDe?abd

![image](https://user-images.githubusercontent.com/5887929/122899293-fe74af80-d34b-11eb-9a0f-b0c34b98c23a.png)

2021-06-22 11:58 UTC, yangwao commented
Well now is the question, why doesn't fetch at least the default picture if I don't see any other? 
![image](https://user-images.githubusercontent.com/5887929/122920654-e9a31680-d361-11eb-8ca9-7ac52ef83632.png)

2021-06-22 14:37 UTC, roiLeo commented
My SEO plugin show the right picture and description but on twitter card it show the default data and I don't know why. 
![Capture d’écran 2021-06-22 à 4 34 03 PM](https://user-images.githubusercontent.com/9987732/122944039-c84d2500-d377-11eb-8bf4-1acc7cdb029c.png)
![Screenshot 2021-06-22 at 16-36-59 Card Validator Twitter Developers](https://user-images.githubusercontent.com/9987732/122944439-1eba6380-d378-11eb-91a8-67bcaedb84a3.png)

2021-06-23 07:55 UTC, yangwao commented
I mean, let's push it to production.
You are welcome to show on our discord https://discord.gg/35hzy2dXXh
Let's reach me there, @yangwao , so I can process some small bounty for your work :)
You will need to have KSM address

2021-06-23 07:56 UTC, yangwao commented
For now, I'll merge it as it's at least something and you're welcome to continue cracking why doesn't work:)

2021-06-23 07:56 UTC, merged