fix: explorer input leftovers
kodadot/nft-gallery pull request #4940
Opened 2023-02-07 18:04 UTC by maderi21

**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #4930 
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [x]  I've tested it at </bsx/collection>
- [x] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=JHJGu2aWyAFBfcso8bR7ma82p15YAavyN6vQfJyWuhniNGa)

#### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
![image](https://user-images.githubusercontent.com/102800574/217328457-6e96ce8d-9bdb-4416-a7f8-b51e035b5fab.png)

2023-02-07 18:06 UTC, maderi21 commented
the `fill="currentColor"` doesn't seem to be working when svg is imported as image. there are also some weird borders around the min/max inputs in dark mode which weren't described in the issue but I can't get rid of them.

regarding payment, same comment as 
- https://github.com/kodadot/nft-gallery/pull/4935#issuecomment-1420666389

2023-02-08 07:36 UTC, roiLeo approved these changes
Noice!
✅ code lgtm & wfm

2023-02-08 07:48 UTC, Jarsen136 requested changes
otherwise code lgtm

2023-02-08 07:48 UTC, Jarsen136 commented on components/explore/SidebarFilter.vue
> -            <img src="/arrow-right.svg" />
Let's also delete the svg file.

2023-02-08 18:01 UTC, maderi21 commented on components/explore/SidebarFilter.vue
> -            <img src="/arrow-right.svg" />
arrow svg deleted

2023-02-08 19:38 UTC, exezbcz commented
I will create follow up issue for the logic.

2023-02-09 02:01 UTC, Jarsen136 approved these changes

2023-02-09 22:01 UTC, vikiival commented
pay 30 usd

2023-02-09 22:01 UTC, yangwao commented
😍 Perfect, I’ve sent the payout 
💵 $30 @ 33.37 USD/KSM ~ 0.899 $KSM
🧗 [JHJGu2aWyAFBfcso8bR7ma82p15YAavyN6vQfJyWuhniNGa](https://kusama.subscan.io/account/JHJGu2aWyAFBfcso8bR7ma82p15YAavyN6vQfJyWuhniNGa)
🔗 [0x0c27cc6ac4e9b95c6c08f01e3a68c7a097569d231cdface961b440ebe659b7b5](https://kusama.subscan.io/extrinsic/0x0c27cc6ac4e9b95c6c08f01e3a68c7a097569d231cdface961b440ebe659b7b5)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

2023-02-10 01:56 UTC, merged