fix: 4950 price fltr on active k-blue
kodadot/nft-gallery pull request #4960
Opened 2023-02-10 06:40 UTC by maderi21

**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #4950
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [x] I've tested it at </bsx/collection>
- [x] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=JHJGu2aWyAFBfcso8bR7ma82p15YAavyN6vQfJyWuhniNGa)

#### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
![image](https://user-images.githubusercontent.com/102800574/218020570-a9e715bb-2c96-43bb-858a-4b0fd71f5e27.png)

2023-02-10 12:08 UTC, Jarsen136 requested changes

2023-02-10 12:08 UTC, Jarsen136 commented on components/explore/SidebarFilter.vue
> +  return false
what if `min` is zero? It would also return false

2023-02-10 13:18 UTC, exezbcz commented
hi! 

## Feedback
### Disabled button
- should not have drop shadow
![image](https://user-images.githubusercontent.com/90852205/218099832-4d89e570-153e-42b8-ae3b-94f3325309ae.png)
- disabled state should not be white
- active state is pink (k-accent) also on the picture (light/dark mode) 
![image](https://user-images.githubusercontent.com/90852205/218101262-5fbf3b3f-b578-4017-95c2-5a3e8b432a81.png)

figma for this: 
https://www.figma.com/file/OwAEyE0QDPn3tHXZbyot1o/Explore-v0.9?node-id=0%3A1&t=Q0EhchN7FTbyJNxY-1

### Input
Next thing is the logic. Something is wrong there, can you have a look please?

2023-02-10 13:50 UTC, maderi21 commented
- @Jarsen136 @preschian fixed the logic
- @exezbcz fixed the styling

2023-02-10 14:17 UTC, Jarsen136 reviewed
I guess we do not have to input the 0 to `MIN` , if we would like to search something is cheaper than the MAX price. I would like the apply button to be avaliable.

<img width="289" alt="image" src="https://user-images.githubusercontent.com/31397967/218112560-1f1aa161-6050-4b31-bb7b-3c585841a3c6.png">
The same case about MAX input
<img width="270" alt="image" src="https://user-images.githubusercontent.com/31397967/218113840-c0bdff67-233d-4e12-852b-986581509244.png">


This is the filter on the Opensea.
<img width="386" alt="image" src="https://user-images.githubusercontent.com/31397967/218113625-213d3ce0-3ee4-4cfe-8a6a-e3ffdb8d6f7b.png">

2023-02-10 14:17 UTC, Jarsen136 commented on components/explore/SidebarFilter.vue
> +const isInputFocused = (): void => {
```suggestion
const toggleInputFocused = (): void => {
```

2023-02-11 07:14 UTC, maderi21 commented on components/explore/SidebarFilter.vue
> +const isInputFocused = (): void => {
done

2023-02-11 07:15 UTC, maderi21 commented
> I guess we do not have to input the 0 to `MIN` , if we would like to search something is cheaper than the MAX price. I would like the apply button to be avaliable.
> 
> <img alt="image" width="289" src="https://user-images.githubusercontent.com/31397967/218112560-1f1aa161-6050-4b31-bb7b-3c585841a3c6.png">
> 
> The same case about MAX input
> <img alt="image" width="270" src="https://user-images.githubusercontent.com/31397967/218113840-c0bdff67-233d-4e12-852b-986581509244.png">
> 
> This is the filter on the Opensea. <img alt="image" width="386" src="https://user-images.githubusercontent.com/31397967/218113625-213d3ce0-3ee4-4cfe-8a6a-e3ffdb8d6f7b.png">

added this option 👍

2023-02-11 13:37 UTC, Jarsen136 approved these changes
WFM

2023-02-12 18:44 UTC, yangwao commented
pay 40 usd

2023-02-12 18:44 UTC, merged

2023-02-12 18:44 UTC, yangwao commented
😍 Perfect, I’ve sent the payout 
💵 $40 @ 33.23 USD/KSM ~ 1.204 $KSM
🧗 [JHJGu2aWyAFBfcso8bR7ma82p15YAavyN6vQfJyWuhniNGa](https://kusama.subscan.io/account/JHJGu2aWyAFBfcso8bR7ma82p15YAavyN6vQfJyWuhniNGa)
🔗 [0xa36f1a7111b44c56a147b741e48e69f51c22c49053cb03e980ac953f8385c48a](https://kusama.subscan.io/extrinsic/0xa36f1a7111b44c56a147b741e48e69f51c22c49053cb03e980ac953f8385c48a)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)