fix: 5005 carousel 3 steps post fixes
kodadot/nft-gallery pull request #5010
Opened 2023-02-14 18:39 UTC by maderi21

**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #5005, Closes #5007
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [x] I've tested it at </bsx/collection>
- [x] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=JHJGu2aWyAFBfcso8bR7ma82p15YAavyN6vQfJyWuhniNGa)

#### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
![image](https://user-images.githubusercontent.com/102800574/218827352-37b9f5a7-0dd8-438d-9b40-531060c09946.png)

2023-02-14 18:59 UTC, exezbcz commented
nice! can you please make the transition even faster, something like 2x

2023-02-14 19:54 UTC, exezbcz commented
> 

sorry for the perfectionism, 0.2 would be perfect I think :D

2023-02-14 20:06 UTC, maderi21 commented
> > 
> 
> sorry for the perfectionism, 0.2 would be perfect I think :D

increased to 0.2

2023-02-15 01:52 UTC, Jarsen136 commented on components/carousel/CarouselTypeNewestList.vue
> +    :link-text="`${$t('helper.seeMore')}`" />
```suggestion
    :link-text="$t('helper.seeMore')" />
```

2023-02-15 08:41 UTC, Jarsen136 approved these changes
code lgtm

2023-02-16 18:30 UTC, yangwao commented
> Increase the number of items on carousels; we were thinking about 30

Let's put it on landing too 30 items for newest list and sales :)

https://user-images.githubusercontent.com/5887929/219455694-61d6fbfc-6fd1-4e1d-b9bf-72bdbd266adc.mov

2023-02-16 18:38 UTC, yangwao commented
It seems Visited NFTs still has 10 item history too? Let's extend it to 30 :)

https://user-images.githubusercontent.com/5887929/219457141-0672cf24-f289-4506-ae02-d53350e0468d.mov

2023-02-16 18:41 UTC, vikiival requested changes

2023-02-16 18:42 UTC, vikiival commented
Please do not overfetch subsquid

2023-02-17 06:28 UTC, maderi21 commented
> Increase the number of items on carousels; we were thinking about 30

didn't know this means everywhere, sorry. increased carousel fetching as follows:

landing: 
- newest 30
- latest sales 30

gallery item:
- more from collection 60
- visited 30

> Please do not overfetch subsquid

I don't know if this isn't happening now,

2023-02-17 09:57 UTC, yangwao commented
> I don't know if this isn't happening now,

it's ok, we've talked that 60 items is not that bad, yet having resolver would be better to not overload subsquid. can be solved later if we hit performance issues on that. 

testing it, seems works well everywhere, perfect!

pay 60

2023-02-17 09:57 UTC, merged

2023-02-17 09:57 UTC, yangwao commented
😍 Perfect, I’ve sent the payout 
💵 $60 @ 39.54 USD/KSM ~ 1.517 $KSM
🧗 [JHJGu2aWyAFBfcso8bR7ma82p15YAavyN6vQfJyWuhniNGa](https://kusama.subscan.io/account/JHJGu2aWyAFBfcso8bR7ma82p15YAavyN6vQfJyWuhniNGa)
🔗 [0xa856cf35b78911cbbff6b14c26614f03ad900e0ffd23a6ae60ea62dcc06fe6d5](https://kusama.subscan.io/extrinsic/0xa856cf35b78911cbbff6b14c26614f03ad900e0ffd23a6ae60ea62dcc06fe6d5)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)