:tada: RMRK 2.0 beta
kodadot/nft-gallery pull request #5028
Opened 2023-02-16 15:15 UTC by vikiival

- :arrow_up: @kodadot1/vuex-options
- :zap: enable RMRK2
- :arrow_up: @kodadot1/vuex-options
- :wrench: rmrk2 config
- :arrow_up: @kodadot1/vuex-options
- :tada: RMRK2

**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

- [ ] Closes #<issue_number>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

2023-02-16 15:33 UTC, Jarsen136 requested changes

2023-02-16 15:33 UTC, Jarsen136 commented on pages/rmrk2/index.vue
> +      this.$consola.log('Not Moonriver')
👀 

<img width="1586" alt="image" src="https://user-images.githubusercontent.com/31397967/219412492-5287eff2-4d3a-47ed-91c5-6fc657ac8518.png">

2023-02-16 15:35 UTC, roiLeo reviewed
doesn't work for me
![Screenshot 2023-02-16 at 16-31-26 KodaDot - NFT Market Explorer](https://user-images.githubusercontent.com/9987732/219412400-dc395823-a2cd-4d3f-9665-9f7ecf1a2f6d.png)

Some nftEntity name are `null`
collectionEntities name are `null` too

2023-02-16 15:35 UTC, roiLeo commented on pages/rmrk2/index.vue
> +    }
```suggestion
    if (prefix !== 'rmrk2') {
      this.$consola.log('Not RMRK2')
      store.dispatch('setUrlPrefix', 'rmrk2')
    }
```

2023-02-16 17:00 UTC, vikiival commented
> 
> Some nftEntity name are `null`
> 
> collectionEntities name are `null` too
> 
> 

Yes, infura had some outage while indexing. 

See kodadot/workers#32

2023-02-16 17:27 UTC, yangwao commented
> infura had some outage while indexing.

https://status.infura.io/ seems only for Polygon today?

can we switch to Pinata for indexer as we have there 100k req which should sufficient for indexing I guess?

<img width="266" alt="image" src="https://user-images.githubusercontent.com/5887929/219441981-56d1a354-2d7f-4fd0-88d5-a5fddecb8e07.png">

2023-02-16 17:35 UTC, yangwao commented
fleek, cf-ipfs or someone from this list? https://ipfs.github.io/public-gateway-checker/

2023-02-16 17:42 UTC, yangwao commented
ok, for indexing we might have ipfs gateway, seems it's infura costs are $200 for what we've been paying at pinata $1k, but with r2 even lower, let's see

2023-02-17 01:28 UTC, Jarsen136 approved these changes

2023-02-17 09:36 UTC, yangwao commented
seems it's working... partially? 
- https://deploy-preview-5028--koda-nuxt.netlify.app/rmrk2/gallery/15517161-90c6619c6b94fcfd34-EVRLOOT_RESOURCES-WATER-11?page=1

![image](https://user-images.githubusercontent.com/5887929/219608033-8de22842-4153-49dc-b1d1-4a888bfa568b.png)

2023-02-17 09:37 UTC, yangwao commented
I think we will have issues with numbers, not sure if they are right? 
https://deploy-preview-5028--koda-nuxt.netlify.app/rmrk2/collection/90c6619c6b94fcfd34-EVRLOOT_RESOURCES?page=1

![image](https://user-images.githubusercontent.com/5887929/219608262-88fcfcec-1c27-4e1c-9bf1-aa4febdf189f.png)

2023-02-17 09:41 UTC, yangwao commented
Different currencies on cards

![image](https://user-images.githubusercontent.com/5887929/219609071-19f31b3f-0d4e-4d7b-9984-a1545e650ee2.png)

2023-02-17 09:42 UTC, yangwao commented
seems stil syncing
- https://squiki.kodadot.workers.dev/status/rubick

```json
"name": "009-rc0",
"squidName": "rubick",
"status": "SYNCING",
"syncStatus": {
"totalBlocks": 16673334,
"currentBlock": 15517829
```

2023-02-17 09:53 UTC, yangwao commented
Ok, my proposal would be to merge it partially it's working and there needs to be done lot of fixes beyond this PR 

- #3725

2023-02-17 11:28 UTC, vikiival commented
>  or hit our image-workers? I think it better to hit our image-workers

using minipfs

https://github.com/kodadot/rubick/blob/zlozenec/src/mappings/utils/metadata.ts

2023-02-19 19:43 UTC, yangwao commented
Let's push it on beta :)

2023-02-20 18:19 UTC, yangwao commented
now?

2023-02-20 19:05 UTC, merged