feat: item list on new collection page
kodadot/nft-gallery pull request #5039
Opened 2023-02-18 06:30 UTC by preschian

**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

## Context

- [x] refactor gallery list to item list
- [x] show item list on new collection page
- [x] infinite scroll still not perfect, related to this https://github.com/kodadot/nft-gallery/issues/4952
- [x] closes https://github.com/kodadot/nft-gallery/issues/5023

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [ ] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=<My_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address>)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

<img width="2032" alt="Screenshot 2023-02-18 at 13 28 41" src="https://user-images.githubusercontent.com/734428/219845326-f32cbf86-4c2d-478d-b340-81ec1c2823e1.png">

2023-02-20 08:14 UTC, roiLeo reviewed
maybe we should export some composable from `useItemsGrid`, I think we'll need to reuse `useSearchParams` in profile page & collection

2023-02-20 08:14 UTC, roiLeo commented on components/items/Items.vue
> +<style scoped></style>
I don't think it's necessary

2023-02-20 08:14 UTC, roiLeo commented on components/explore/ExploreTabItem.vue
> +          <span>Items</span>
```suggestion
          <span>{{ $t('items') }}</span>
```

2023-02-20 08:14 UTC, roiLeo commented on components/explore/ExploreTabItem.vue
> +          <span>Activity</span>
```suggestion
          <span>{{ $t('tabs.activity') }}</span>
```

2023-02-20 14:22 UTC, roiLeo commented on components/items/Items.vue
> +<style scoped></style>
(I was referring to components import)

2023-02-20 14:29 UTC, vikiival commented on components/items/ItemsGrid/ItemsGridImage.vue
> +})
subsquid

2023-02-21 15:42 UTC, roiLeo approved these changes
looks good

2023-02-23 06:54 UTC, exezbcz commented
<img width="1467" alt="image" src="https://user-images.githubusercontent.com/90852205/220837944-4a9077c0-3e35-4a19-9e81-2b5d66852c30.png">
It looks weird on my end. 
otherwise oki

2023-02-23 15:03 UTC, exezbcz commented
something is still wrong, is this related to the cards having different height? (afaik there is an issue for this)  
![image](https://user-images.githubusercontent.com/90852205/220944737-1c76810c-296b-42a9-a6e0-29629dd29f8d.png)

link: https://deploy-preview-5039--koda-nuxt.netlify.app/bsx/collection/1299595206?page=2&redesign=true

2023-02-23 15:11 UTC, roiLeo commented
> I will check in separate PR 👍 thanks for the link

We already has this issue fix is to wrap card content with `container` class

ref #4935

2023-02-23 15:14 UTC, roiLeo commented
Why do we have a full-width layout here compared to explore layout?
We need to unify user experience

2023-02-23 15:30 UTC, roiLeo commented
> waiting for this decision actually #4857 should I put wrapper for now?

For now I would just copy same layout as we use currently on explore page.
#4857 fix might come later since we could have potential side effects (didn't test responsive)

2023-02-24 11:28 UTC, Jarsen136 commented
> Complexity	4

I just wonder if we could manage to reduce it

2023-02-24 11:29 UTC, Jarsen136 approved these changes

2023-02-24 12:37 UTC, daiagi requested changes

2023-02-24 12:37 UTC, daiagi commented on components/items/ItemsGrid/ItemsGrid.vue
> +    <p>total: {{ total }}</p>
missing translation for 'total'

2023-02-24 13:26 UTC, exezbcz commented
@preschian apart from this issue I think everything seems to be fine 
https://github.com/kodadot/nft-gallery/pull/5039#issuecomment-1441941344

2023-02-27 11:05 UTC, daiagi approved these changes

2023-02-27 11:18 UTC, merged