[Feedback request] 🔧 container is-fluid
kodadot/nft-gallery pull request #5089
Opened 2023-02-22 08:25 UTC by roiLeo

This is for testing purposes only 🧪 
ping @exezbcz 

## Context

- [x] ref #4857
- [x] container size for Navbar
- [x] container size for /explore pages

## Preview

https://deploy-preview-5089--koda-nuxt.netlify.app/bsx/explore/collectibles

2023-02-22 18:20 UTC, yangwao commented
actually, when netlify first pick ups PR and you move it to draft, when new commit event is emitted, it builds it anyway even in draft...

2023-02-26 12:02 UTC, vikiival commented
Please make this as draft

2023-03-06 11:56 UTC, vikiival commented
👀 can I close?

2023-03-06 12:03 UTC, roiLeo commented
> 👀 can I close?

I'm waiting for @exezbcz feedback to push changes

2023-03-06 15:32 UTC, exezbcz commented
@roiLeo hmm, it's better but still its something missing 
- I am also not completely sure what it does, the margins are now flexible or? 
- I can see that on bigger screens the content is stretching now - There is no dynamic grid yet so the collection cards are for example stretched. 
- but for example on 1240px the margins are looking worse than on current beta.
- there seems to be another 32px padding added
![image](https://user-images.githubusercontent.com/90852205/223154797-26a0a3c3-723e-484c-91f3-78852f913a8e.png)

the objective was to lower the margins on certain screens, or best, make it unified for desktop and mobile, mobile has fixed 20px afaik. 

do I understand this correctly? Correct me please if I am wrong :D

2023-03-06 16:03 UTC, roiLeo commented
> I am also not completely sure what it does, the margins are now flexible or?
> I can see that on bigger screens the content is stretching now 

we can set fixed margin (left & right) for container, on this preview it's set as 32px and content will fulfill container

> There is no dynamic grid yet so the collection cards are for example stretched.

not related but we can rework resizing of collections cards

> but for example on 1240px the margins are looking worse than on current beta.

Looks oki?
![Capture d’écran 2023-03-06 à 4 49 33 PM](https://user-images.githubusercontent.com/9987732/223160743-71820749-9792-450c-ab53-7f474181278d.png)

> there seems to be another 32px padding added

This will be default padding (can be changed) between the content and the edge of the window

2023-03-07 14:45 UTC, exezbcz commented
@roiLeo yup, that is better now. 
I think something like 40px margin for desktop would be good, and then 20px for specific lower breakpoints - 1024?

2023-03-09 11:35 UTC, vikiival commented
cc @exezbcz need your visual 👁️ 👁️ 👁️

2023-03-09 11:35 UTC, vikiival commented on styles/global.scss
> +  padding-left: 40px;
maybe use `rem` instead of `px`?

2023-03-09 11:36 UTC, vikiival commented on styles/global.scss
> +  .container.is-fluid {
likewise

2023-03-09 11:36 UTC, vikiival requested changes
Smol

2023-03-10 10:24 UTC, exezbcz commented
yup, its okay, but its not working on landing page - is that expected? 

and with bigger items on explore - but that would be fixed individually no? 
<img width="1461" alt="image" src="https://user-images.githubusercontent.com/90852205/224291560-56d5abd3-65e8-4a48-9f2b-db596e6b901a.png">

2023-03-10 14:10 UTC, roiLeo commented
> yup, its okay, but its not working on landing page - is that expected?

Now should be testable on landing page

> and with bigger items on explore - but that would be fixed individually no? 

yeah we could change fixed width to make it more responsive

2023-03-10 15:06 UTC, exezbcz commented
@roiLeo it definitely makes sense for collection page and for explore page 
- We should apply it to the rest so its consistent, wdyt?

2023-03-10 15:08 UTC, roiLeo commented
> We should apply it to the rest so its consistent, wdyt?

Yes! Note that we will keep some pages at half size layout (teleport, create..) for now

2023-03-10 15:10 UTC, exezbcz commented
@roiLeo yup, It makes no sense making teleport full width, maybe once it is portfolio page? 👀 

Thank you for the changes!

2023-03-10 15:56 UTC, exezbcz commented
looking good! We will need to change the carousel on landing but otherwise solid.

2023-03-11 09:27 UTC, yangwao commented
mergeable? would be nice to push it out for release

2023-03-11 09:27 UTC, vikiival approved these changes

2023-03-11 09:28 UTC, merged

2023-03-11 09:28 UTC, vikiival commented
pay 50 usd

2023-03-11 09:45 UTC, roiLeo commented
I didnt had Time to test it on a large screen :/. How does it look ?