#5209 activity tab
kodadot/nft-gallery pull request #5224
Opened 2023-03-10 04:05 UTC by prachi00

**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [ ] Closes #5209
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [ ] My contribution builds **clean without any errors or warnings**
- [ ] I've merged recent default branch -- **main** and I've no conflicts
- [ ] I've tried to respect high code quality standards
- [ ] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [ ] Fill up your KSM address: 
[Payout](https://beta.kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)

#### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
<img width="813" alt="Screen Shot 2023-03-09 at 7 49 30 PM" src="https://user-images.githubusercontent.com/39299315/224220628-4976e1e7-5258-48b8-91d0-116c2015d29f.png">

2023-03-10 09:51 UTC, daiagi requested changes
minor changes

overall wfm

2023-03-10 09:51 UTC, daiagi commented on components/gallery/GalleryItemTabsPanel/GalleryItemActivity.vue
> +    column-gap: 1.5rem;
I think the columm-gap is too large compare with the design
![image](https://user-images.githubusercontent.com/22791238/224277437-1e651e8f-5541-4a76-8982-844b4aa3be37.png)

2023-03-10 09:51 UTC, daiagi commented on components/gallery/GalleryItemTabsPanel/GalleryItemActivity.vue
> +          class="events-checkbox is-flex is-align-items-center"
```suggestion
class="is-clickable is-capitalized is-flex is-align-items-center"
```

same goes for other uses of events-checkbox class

2023-03-10 09:51 UTC, daiagi commented on components/gallery/GalleryItemTabsPanel/GalleryItemActivityTable.vue
> +          <span class="date-column">{{
```suggestion
<span class="no-wrap">
```

2023-03-10 09:51 UTC, daiagi commented on components/gallery/GalleryItemTabsPanel/GalleryItemActivityTable.vue
> +}
can be removed and uses replaced by class="no-wrap"

2023-03-10 10:17 UTC, exezbcz commented
the button does not work on the full width and height - please make the select are the whole button. 

<img width="101" alt="image" src="https://user-images.githubusercontent.com/90852205/224288557-c9b7ffbf-1940-4aba-a729-4d38ab49107b.png">

if the name is too long we can I think cut it so its not jumping to the second row - that is the ideal situation that no content is jumping to second row 

can we also increase the vertical padding? something like 20 is good - between the buttons and the stroke. 
<img width="88" alt="image" src="https://user-images.githubusercontent.com/90852205/224290312-e38f4dea-9790-4222-9ea0-51c2bebc64d6.png">

2023-03-12 00:12 UTC, prachi00 commented
Left:

- [ ] if the name is too long we can I think cut it so its not jumping to the second row (somewhere on the edge with the second name

can this be done in another issue? bit tricky to change the class in oruga table as this is deeply nested and would be through unscoped css

2023-03-12 07:34 UTC, daiagi commented on components/gallery/GalleryItemTabsPanel/GalleryItemActivity.vue
> +          <span :for="name" class="is-clickable">
```suggestion
          <span :for="name">
```

it works without it:

![image](https://user-images.githubusercontent.com/22791238/224530868-1c4eeb8a-8bc5-41c4-8dd3-8b416acda083.png)

2023-03-14 02:58 UTC, prachi00 commented
> 

fixed for div, for label , it seems is-clickable is mandatory as even if we wrap it in a , the label tag inside it still wont show pointer without is-clickable

2023-03-14 06:36 UTC, exezbcz commented
good! works for me

2023-03-15 09:46 UTC, roiLeo commented on components/gallery/GalleryItemTabsPanel/GalleryItemActivity.vue
> +    <div class="events px-5 py-5 is-flex is-flex-direction-column">
```suggestion
    <div class="events p-5 is-flex is-flex-direction-column">
```

2023-03-15 13:23 UTC, vikiival approved these changes

2023-03-15 14:14 UTC, vikiival commented
pay 25 usd

2023-03-15 14:14 UTC, merged

2023-03-15 14:14 UTC, yangwao commented
😍 Perfect, I’ve sent the payout 
💵 $25 @ 35.44 USD/KSM ~ 0.705 $KSM
🧗 [EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU](https://kusama.subscan.io/account/EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)
🔗 [0xa86e1cab2a14ff1fed6612c4a0e0d059faec44cc8b3287c5a35a15f95e9db82f](https://kusama.subscan.io/extrinsic/0xa86e1cab2a14ff1fed6612c4a0e0d059faec44cc8b3287c5a35a15f95e9db82f)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)