#5143
kodadot/nft-gallery pull request #5238
Opened 2023-03-12 22:10 UTC by prachi00

**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [ ] Closes #5143
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [ ] My contribution builds **clean without any errors or warnings**
- [ ] I've merged recent default branch -- **main** and I've no conflicts
- [ ] I've tried to respect high code quality standards
- [ ] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [ ] Fill up your KSM address: 
[Payout](https://beta.kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)

#### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
![Screen Shot 2023-03-12 at 3 09 24 PM](https://user-images.githubusercontent.com/39299315/224576700-b7c497e5-23df-4325-889a-95ed2d38b46f.png)

2023-03-13 02:18 UTC, daiagi approved these changes

2023-03-13 09:47 UTC, exezbcz commented
<img width="461" alt="image" src="https://user-images.githubusercontent.com/90852205/224665789-97935812-8f91-4596-880c-9a689a6c2005.png">
this to 40px please

2023-03-13 13:37 UTC, vikiival commented on layouts/explore-layout.vue
> +}
pls do not use px

2023-03-13 13:38 UTC, vikiival requested changes
as @exezbcz & I said Pls

2023-03-13 13:48 UTC, vikiival commented
+ please resolve conflicts

2023-03-14 10:49 UTC, vikiival commented on components/explore/SidebarFilter.vue
> +  margin-right: 32px;
```suggestion
  margin-right: 5rem;
```

2023-03-14 10:51 UTC, vikiival approved these changes

2023-03-14 11:08 UTC, merged