feat: load rmrk2 image on gallery item
kodadot/nft-gallery pull request #5279
Opened 2023-03-15 14:53 UTC by preschian

**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

- [x] Closes #5183

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [ ] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=<My_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address>)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

| &nbsp; | &nbsp; |
| --- | --- |
| <img width="1624" alt="Screenshot 2023-03-15 at 23 25 15" src="https://user-images.githubusercontent.com/734428/225358484-2a955a7e-398f-42e8-ac56-0594083fed93.png"> | <img width="1624" alt="Screenshot 2023-03-15 at 23 25 33" src="https://user-images.githubusercontent.com/734428/225358708-d96b4ea4-d78c-4868-b407-8bf69ed3922f.png"> |

2023-03-16 07:05 UTC, daiagi approved these changes

2023-03-16 12:52 UTC, vikiival requested changes
I want to avoid naming anything RMRK

2023-03-16 12:52 UTC, vikiival commented on components/base/types.ts
> +export interface CarouselNFT extends RMRK2Resources {
RMRK2Resources
```suggestion
export interface CarouselNFT extends ItemResources {
```

2023-03-16 12:52 UTC, vikiival commented on composables/useNft.ts
> +export type RMRK2Resources = {
```suggestion
export type ItemResource = {
```

2023-03-17 15:02 UTC, marcelosousa commented
/reviewpad summarize

2023-03-20 10:22 UTC, vikiival commented
@preschian can we please proceed? 🥺

2023-03-21 13:10 UTC, merged