fix: subscribe button styling
kodadot/nft-gallery pull request #5386
Opened 2023-03-26 13:00 UTC by leo-anderson-x

**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #5371
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [ ] My contribution builds **clean without any errors or warnings**
- [ ] I've merged recent default branch -- **main** and I've no conflicts
- [ ] I've tried to respect high code quality standards
- [ ] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=DzUbHCk3Fr3XdCPNKo7uCJvtBH7YfgiFbn4Gr3VmCMiFy1C)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

2023-03-26 15:06 UTC, Jarsen136 requested changes
Should also fix this mobile issue: submit button is missing.

current preview:
<img width="559" alt="image" src="https://user-images.githubusercontent.com/31397967/227784798-fe55e4dc-73d2-4cdf-8bbd-d2e61af1fade.png">

should be like this:

ref: #5283

![image](https://user-images.githubusercontent.com/31397967/227784970-b7052f10-da39-49c8-95be-bda618398b6e.png)

2023-03-27 14:15 UTC, leo-anderson-x commented
@Jarsen136 fixed. 


https://user-images.githubusercontent.com/128157824/227966068-50bc928d-0a08-4d92-bd43-b3c9190637a0.mp4

2023-03-27 16:18 UTC, roiLeo approved these changes

2023-03-27 16:27 UTC, Jarsen136 approved these changes

2023-03-28 13:04 UTC, merged