#5488 divider fix
kodadot/nft-gallery pull request #5507
Opened 2023-04-04 02:45 UTC by prachi00

**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [ ] Closes #5488
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [ ] My contribution builds **clean without any errors or warnings**
- [ ] I've merged recent default branch -- **main** and I've no conflicts
- [ ] I've tried to respect high code quality standards
- [ ] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [ ] Fill up your KSM address: 
[Payout](https://beta.kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)

#### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
<img width="408" alt="Screen Shot 2023-04-03 at 7 45 06 PM" src="https://user-images.githubusercontent.com/39299315/229673510-cd75c90f-8390-4f18-bb54-63844c160b2b.png">

2023-04-04 06:49 UTC, daiagi requested changes
the hover color in ```moreNFTDetails``` needs to extend to the edge of container

![image](https://user-images.githubusercontent.com/22791238/229710735-6299cfaf-3594-44b1-b8e2-c11938233f7f.png)

2023-04-05 05:18 UTC, daiagi requested changes
the hr margin should be same in flippers and in holders tab

2023-04-05 05:18 UTC, daiagi commented on components/collection/activity/ownerInsightsTabs/FlipperTab.vue
> +      <hr class="m-3" />
```suggestion
      <hr class="my-3 mx-5" />
```

2023-04-05 05:20 UTC, daiagi approved these changes
lgtm

2023-04-05 15:18 UTC, merged

2023-04-05 15:18 UTC, vikiival commented
pay 10 usd

2023-04-05 15:19 UTC, yangwao commented
😍 Perfect, I’ve sent the payout 
💵 $10 @ 33.45 USD/KSM ~ 0.299 $KSM
🧗 [EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU](https://kusama.subscan.io/account/EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)
🔗 [0xe3a5853f9a61af3971ab3e64bd542f069cf00b1a71a7b07045e2b87639913c25](https://kusama.subscan.io/extrinsic/0xe3a5853f9a61af3971ab3e64bd542f069cf00b1a71a7b07045e2b87639913c25)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)