feat: float filter button on mobile collection activity page
kodadot/nft-gallery pull request #5546
Opened 2023-04-07 12:35 UTC by leo-anderson-x

**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

- [x] Closes #5359 
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [x] I've tested it at </bsx/collection>
- [x] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=DzUbHCk3Fr3XdCPNKo7uCJvtBH7YfgiFbn4Gr3VmCMiFy1C)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

https://user-images.githubusercontent.com/128157824/230609671-444e8387-84b0-40ec-95c3-48b502dfba2f.mp4

2023-04-07 14:12 UTC, exezbcz commented
good! 
can we please make the space disappear after the burger menu is not displayed? - I mean the space between tab switch and white line
![image](https://user-images.githubusercontent.com/90852205/230623168-8ce13e59-87b2-4b4a-8f21-1a1f1e1ce44d.png)

2023-04-07 14:13 UTC, daiagi requested changes
few changes please

2023-04-07 14:13 UTC, daiagi commented on components/explore/FilterFloatButton.vue
> +const numOfActiveFilters = computed(() => {
this is becoming a shared functionality shared by FilterMeunButton, this component and BreadCrumbsFilter
please extract it to a composable

2023-04-07 14:13 UTC, daiagi commented on components/explore/MobileControls.vue
> +      <FilterFloatButton v-if="isActivityTab" />
please use v-else instead

2023-04-07 14:13 UTC, daiagi commented on components/explore/FilterFloatButton.vue
> +@import '@/styles/abstracts/variables';
not needed as you are not using any theme style here

2023-04-08 08:29 UTC, leo-anderson-x commented
> good! can we please make the space disappear after the burger menu is not displayed? - I mean the space between tab switch and white line

@exezbcz fixed:
![deploy-preview-5546--koda-canary netlify app_bsx_collection_3586573150_activity_page=1(iPhone SE)](https://user-images.githubusercontent.com/128157824/230711830-87ef873f-5043-4b7f-a7f9-0118d20a209f.png)

2023-04-08 10:40 UTC, exezbcz commented
@leo-anderson-x yes, good job!

2023-04-09 05:34 UTC, daiagi reviewed
nice job!
just fix 1 relative import please

2023-04-09 05:34 UTC, daiagi commented on components/explore/MobileControls.vue
> +import FilterFloatButton from '../collection/activity/FilterFloatButton.vue'
```suggestion
import FilterFloatButton from '@/components/collection/activity/FilterFloatButton.vue'
```

2023-04-09 13:43 UTC, daiagi approved these changes

2023-04-10 11:56 UTC, yangwao commented
pay 30 usd

2023-04-10 11:56 UTC, merged