fix: set prefix to localStorage
kodadot/nft-gallery pull request #5594
Opened 2023-04-11 07:41 UTC by preschian

**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #5576
- [x] Closes #5556

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

2023-04-11 09:21 UTC, vikiival approved these changes

2023-04-11 09:40 UTC, roiLeo approved these changes
✅ code lgtm

2023-04-11 09:40 UTC, roiLeo commented on composables/usePrefix.ts
> +  const storage = useLocalStorage('urlPrefix', { selected: 'bsx' })
maybe set 'bsx' as constant (`DEFAULT_PREFIX`)

2023-04-11 11:39 UTC, yangwao commented
I think it's for separate issue? 

When I switch to "RMRK2" it lands this

https://user-images.githubusercontent.com/5887929/231151663-6ce4ef70-8f3f-4ac3-83fb-7f37759226d1.mov

2023-04-11 15:09 UTC, roiLeo requested changes
Hey we still have a small issue mayberelated with https://github.com/kodadot/nft-gallery/pull/5472#discussion_r1157003027, I can't manage to change network from explore menu

2023-04-12 06:51 UTC, roiLeo approved these changes
✅ wfm

2023-04-12 10:29 UTC, yangwao commented
pay 30 usd

2023-04-12 10:29 UTC, merged

2023-04-12 10:29 UTC, yangwao commented
😍 Perfect, I’ve sent the payout 
💵 $30 @ 33.29 USD/KSM ~ 0.901 $KSM
🧗 [DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM](https://kusama.subscan.io/account/DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM)
🔗 [0x26e68d24f0da3afae1e8d6c4f9408b2aa4e05e0e1175f177cddc7776d0fff8e4](https://kusama.subscan.io/extrinsic/0x26e68d24f0da3afae1e8d6c4f9408b2aa4e05e0e1175f177cddc7776d0fff8e4)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)