fix: not showing royalties in gallery detail
kodadot/nft-gallery pull request #5674
Opened 2023-04-15 03:36 UTC by leo-anderson-x

**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix

## Context

- [x] Closes #5671 

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=DzUbHCk3Fr3XdCPNKo7uCJvtBH7YfgiFbn4Gr3VmCMiFy1C)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

https://canary.kodadot.xyz/ksm/gallery/16859826-4036da32f78754d408-J66M9-MANTA_SEA_RED_DEVIL-00000017

![CleanShot 2023-04-15 at 12 32 34@2x](https://user-images.githubusercontent.com/128157824/232181046-126263e6-83fa-4164-965d-e4046e9c48e1.png)

2023-04-15 07:58 UTC, daiagi approved these changes

2023-04-17 08:58 UTC, roiLeo requested changes
There is no things as `royalty` on rmrk v1.0.0

2023-04-17 11:03 UTC, vikiival commented on queries/subsquid/rmrk/nftById.graphql
> +    royalty
```suggestion
```

2023-04-17 11:19 UTC, roiLeo approved these changes

2023-04-17 12:33 UTC, merged

2023-04-17 12:33 UTC, vikiival commented
pay 10 usd