feat: Show rmrk version in item description
kodadot/nft-gallery pull request #5691
Opened 2023-04-15 18:03 UTC by Jarsen136

**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

- [x] Closes #5681
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
`/ksm/gallery/13328952-54bbd380dc3baaa27b-EVRSOULS-Ranger-00000922`
<img width="588" alt="image" src="https://user-images.githubusercontent.com/31397967/232245820-1461b14f-b69a-4c13-a96d-127e6b9f881b.png">

`/rmrk/gallery/17483893-9AFFD71D65E3DBBF29-KODA_VILLA-KODA_VILLAGE_2-0000000000000002`
<img width="734" alt="image" src="https://user-images.githubusercontent.com/31397967/232245874-e0fdcf62-6700-45ed-9a01-d0b421b53b88.png">

2023-04-15 20:11 UTC, vikiival approved these changes

2023-04-15 20:12 UTC, vikiival requested changes

2023-04-15 20:12 UTC, vikiival commented on components/gallery/GalleryItemDescription.vue
> +const { isV2 } = useRmrkVersion()
```suggestion
const { version } = useRmrkVersion()
```

2023-04-15 20:12 UTC, vikiival commented on components/gallery/GalleryItemDescription.vue
> +      </div>
```suggestion
      <div
        v-if="version"
        class="is-flex is-justify-content-space-between">
        <p>{{ $t('tabs.tabDetails.version') }}</p>
        <p>{{ version }}</p>
      </div>
```

2023-04-16 08:57 UTC, exezbcz commented
![image](https://user-images.githubusercontent.com/90852205/232287997-8e06e812-bc22-42ae-96fd-13d959db0666.png)
it shows 1.0.0 on my end, is that alright? (The 3 digit version format) 


for rmrk2 as well
![image](https://user-images.githubusercontent.com/90852205/232288045-0b45fa21-def4-4493-9603-95271024f650.png)

2023-04-16 12:07 UTC, vikiival commented
Yup It's correct

2023-04-16 12:08 UTC, vikiival approved these changes

2023-04-16 12:08 UTC, merged

2023-04-16 12:08 UTC, vikiival commented
pay 10 usd

2023-04-16 12:08 UTC, yangwao commented
😍 Perfect, I’ve sent the payout 
💵 $10 @ 36.61 USD/KSM ~ 0.273 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0xb6e8c99ead509daf936ca3932f1c9798ad2f7579f951c1820dea24b6f0dbcc15](https://kusama.subscan.io/extrinsic/0xb6e8c99ead509daf936ca3932f1c9798ad2f7579f951c1820dea24b6f0dbcc15)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)