fix: default title seo.
kodadot/nft-gallery pull request #5695
Opened 2023-04-16 15:33 UTC by zhyd1997

**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #5694
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [x] I've tested it at </bsx/collection>
- [x] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=H2DifyJqaansQREdGFU4BxZyaApbkCgP1a9Pq4xKaebSFZh)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

<img width="700" alt="Screenshot 2023-04-16 at 23 32 10" src="https://user-images.githubusercontent.com/31362988/232323550-9f2697f9-b0c2-4d06-806a-008062637523.png">

2023-04-16 17:05 UTC, vikiival requested changes

2023-04-17 00:34 UTC, zhyd1997 commented on nuxt.config.js
> +    title: 'KodaDot - One Stop Shopw for Polkadot NFTs',
Sorry, done!

2023-04-17 12:34 UTC, vikiival approved these changes

2023-04-17 12:35 UTC, merged

2023-04-17 12:36 UTC, vikiival commented
pay 10 usd

2023-04-17 12:36 UTC, yangwao commented
😍 Perfect, I’ve sent the payout 
💵 $10 @ 36.29 USD/KSM ~ 0.276 $KSM
🧗 [H2DifyJqaansQREdGFU4BxZyaApbkCgP1a9Pq4xKaebSFZh](https://kusama.subscan.io/account/H2DifyJqaansQREdGFU4BxZyaApbkCgP1a9Pq4xKaebSFZh)
🔗 [0x4f32ee57bad51a72482d8bbd3f39862f118a50ccce0ae6d000043a41d29ee0f2](https://kusama.subscan.io/extrinsic/0x4f32ee57bad51a72482d8bbd3f39862f118a50ccce0ae6d000043a41d29ee0f2)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)