🔧 footer hello links
kodadot/nft-gallery pull request #5926
Opened 2023-05-11 14:52 UTC by roiLeo

First PR on M2 Chip

## PR Type

- [x] Bugfix

## Context

- [x] Closes #5900

2023-05-11 19:17 UTC, yangwao requested changes
@JustLuuuu supposed post new updated link, there was following changes

2023-05-11 19:17 UTC, yangwao commented on components/TheFooter.vue
> +    url: 'https://hello.kodadot.xyz/general-1/faq',
https://hello.kodadot.xyz/ecosystem/faq

2023-05-11 19:17 UTC, yangwao commented on components/TheFooter.vue
> +    url: 'https://hello.kodadot.xyz/general/faq',
https://hello.kodadot.xyz/about-us/who-are-we

2023-05-11 19:17 UTC, yangwao commented on components/TheFooter.vue
> +    url: 'https://hello.kodadot.xyz/technical/kodadots-programs/artist-referral-program',
https://hello.kodadot.xyz/be-part-of-kodadot/kodadots-programs/artist-referral-program

2023-05-11 19:17 UTC, yangwao commented on components/TheFooter.vue
> +    url: 'https://hello.kodadot.xyz/technical/kodadots-programs/artist-ambassador-program',
https://hello.kodadot.xyz/be-part-of-kodadot/kodadots-programs/artist-ambassador-program

2023-05-11 19:17 UTC, yangwao commented on components/TheFooter.vue
> +    url: 'https://hello.kodadot.xyz/technical/kodadots-programs/ambassador-program',
https://hello.kodadot.xyz/be-part-of-kodadot/kodadots-programs/ambassador-program

2023-05-12 07:05 UTC, preschian approved these changes

2023-05-12 07:38 UTC, daiagi approved these changes

2023-05-12 10:12 UTC, yangwao commented
mmm

![image](https://github.com/kodadot/nft-gallery/assets/5887929/1de92c21-e54e-4c7a-9495-aaf8fcb9646b)

I would also 
- deleted completely Contribute page from this codebase (as we want maintain less same files)
- link Contribute to https://hello.kodadot.xyz/be-part-of-kodadot/join-as-a-developer

2023-05-12 10:19 UTC, roiLeo commented
> * https://hello.kodadot.xyz/be-part-of-kodadot/join-as-a-developer

Done, do we keep `CONTRIBUTING.md`?

2023-05-12 10:20 UTC, JustLuuuu commented
I would also love to have tutorials in the footer:
https://hello.kodadot.xyz/tutorial/

2023-05-12 12:12 UTC, roiLeo commented
> @JustLuuuu is everything oki?

Nope wait for last commit

2023-05-12 12:15 UTC, roiLeo commented
😢 
<img width="682" alt="Capture d’écran 2023-05-12 à 2 14 51 PM" src="https://github.com/kodadot/nft-gallery/assets/9987732/9fe107e6-042c-44c7-b7c8-b94b80078444">

2023-05-12 12:16 UTC, closed without merging