#6147 refactor footer
kodadot/nft-gallery pull request #6169
Opened 2023-06-06 04:04 UTC by prachi00

**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

## Needs QA check

- @kodadot/qa-guild please review

## Context

- [ ] Closes #6147
- [ ] Requires deployment <snek/rubick/worker>

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=13Qx65nLd6SwdtjrRyuoEtp9CKXhF651xdHBPaXcvhwKm4N1)

## Screenshot 📸

- [x] My fix has changed UI
<img width="1245" alt="Screen Shot 2023-06-05 at 9 04 41 PM" src="https://github.com/kodadot/nft-gallery/assets/39299315/1182d477-60b0-43c3-af83-be21022ff2fc">

## Copilot Summary

2023-06-06 05:08 UTC, Jarsen136 requested changes
Some link on the footer would redirect to incorrect url.

<img width="1051" alt="image" src="https://github.com/kodadot/nft-gallery/assets/31397967/2c5a00bf-6b0d-4128-acfa-613e13d57028">

2023-06-06 05:23 UTC, prachi00 commented
> Some link on the footer would redirect to incorrect url.
> 
> <img alt="image" width="1051" src="https://user-images.githubusercontent.com/31397967/243551633-2c5a00bf-6b0d-4128-acfa-613e13d57028.png">

oh forgot the external boolean, thanks, fixed it

2023-06-06 05:37 UTC, Jarsen136 reviewed
otherwise lgtm

2023-06-06 05:37 UTC, Jarsen136 commented on components/TheFooter.vue
> +    name: $i18n.t('faq'),
please upper case `FAQ`

2023-06-06 06:38 UTC, preschian approved these changes

2023-06-06 06:47 UTC, Jarsen136 approved these changes

2023-06-06 10:17 UTC, exezbcz commented
the subscribe button is not sizing correctly 
<img width="1039" alt="image" src="https://github.com/kodadot/nft-gallery/assets/90852205/8f28dd68-4e89-4ac1-897a-2263f91c62d3">
1082px and around that 


same on 850px 
<img width="840" alt="image" src="https://github.com/kodadot/nft-gallery/assets/90852205/0d7eff17-2454-4917-b206-8fd42bb013dc">

- I would maybe switch to mobile footer here

2023-06-07 04:28 UTC, prachi00 commented
@prury it is already center aligned 
<img width="350" alt="Screen Shot 2023-06-06 at 9 27 42 PM" src="https://github.com/kodadot/nft-gallery/assets/39299315/84569ff6-7f87-43cd-8b29-50695d8974c0">

2023-06-07 04:54 UTC, prachi00 commented
@exezbcz fixed the 1st one
for the 2nd one, it seems mobile view starts at 768px, we use buefy helper for that https://bulma.io/documentation/helpers/visibility-helpers/

2023-06-08 04:08 UTC, prachi00 commented
> > @prury it is already center aligned <img alt="Screen Shot 2023-06-06 at 9 27 42 PM" width="350" src="https://user-images.githubusercontent.com/39299315/243910802-84569ff6-7f87-43cd-8b29-50695d8974c0.png">
> 
> i mean like that: ![image](https://user-images.githubusercontent.com/36627808/244070391-2e223261-e5d1-4fc3-8b35-3f6d37abfc21.png)

<img width="361" alt="Screen Shot 2023-06-07 at 9 08 05 PM" src="https://github.com/kodadot/nft-gallery/assets/39299315/290775b7-c564-42d6-acf8-5014bafafa1b">
done

2023-06-08 12:30 UTC, vikiival commented
@exezbcz can we merge?

2023-06-08 15:40 UTC, yangwao commented
> Documentation -> fix link to [developers.kodadot.xyz](https://developers.kodadot.xyz/)
Documetation should be renamed to "Developers" and point to -> developers.kodadot.xyz

2023-06-08 22:43 UTC, prachi00 commented
![Screen Shot 2023-06-08 at 3 42 39 PM](https://github.com/kodadot/nft-gallery/assets/39299315/b9a98a43-3465-43d1-8084-0f3b071ce45f)
done @yangwao

2023-06-11 06:43 UTC, prachi00 commented
@yangwao @vikiival  can we merge this

2023-06-12 10:57 UTC, merged

2023-06-12 10:57 UTC, vikiival commented
pay 30 usd

2023-06-12 10:57 UTC, yangwao commented
😍 Perfect, I’ve sent the payout 
💵 $30 @ 4.54 USD/DOT ~ 6.608 $DOT
🧗 [13Qx65nLd6SwdtjrRyuoEtp9CKXhF651xdHBPaXcvhwKm4N1](https://polkadot.subscan.io/account/13Qx65nLd6SwdtjrRyuoEtp9CKXhF651xdHBPaXcvhwKm4N1)
🔗 [0x7484736c3840c3202a5fcab71966fd5d7f4339a0460fcbc722244ef7cf51910e](https://polkadot.subscan.io/extrinsic/0x7484736c3840c3202a5fcab71966fd5d7f4339a0460fcbc722244ef7cf51910e)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)