🔧 profile page buttons
kodadot/nft-gallery pull request #6187
Opened 2023-06-08 12:41 UTC by roiLeo

- closes #6167 
- not aligned?

![Screenshot 2023-06-08 at 14-38-32 NFT Artist Profile on KodaDot KodaDot - NFT Market Explorer](https://github.com/kodadot/nft-gallery/assets/9987732/d2bf7bc5-93c8-440d-b1f1-9664b614d510)
![Screenshot 2023-06-08 at 14-40-21 NFT Artist Profile on KodaDot KodaDot - NFT Market Explorer](https://github.com/kodadot/nft-gallery/assets/9987732/785f0efc-d339-4ede-9b29-d109e9ed8eca)

2023-06-08 15:41 UTC, prury commented
Clicking on them only opens the link if you click on the image, not in the whole button per se.

2023-06-09 07:56 UTC, preschian requested changes
doesnt work:
- gift button to 404 page
- qr code title

2023-06-09 08:09 UTC, roiLeo commented
> doesnt work:
> 
>     * gift button to 404 page
> 
>     * qr code title

Thanks for the review, now fixed

![Screenshot 2023-06-09 at 10-08-47 NFT Artist Profile on KodaDot KodaDot - NFT Market Explorer](https://github.com/kodadot/nft-gallery/assets/9987732/0782fa00-201b-49f0-9ece-f517dde74061)

2023-06-09 08:16 UTC, preschian approved these changes

2023-06-09 13:34 UTC, daiagi commented
![image](https://github.com/kodadot/nft-gallery/assets/22791238/b75602c9-d4c6-49f4-97f0-452316057bc1)

can we add some gap or remove the double borders?

2023-06-09 14:05 UTC, roiLeo commented
> can we add some gap or remove the double borders?

Should be possible, but a bit long to debug. I think we might wait for the new design because they could disappear

2023-06-09 14:06 UTC, prury commented
> > can we add some gap or remove the double borders?
> 
> Should be possible, but a bit long to debug. I think we might wait for the new design because they could disappear

2023-06-09 14:06 UTC, prury commented
sorry, missclicked

2023-06-09 14:22 UTC, daiagi commented
>Should be possible, but a bit long to debug. I think we might wait for the new design because they could disappear

fine by me, let's see what the new design brings

2023-06-09 14:28 UTC, daiagi commented on components/rmrk/Profile/ProfileDetail.vue
> +  }
smol

  ```suggestion
get realworldFullPath(): string {
    return window.location.href
  }
  ```

2023-06-09 14:29 UTC, daiagi approved these changes

2023-06-09 14:45 UTC, merged