#675 Open ksm transaction and view current price of KSM
kodadot/nft-gallery pull request #692
Opened 2021-09-03 15:12 UTC by prachi00

**Thank you for your contribution** to the KodaDot NFT gallery.
Let's do a quick check before the merge.
Your contribution will be an eternal part of the community codebase

### Before submitting this PR, please make sure:
- [x] Code builds clean without any errors or warnings
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I didn't break any original functionality

### Optional
- [ ] I've tested it on mobile and everything works

### PR type
- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

### What's new? (maybe part of changelog)
- closes #675 -  For opening ksm transactions, I have added a button and have found the transaction id using `blockHash.toHex();`
For showing current price of KSM, have used state variable `fiatPrice`. 

### If issue contains bounty label ($,$$,$$$)
- Your KSM address: EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU

### Community participation
- [x] Are you at KodaDot Discord? If no, [let's join us - https://discord.gg/35hzy2dXXh](https://discord.gg/35hzy2dXXh)

### Screenshot
- [x] Whenever your fix will change **something** on UI, a screenshot is more than welcome

<img width="535" alt="Screenshot 2021-09-03 at 8 32 55 PM" src="https://user-images.githubusercontent.com/39299315/132028058-271eba31-ccd4-4590-b844-1635b793ee8a.png">

2021-09-03 15:21 UTC, vikiival requested changes
Otherwise good.
But I would move the button under the form

2021-09-03 15:21 UTC, vikiival commented on src/components/transfer/Transfer.vue
> +          </div>
You should write a [Vuex getter](https://vuex.vuejs.org/guide/getters.html) for this

2021-09-03 15:21 UTC, vikiival commented on src/components/transfer/Transfer.vue
> +      this.$store.state.explorer.chain,
also getter for this

2021-09-03 15:21 UTC, vikiival commented on src/components/transfer/Transfer.vue
> +    const url =  urlBuilderTransaction(this.transactionValue,
Use the linter please

2021-09-03 15:23 UTC, yangwao commented
Why is a field for an address now short?
Balance seems needs spacing from amount 
![image](https://user-images.githubusercontent.com/5887929/132029422-2ac5d93e-c832-4044-956f-cc14f8b3c07e.png)
On the production looks like longer, it's better when one wants to see whole address https://nft.kodadot.xyz/transfer

2021-09-03 15:48 UTC, prachi00 commented
> have done the mentioned changes and updated the screenshot in the PR description

2021-09-05 09:49 UTC, yangwao commented
I would show the button only if there was made some transaction.
Now it shows by default and leading to https://kusama.subscan.io/extrinsic/
![image](https://user-images.githubusercontent.com/5887929/132122546-935f32be-9818-442d-bfa2-6e3732059b93.png)

I'm thinking that showing on button first 6 chars from extrinsic would be perfect to identify transaction before clicking

2021-09-05 18:38 UTC, prachi00 commented
@yangwao 
<img width="824" alt="Screenshot 2021-09-06 at 12 07 14 AM" src="https://user-images.githubusercontent.com/39299315/132137771-7638c508-4205-4165-becd-287bf4b8a99d.png">

Have fixed these. Please check now.

2021-09-07 12:58 UTC, yangwao commented
@prachi00 you are officially the first one I've used it to pay out the bounty, feels amazing! 

![image](https://user-images.githubusercontent.com/5887929/132348671-c3f3a519-3dca-4150-96ce-edbf035acc11.png)

2021-09-07 12:58 UTC, merged