Ksm Usd convertor in transfer
kodadot/nft-gallery pull request #700
Opened 2021-09-08 06:37 UTC by prachi00

**Thank you for your contribution** to the KodaDot NFT gallery.
Let's do a quick check before the merge.
Your contribution will be an eternal part of the community codebase

### Before submitting this PR, please make sure:
- [x] Code builds clean without any errors or warnings
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I didn't break any original functionality

### Optional
- [x] I've tested it on mobile and everything works

### PR type
- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

### What's new? (maybe part of changelog)
- closes #<issue_number> 
Have added an input field for USD, where you can constantly change the values and get KSM price and vice versa.
One issue with this is that the KSM price we fetch is from an API and the value doesn't change unless you reload, that is why I have added an approximate text, so the user knows the value is approximate.
Suggestion: In the future, we can implement polling or sockets so the KSM price changes instantly. 

### If issue contains bounty label ($,$$,$$$)
- Your KSM address: EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU

### Community participation
- [x] Are you at KodaDot Discord? If no, [let's join us - https://discord.gg/35hzy2dXXh](https://discord.gg/35hzy2dXXh)

### Screenshot
- [x] Whenever your fix will change **something** on UI, a screenshot is more than welcome

<img width="802" alt="Screenshot 2021-09-08 at 11 55 27 AM" src="https://user-images.githubusercontent.com/39299315/132457244-0e29e374-d8d9-4974-bdbb-aae7c9a15108.png">

2021-09-15 08:01 UTC, roiLeo requested changes

2021-09-16 08:44 UTC, yangwao commented
works!

2021-09-16 08:44 UTC, merged

2021-09-16 12:11 UTC, abhisar2006 commented
Hi,

I came across an Issue.. Dont know if it is a valid one.

![image](https://user-images.githubusercontent.com/30148793/133609737-fae551b8-e4cf-4c7a-8f15-46dcf062b463.png)

The minimum value is 3 decimal points. Is that right?

2021-09-16 12:46 UTC, roiLeo commented
> Hi,
> 
> I came across an Issue.. Dont know if it is a valid one.
> 
> ![image](https://user-images.githubusercontent.com/30148793/133609737-fae551b8-e4cf-4c7a-8f15-46dcf062b463.png)
> 
> The minimum value is 3 decimal points. Is that right?

Yes, it comes from input ```step="0.001"```