Netlify Deploy Button for Kodadot-app #1397
kodadot/nft-gallery pull request #7508
Opened 2023-10-05 03:18 UTC by AshutoshSingh72

Thank you for your contribution to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz/).

👇 __ Let's make a quick check before the contribution.
## Problems
I tried to list Kodadot NFT gallery tamplate on  https://www.netlify.com/integrations/templates/
But https://github.com/netlify/templates this Template Git hub Repo is Archived but i tried to make pull request but because it is archived i wan't able to pull 
![IMG_20231004_172752](https://github.com/kodadot/nft-gallery/assets/78789916/a77d197b-15b8-46e9-98d4-06757c497be2)

View my Template 
md file https://github.com/AshutoshSingh72/templates/blob/master/src/site/template/Kodadot-nft-gallery.md

## Fixes
But i was able able to build the netlify deploy button added it into the contributor md

## PR Type
- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

- [x] Closes #1397
- [x] ## Did your issue had any of the "$" label on it?
- [x] My DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=158VTDxZJidzsMcAdh7h828domveRvpmk1SCxwLUEHhcgY4v&usdamount=0&donation=true)

2023-10-05 12:45 UTC, vikiival requested changes
https://www.netlify.com/blog/2021/12/26/deploying-with-the-click-of-a-button/

2023-10-05 12:45 UTC, vikiival commented on CONTRIBUTING.md
> +
```suggestion
[![Deploy to Netlify](https://www.netlify.com/img/deploy/button.svg)](https://app.netlify.com/start/deploy?repository=https://github.com/kodadot/nft-gallery)
```

2023-10-05 13:44 UTC, AshutoshSingh72 commented
> https://www.netlify.com/blog/2021/12/26/deploying-with-the-click-of-a-button/

😅 Thanks viki i was using the same code but i forgot to update https://github.com/AshutoshSingh72/nft-gallery/commit/7c3d79dc031462fa54bb5284dc6c2dbe254be258

2023-10-05 13:45 UTC, AshutoshSingh72 commented
> https://www.netlify.com/blog/2021/12/26/deploying-with-the-click-of-a-button/

Updated

2023-10-05 13:53 UTC, AshutoshSingh72 commented
> https://www.netlify.com/blog/2021/12/26/deploying-with-the-click-of-a-button/

I'm requesting review from you viki

2023-10-08 16:29 UTC, AshutoshSingh72 commented
Cc @yangwao @vikiival

2023-10-09 10:11 UTC, vikiival commented
Hello,
the solution that you provided does not work ^-^
Please take high issue with a higher priority

<img width="1680" alt="Screenshot 2023-10-09 at 12 08 49" src="https://github.com/kodadot/nft-gallery/assets/22471030/4694764e-6b05-4abe-9f9a-f46c49d3145c">

2023-10-09 10:11 UTC, closed without merging

2023-10-09 13:05 UTC, AshutoshSingh72 commented
> Hello, the solution that you provided does not work ^-^ Please take high issue with a higher priority
> 
> <img alt="Screenshot 2023-10-09 at 12 08 49" width="1680" src="https://user-images.githubusercontent.com/22471030/273554411-4694764e-6b05-4abe-9f9a-f46c49d3145c.png">

I'm using the same deploy button and it is working https://6523f73dadb3140a638f697e--melodic-cheesecake-9489e5.netlify.app/

2023-10-09 13:07 UTC, AshutoshSingh72 commented
> Hello, the solution that you provided does not work ^-^ Please take high issue with a higher priority
> 
> <img alt="Screenshot 2023-10-09 at 12 08 49" width="1680" src="https://user-images.githubusercontent.com/22471030/273554411-4694764e-6b05-4abe-9f9a-f46c49d3145c.png">

![Screenshot_2023-10-09-18-36-31-80](https://github.com/kodadot/nft-gallery/assets/78789916/f31085d3-c1f8-4af0-ac4a-695267dee4f0)

2023-10-09 13:09 UTC, vikiival commented
Looks a residual from some old repository 

https://app.netlify.com/sites/joyful-douhua-7de1e0/deploys/6523fb58dae19f089b306ed0

please anyway open new pr with correct commit description.

2023-10-09 13:16 UTC, vikiival commented
Yup looks like its working

<img width="1680" alt="Screenshot 2023-10-09 at 15 14 03" src="https://github.com/kodadot/nft-gallery/assets/22471030/b7ac35f6-3345-447f-bad1-e6c1d69d5e82">

I had some residual repository.

Reasons Why I closed this PR:
Sir well you do not follow the contributing standards 🙂 

1. 7 same commits
2. Not using PR template
3. Screenshots not provided
4. Issue never created for this PR.

2023-10-09 13:26 UTC, AshutoshSingh72 commented
> Yup looks like its working
> 
> <img alt="Screenshot 2023-10-09 at 15 14 03" width="1680" src="https://user-images.githubusercontent.com/22471030/273596105-b7ac35f6-3345-447f-bad1-e6c1d69d5e82.png">
> I had some residual repository.
> 
> Reasons Why I closed this PR: Sir well you do not follow the contributing standards 🙂
> 
> 1. 7 same commits
> 2. Not using PR template
> 3. Screenshots not provided
> 4. Issue [Create kodadot-app Netlify Deploy Button #1397](https://github.com/kodadot/nft-gallery/issues/1397) was created almost **2yrs ago**

bro for me i'm working here to solve some problems i faced first time joining kodadot contributors so it might be the oldest issue but it is a big deal for new contributors who stuck on this