🔧 transfer assetHub
kodadot/nft-gallery pull request #7636
Opened 2023-10-13 07:15 UTC by roiLeo

- ref #7632 

What need to be tested:
- transfer on ahk
- transfer on ahp
- transfer on old ahp collection (`u-`)

2023-10-13 12:27 UTC, vikiival requested changes

2023-10-13 12:27 UTC, vikiival commented on composables/transaction/transactionSend.ts
> +    cb: api.tx.uniques.transfer,
```suggestion
    cb: getApiCall(api, item.urlPrefix, Interaction.SEND, legacy),
```

2023-10-13 12:44 UTC, roiLeo commented on composables/transaction/transactionSend.ts
> +    cb: api.tx.uniques.transfer,
this will be the same issue imo

2023-10-13 12:59 UTC, vikiival commented on composables/transaction/transactionSend.ts
> +import { assetHubParamResolver } from '@/utils/gallery/abstractCalls'
```suggestion
import { assetHubParamResolver, getApiCall } from '@/utils/gallery/abstractCalls'
```

2023-10-13 13:00 UTC, vikiival commented
well accourding to screen that was in the issue the point is that the transaction is constructed correctly but instead of `uniques.transfer`, `nfts.transfer` is sent

2023-10-13 13:02 UTC, roiLeo commented
> well accourding to screen that was in the issue the point is that the transaction is constructed correctly but instead of `uniques.transfer`, `nfts.transfer` is sent

legacy collection (prefix `u-`) should use `uniques` or `nft` pallet?

2023-10-13 15:11 UTC, roiLeo commented on composables/transaction/transactionSend.ts
> +import { assetHubParamResolver, getApiCall } from '@/utils/gallery/abstractCalls'
```suggestion
import {
  assetHubParamResolver,
  getApiCall,
} from '@/utils/gallery/abstractCalls'
```

2023-10-13 15:19 UTC, prury commented
@roiLeo when you think is ready lmk, i'll ask the user to test using the deploy link

2023-10-13 15:45 UTC, vikiival commented
> legacy collection (prefix u-) should use uniques or nft pallet?

Uniques.

2023-10-16 07:03 UTC, roiLeo commented
> @roiLeo when you think is ready lmk, i'll ask the user to test using the deploy link

this is already testable

2023-10-16 10:55 UTC, vikiival commented
![Screenshot 2023-10-16 at 12 53 56](https://github.com/kodadot/nft-gallery/assets/22471030/4f06f52b-c504-400e-bd00-bbf9e2e1844d)


![Screenshot 2023-10-16 at 12 53 59](https://github.com/kodadot/nft-gallery/assets/22471030/5fb52aa0-dc46-4d47-a173-abff8c07e095)

2023-10-16 10:55 UTC, vikiival approved these changes

2023-10-16 10:55 UTC, merged

2023-10-16 10:56 UTC, vikiival commented
Tested, the correct handler is spawned

2023-10-16 10:57 UTC, roiLeo commented
oh my.. this screen resolution should be illegal