#731 Using native webshare API for sharing
kodadot/nft-gallery pull request #797
Opened 2021-09-25 15:21 UTC by prachi00

**Thank you for your contribution** to the KodaDot NFT gallery.
Let's do a quick check before the merge.
Your contribution will be an eternal part of the community codebase.

### PR type
- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

### Before submitting this PR, please make sure:
- [x] Code builds clean without any errors or warnings
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've didn't break any original functionality
- [x] I've posted screenshot of demonstrated change in this PR

### Optional
- [x] I've tested it on mobile and everything works
- [ ] I found edge cases

### What's new? (may be part of changelog)
- This PR closes #731 
Have used share api for all the platforms where its supported

### If issue had bounty label ($,$$,$$$)
- Fill up your KSM address: 
https://kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU

### Community participation
- [x] Are you at KodaDot Discord? If not yet, [let's join us - https://discord.gg/35hzy2dXXh](https://discord.gg/35hzy2dXXh)

### Screenshot
- [x] Whenever my fix has changed **something** on UI, a screenshot for others, is more than welcome
![WhatsApp Image 2021-09-25 at 8 48 07 PM](https://user-images.githubusercontent.com/39299315/134776548-e752f029-6e9a-4c0b-b01a-7c30dfe190bc.jpeg)

2021-09-25 15:35 UTC, yangwao commented
Seems working well! 
Let me wait for @roiLeo review if everything is okay
![telegram-cloud-photo-size-4-5943001867757925936-y](https://user-images.githubusercontent.com/5887929/134777062-eb205435-de8b-4496-9c07-76c8a6b1bb12.jpg)

2021-09-25 17:04 UTC, roiLeo requested changes
LGTM works well on mobile, just a quick change to fix linting errors.

2021-09-25 19:07 UTC, prachi00 commented on src/components/rmrk/Gallery/Item/Sharing.vue
> +        title: "KodaDot",
fixed

2021-09-25 20:18 UTC, roiLeo approved these changes

2021-09-26 07:09 UTC, vikiival approved these changes
WFM

2021-09-26 07:09 UTC, merged