Add royalties to collection mint
kodadot/nft-gallery pull request #9109
Opened 2024-01-23 15:27 UTC by brano-hozza

**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

- [x] Closes #8130 
- [ ] Requires deployment <snek/rubick/worker>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality

#### Optional

- [ ] I've tested it at </ksm/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16DkEx1FzrKqTLPqTJNsSosKJ2UGbUVoLEhiGFFV8cYFpfj1)

#### Community participation

- [x] [Are you at KodaDot Ecosystem Telegram?](https://t.me/kodadot_eco)

## Screenshot 📸

- [x] My fix has changed collection mint form on UI; a screenshot is best to understand changes for others.
![image](https://github.com/kodadot/nft-gallery/assets/64609060/4d0ea14a-3426-42f5-b704-a0372ab94e79)

2024-01-23 16:03 UTC, roiLeo reviewed
Hey, small stuff.

It's missing on Create Nft to display default collection royalty when has been set on collection.

2024-01-23 17:41 UTC, brano-hozza commented on composables/transaction/mintCollection/transactionMintCollectionStatemine.ts
> +  }
I did this after chatting with @vikiival so I am not sure

2024-01-23 17:43 UTC, brano-hozza commented on components/create/CreateCollection.vue
> +      <NeoField v-if="!isRmrk">
It's the same as in `CreateNFT` component, should it be different?

2024-01-23 18:23 UTC, vikiival commented on composables/transaction/mintCollection/transactionMintCollectionStatemine.ts
> +  }
There is no such thing as `set_collection_attribute`


<img width="1649" alt="Screenshot 2024-01-23 at 19 22 51" src="https://github.com/kodadot/nft-gallery/assets/22471030/09af3792-d11e-4296-a26c-b09460ecb892">

2024-01-23 18:25 UTC, vikiival commented on components/create/CreateCollection.vue
> +      <NeoField v-if="!isRmrk">
RoiLeo is right, collection royalty only works on assethub

2024-01-23 18:27 UTC, vikiival commented
> It's missing on Create Nft to display default collection royalty when has been set on collection.

How would you do it? 

Because I would hide set royalty on create NFT in asset hub, 
just to make info text

2024-01-24 08:12 UTC, roiLeo commented on composables/transaction/mintCollection/transactionMintCollectionStatemine.ts
> +  }
nvm I was looking at https://github.com/paritytech/polkadot-sdk/blob/a817d310bb5c88267e57eb41fea3f9f56124f8e0/substrate/frame/nfts/src/impl_nonfungibles.rs#L296

2024-01-24 11:28 UTC, brano-hozza commented
So which one?

2024-01-24 12:02 UTC, vikiival commented
I think roiLeo has good solution for royalties handling.
I have opened issue #9120 because the scope of #8130 was to add this input to collection.

So if you want @brano-hozza you can do follow-up issue.

2024-01-24 12:21 UTC, vikiival commented on composables/transaction/mintCollection/transactionMintCollectionStatemine.ts
> +      ...royaltyArgs,
This has to be the last arg :) (or minimally afer create Collection)

2024-01-24 12:22 UTC, vikiival requested changes
~ One thingie

2024-01-26 10:40 UTC, vikiival approved these changes

2024-01-26 14:06 UTC, roiLeo approved these changes

2024-01-27 06:57 UTC, preschian approved these changes
lgtm (not tested)

2024-01-27 16:09 UTC, yangwao commented
Thanks!
pay 50 usd

2024-01-27 16:09 UTC, merged

2024-01-27 16:09 UTC, yangwao commented
😍 Perfect, I’ve sent the payout 
💵 $50 @ 6.7 USD/DOT ~ 7.463 $DOT
🧗 [16DkEx1FzrKqTLPqTJNsSosKJ2UGbUVoLEhiGFFV8cYFpfj1](https://polkadot.subscan.io/account/16DkEx1FzrKqTLPqTJNsSosKJ2UGbUVoLEhiGFFV8cYFpfj1)
🔗 [0x1080b1af0be627cbf45bdbe0209108ddade731c37fc6d9184cd447810cff4240](https://polkadot.subscan.io/extrinsic/0x1080b1af0be627cbf45bdbe0209108ddade731c37fc6d9184cd447810cff4240)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)