fix: No search icon on devices from 1024 -> mobile
kodadot/nft-gallery pull request #9269
Opened 2024-02-04 03:02 UTC by hassnian

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #9267

## Needs Design check

- @exezbcz please review

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD)

## Screenshot 📸

- [ ] My fix has changed **something** on UI;

2024-02-04 06:40 UTC, preschian approved these changes

2024-02-04 10:33 UTC, exezbcz commented
not sure if its the right solution 

filtering based on touchdevices have some edge cases when the search icon should be there as well 

![image](https://github.com/kodadot/nft-gallery/assets/90852205/71b8c4d6-0e69-4c66-b9c5-83784495c68e)

- this is no touch, but smaller window 

the thing is that the search bar is not displayed when the navbar is collapsed - there is then no way how to access the search

2024-02-04 10:47 UTC, preschian commented
> this is no touch, but smaller window

@hassnian time to use this instead https://github.com/kodadot/nft-gallery/issues/8767

2024-02-04 19:44 UTC, roiLeo requested changes

2024-02-04 19:44 UTC, roiLeo commented on components/Navbar.vue
> +            v-if="isMobileNavbarOpen || isTouch"
```suggestion
```

this is not needed parent class has already `lg:!hidden`

same form `<Search />` component near it

2024-02-05 16:03 UTC, prury commented
as talked with @hassnian on dm, page is now generating two search components, one hidden and another one visible

when searching we also get duplicated hidden/visible results(comparison to canary): 
![image](https://github.com/kodadot/nft-gallery/assets/36627808/1703149c-f50b-4755-b1cd-4afbfc279b45)
![image](https://github.com/kodadot/nft-gallery/assets/36627808/5cef326a-e1c5-4089-858c-792b78aa652e)

solution for tests was to make playwright search only for visible elements within page, although code now a bit more clunky

2024-02-05 16:25 UTC, exezbcz commented
@prury better to probably rewrite since the search component does not change based on whether its visible on landing page or not - its always in the navbar 


making it only change to a icon on certain breakpoint would be best solution

2024-02-06 12:38 UTC, yangwao commented
Thanks!
pay 30 usd

2024-02-06 12:38 UTC, merged

2024-02-06 12:38 UTC, yangwao commented
😍 Perfect, I’ve sent the payout 
💵 $30 @ 6.69 USD/DOT ~ 4.484 $DOT
🧗 [16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD](https://polkadot.subscan.io/account/16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD)
🔗 [0x80d1d11fb645baaadf96dec35cda1dad5f5c6689b3ec1bfa8c19de5620a2c9e1](https://polkadot.subscan.io/extrinsic/0x80d1d11fb645baaadf96dec35cda1dad5f5c6689b3ec1bfa8c19de5620a2c9e1)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)