fix: transfer page buttons alignment
kodadot/nft-gallery pull request #9531
Opened 2024-02-23 05:56 UTC by iMac7

**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [ ] Closes #9530
- [ ] Requires deployment <snek/rubick/worker>

#### Before submitting pull request, please make sure:

- [ ] My contribution builds **clean without any errors or warnings**
- [ ] I've merged recent default branch -- **main** and I've no conflicts
- [ ] I've tried to respect high code quality standards
- [ ] I've didn't break any original functionality

#### Optional

- [ ] I've tested it at </ksm/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=14dLrAvjDw7cFLaxM7VWR6YtHd7bGZY2QpzXDhAJJ4yv6oGw&amount=0)

#### Community participation

- [x] [Are you at KodaDot Ecosystem Telegram?](https://t.me/kodadot_eco)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
![Screenshot_20240223_085434](https://github.com/kodadot/nft-gallery/assets/76876702/99aec145-5b12-444d-a258-e2c9a4e66290)

2024-02-23 06:54 UTC, hassnian commented
@iMac7 pls also center them

2024-02-23 07:14 UTC, iMac7 commented
done

2024-02-23 12:17 UTC, hassnian reviewed
the root cause of the issue , some other buttons might also be broken 

![CleanShot 2024-02-23 at 17 16 22@2x](https://github.com/kodadot/nft-gallery/assets/44554284/fe900e86-aa3b-4dd0-863b-229316549b0f)

2024-02-23 12:19 UTC, hassnian approved these changes

2024-02-23 22:06 UTC, Jarsen136 commented
> the root cause of the issue , some other buttons might also be broken
> 
> ![CleanShot 2024-02-23 at 17 16 22@2x](https://private-user-images.githubusercontent.com/44554284/307318546-5efa6b0c-772e-4c6e-ae1b-1515963e16e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3MjYwNjAsIm5iZiI6MTcwODcyNTc2MCwicGF0aCI6Ii80NDU1NDI4NC8zMDczMTg1NDYtNWVmYTZiMGMtNzcyZS00YzZlLWFlMWItMTUxNTk2M2UxNmU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDIyMDI0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyZmQ1ODVjZDg3NTQ0YTAzMTlhZDU5MGQ4Y2ZjMDIwMzI4NjAxZTJkNWI1NDIxMjdkMTc0ODcyYjY0ZWFkYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7mVB92oFD8WRXIeIe7yUFxzN2YaYiwtQvTZKf0eQSpc)


Maybe we should fix the root issue instead of adding a fix every place.
<img width="326" alt="image" src="https://github.com/kodadot/nft-gallery/assets/31397967/cf0fd525-e58f-40ac-bb68-f7bb3bd3eef6">

2024-02-23 22:06 UTC, Jarsen136 requested changes
.

2024-02-24 06:37 UTC, iMac7 commented
> the root cause of the issue , some other buttons might also be broken
> 
> ![CleanShot 2024-02-23 at 17 16 22@2x](https://private-user-images.githubusercontent.com/44554284/307318546-5efa6b0c-772e-4c6e-ae1b-1515963e16e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3NTY4NDgsIm5iZiI6MTcwODc1NjU0OCwicGF0aCI6Ii80NDU1NDI4NC8zMDczMTg1NDYtNWVmYTZiMGMtNzcyZS00YzZlLWFlMWItMTUxNTk2M2UxNmU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI0VDA2MzU0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0N2FmNTRlNDIxNjhkMzhkMDJjMGMxNDM3NGY0YjQ3MTRmY2I4ZmJlYmI1ZjE4YzM3YzUxYmE3Y2Q2ODU4ODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8AflV9RqEgZKVAHKf4T6hx_n6rUxyJMWuWRK0wslmOs)

nice catch, any reason it might have been commented out? I hope undoing this doesn't break anything :eyes:

2024-02-24 06:39 UTC, hassnian commented
@iMac7 check any pill variant used inside that pr and see if you can add a local fix there

2024-02-25 14:55 UTC, iMac7 commented
> @iMac7 check any pill variant used inside that pr and see if you can add a local fix there
Just uncommenting [this](https://github.com/kodadot/nft-gallery/pull/9394/files#diff-6cac81a09ae16a212a724a6359cce50c6031ffb32b5746b2fc6c34c2164e93e0) seems to fix things, are you suggesting I leave the comment as it is and apply local fixes on the pill buttons?

2024-02-27 08:18 UTC, Jarsen136 commented on libs/ui/src/components/NeoButton/NeoButton.scss
> -      // commented out in https://github.com/kodadot/nft-gallery/pull/9394
You should check what causing the issue #9394 here and fix it.

2024-02-27 11:16 UTC, daiagi commented
Oh yes.
I commented that line out
It was causing wierd behviour on code Checker pill variant buttons

So whatever fix is. Please check that buttons over there stay centered
Pay attention to button that have icon as well

https://canary.kodadot.xyz/code-checker

2024-02-27 11:24 UTC, iMac7 commented
> Oh yes. I commented that line out It was causing wierd behviour on code Checker pill variant buttons
> 
> So whatever fix is. Please check that buttons over there stay centered Pay attention to button that have icon as well
> 
> https://canary.kodadot.xyz/code-checker

it was happening on the pill variants, any style that overrides a similar style in `NeoButton.scss` is not applied

2024-02-28 23:47 UTC, closed without merging