holders tab changes
kodadot/nft-gallery pull request #9633
Opened 2024-03-05 12:30 UTC by iMac7

**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #5696 
- [ ] Requires deployment <snek/rubick/worker>

#### Before submitting pull request, please make sure:

- [ ] My contribution builds **clean without any errors or warnings**
- [ ] I've merged recent default branch -- **main** and I've no conflicts
- [ ] I've tried to respect high code quality standards
- [ ] I've didn't break any original functionality

#### Optional

- [ ] I've tested it at </ksm/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer?target=14dLrAvjDw7cFLaxM7VWR6YtHd7bGZY2QpzXDhAJJ4yv6oGw&usdamount=undefined)

#### Community participation

- [x] [Are you at KodaDot Ecosystem Telegram?](https://t.me/kodadot_eco)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
![Screenshot_20240305_152848](https://github.com/kodadot/nft-gallery/assets/76876702/c2b07738-d778-483b-a101-b99f66aa175f)

2024-03-05 16:38 UTC, exezbcz commented
i think its missing the "bought xx days ago" 


![image](https://github.com/kodadot/nft-gallery/assets/90852205/5cc13e8c-6da2-408e-a325-787c15a86446)


As the issue is 
![image](https://github.com/kodadot/nft-gallery/assets/90852205/735fb241-84ee-4c6b-bd49-a7464b4a97fa)

2024-03-05 16:41 UTC, exezbcz commented
and also i think the holding for should be "longest hold" 

so, longest time period out of the all items

lets say you hold items for: 
10, 12, 20, 40 days 

longest hold = 40 

it is on the items you own, not all time

2024-03-05 21:34 UTC, Jarsen136 requested changes

2024-03-05 21:34 UTC, Jarsen136 commented on composables/collectionActivity/helpers.ts
> +      new Date(nft.updatedAt).getTime(),
Is this time correct? If user relists the nft with a new price, the `updatedAt` may change. It does not represent holding time.

2024-03-06 11:40 UTC, Jarsen136 commented on composables/collectionActivity/helpers.ts
> +      new Date(nft.updatedAt).getTime(),
Thanks for showing an example. You're right.

2024-03-06 11:41 UTC, Jarsen136 approved these changes

2024-03-06 11:41 UTC, Jarsen136 commented on components/collection/activity/ownerInsightsTabs/HolderTab.vue
> +import { formatSecondsToDuration } from '~/utils/format/time'
```suggestion
import { formatSecondsToDuration } from '@/utils/format/time'
```

2024-03-07 17:47 UTC, prury commented
let's see if i understood correctly: 
Take this [User](https://deploy-preview-9633--koda-canary.netlify.app/ahp/u/13zFVp9pdsJCJPeVBBRiSAkhBgZ4qENVEZBvfbs9Ft4rHVM8?collections=82) for example, he owns [nine Alchemy NFTs](https://github.com/kodadot/nft-gallery/assets/36627808/ac0055c4-e74b-451a-9f3e-dd46dabec68f) and in the list inside collection i can see that all of them but one is being held for 22 days

![image](https://github.com/kodadot/nft-gallery/assets/36627808/7bdd4578-6911-4044-a8a0-7d2e5d0389d5)

![image](https://github.com/kodadot/nft-gallery/assets/36627808/a5de2fbe-615e-4b75-b9a4-b8063afcb004)

wouldn't it be the longest hold 1 month? since he still owns the nfts? 

collection for analysis: https://deploy-preview-9633--koda-canary.netlify.app/ahp/collection/82/activity

@exezbcz wdyt?

2024-03-09 10:22 UTC, exezbcz commented
one last thing

hover over items: 

deploy:
![image](https://github.com/kodadot/nft-gallery/assets/90852205/69adc983-6e5a-4394-9a70-9df279a493c4)



canary: 
![image](https://github.com/kodadot/nft-gallery/assets/90852205/ff8894ff-969b-4716-afd8-324b74f558ec)

2024-03-09 11:03 UTC, exezbcz commented
@iMac7 thank you 


@preschian could you please review? 👀

2024-03-10 09:36 UTC, preschian approved these changes
code lgtm

2024-03-10 09:39 UTC, exezbcz approved these changes

2024-03-11 00:41 UTC, prury commented
by looking at the holders i still see incorrect info about the longest holder
go to: https://deploy-preview-9633--koda-canary.netlify.app/ahp/collection/82/activity
search for vikiival:
![image](https://github.com/kodadot/nft-gallery/assets/36627808/b5d6d915-26bb-4a81-8b40-1bb2be7ee8c4)

he is holding this nft for more than 1 month: https://deploy-preview-9633--koda-canary.netlify.app/ahp/gallery/82-198

2024-03-12 12:04 UTC, yangwao commented
I see it's thing in interpretation until it hits 2 months, showing 1 month, do I get it correctly?

2024-03-12 12:58 UTC, iMac7 commented
> I see it's thing in interpretation until it hits 2 months, showing 1 month, do I get it correctly?

Yes

2024-03-12 12:59 UTC, yangwao commented
Thanks!
pay 50 usd

2024-03-12 12:59 UTC, merged

2024-03-12 12:59 UTC, yangwao commented
😍 Perfect, I’ve sent the payout 
💵 $50 @ 10.66 USD/DOT ~ 4.69 $DOT
🧗 [14dLrAvjDw7cFLaxM7VWR6YtHd7bGZY2QpzXDhAJJ4yv6oGw](https://polkadot.subscan.io/account/14dLrAvjDw7cFLaxM7VWR6YtHd7bGZY2QpzXDhAJJ4yv6oGw)
🔗 [0x265eca75c1d14e7bdb7665e5c440454613aa58721a12ae2735fa6bdf55ae101a](https://polkadot.subscan.io/extrinsic/0x265eca75c1d14e7bdb7665e5c440454613aa58721a12ae2735fa6bdf55ae101a)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)