Feature: Generative art toolbar
kodadot/nft-gallery pull request #9791
Opened 2024-03-16 09:52 UTC by Temidayo32

**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

- [x] Closes #9737
- [ ] Requires deployment <snek/rubick/worker>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [ ] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality

#### Optional

- [ ] I've tested it at </ksm/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Did your issue had any of the "$" label on it?

- [ ] Fill up your DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=14rs1iTduAn9YrqtDwsTZxK9YDbkzDekBstqxc78M6An87fX&usdamount=0)

#### Community participation

- [x] [Are you at KodaDot Ecosystem Telegram?](https://t.me/koda_eco)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

![image](https://github.com/kodadot/nft-gallery/assets/87539866/2ae17ee1-bdb8-4cc5-bd66-bef768ddffac)

2024-03-16 10:05 UTC, exezbcz commented
<img width="526" alt="image" src="https://github.com/kodadot/nft-gallery/assets/90852205/6df1aa42-02f8-4687-a861-c79dc6c2e9d0">
<img width="707" alt="image" src="https://github.com/kodadot/nft-gallery/assets/90852205/9e50c551-c1cd-4e2f-885a-a484acef750e">


please use correct font awesome iccons and match the padding (button size)

2024-03-16 14:02 UTC, exezbcz commented
even worse
<img width="1687" alt="image" src="https://github.com/kodadot/nft-gallery/assets/90852205/6017c589-8fc2-48fe-9df9-936b10b5e4b0">


check again

2024-03-16 16:17 UTC, Temidayo32 commented
> even worse <img alt="image" width="1687" src="https://private-user-images.githubusercontent.com/90852205/313409125-6017c589-8fc2-48fe-9df9-936b10b5e4b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2MDQ4NzQsIm5iZiI6MTcxMDYwNDU3NCwicGF0aCI6Ii85MDg1MjIwNS8zMTM0MDkxMjUtNjAxN2M1ODktOGZjMi00OGZlLTlkZjktOTM2YjEwYjVlNGIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE2VDE1NTYxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhNDc1M2Y3ZDIxMjBmZDAzOTBmM2ZiN2UyYzhiZjg5NWUyNGM3YmM1NGU0OTExOTYzOGFiOGM1Y2ZiNTUzZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ryxfLGBuFIXFheE7Jft4ubFJwutbinKoX_pcwCQ4q8U">
> 
> check again

@exezbcz  I'm not sure I get the specific element you are referring to here. The reload is working alright on my end here. That is, using the netlify instance generated for this PR. I would appreciate if you can help me know the specific issue here you are pointing out.


Uploading reload - Made with Clipchamp.mp4…

2024-03-16 16:28 UTC, exezbcz commented
@Temidayo32 size

2024-03-17 14:37 UTC, exezbcz commented
sir, the icons are not centered 
<img width="419" alt="image" src="https://github.com/kodadot/nft-gallery/assets/90852205/b2c127cd-30ae-4fc1-bf82-ad1ac12f22be">

2024-03-17 14:53 UTC, exezbcz commented
aaand one more thing, the toolbar should show only on generative art

2024-03-18 19:48 UTC, prury commented
@Temidayo32 
- Checked again and bar its also showing for non-generative items(should be like exez pointed, only shown on generative art items)
- tooltip also not present

2024-03-18 21:21 UTC, Temidayo32 commented
> @Temidayo32
> 
> * Checked again and bar its also showing for non-generative items(should be like exez pointed, only shown on generative art items)
> * tooltip also not present

I think I might appreciate some clarification as regards the route for generative and non-generative items. I assumed all generative items are on the `[id]/gallery/` path

2024-03-18 21:45 UTC, prury commented
> > @Temidayo32
> > 
> > * Checked again and bar its also showing for non-generative items(should be like exez pointed, only shown on generative art items)
> > * tooltip also not present
> 
> I think I might appreciate some clarification as regards the route for generative and non-generative items. I assumed all generative items are on the `[id]/gallery/` path. It appears to me this is not the case.

cc:
@kodadot/internal 

Also, i think you removed the fullscreen functionality completely, and that should not be the case. 
the bar should only appear to specific genart collections(the ones that are animated)

2024-03-18 23:24 UTC, Jarsen136 requested changes
> I assumed all generative items are on the `[id]/gallery/` path. It appears to me this is not the case.

At least you could check if the `mimeType` is iframe.

2024-03-18 23:24 UTC, Jarsen136 commented on components/gallery/GalleryItem.vue
> +const generativeArtToolbar = computed(() => route.path.includes('/gallery'))
.

2024-03-19 08:34 UTC, Temidayo32 commented
> > > @Temidayo32
> > > 
> > > * Checked again and bar its also showing for non-generative items(should be like exez pointed, only shown on generative art items)
> > > * tooltip also not present
> > 
> > 
> > I think I might appreciate some clarification as regards the route for generative and non-generative items. I assumed all generative items are on the `[id]/gallery/` path. It appears to me this is not the case.
> 
> cc: @kodadot/internal
> 
> Also, i think you removed the fullscreen functionality completely, and that should not be the case. the bar should only appear to specific genart collections(the ones that are animated)

I don't think the fullscreen functionality is removed
![2024-03-19 09-19-09](https://github.com/kodadot/nft-gallery/assets/87539866/74496aee-a84e-43d8-95e5-a2b462793d07)

2024-03-19 10:33 UTC, vikiival commented
[Closing as this PR used force-push](https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#is-it-of-good-quality)

Please do open a new PR without force push.

![Screenshot 2024-03-19 at 11 31 28](https://github.com/kodadot/nft-gallery/assets/22471030/1f10931a-0733-458c-9a65-5b38a8e33acb)

2024-03-19 10:33 UTC, closed without merging